### ISSUE TITLE
Fix versions of test files to 3.1.0

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1001]
- [x] (DF) check which test files are in use, fix or remove remaining
- [x] change all versions to 3.1.0
- [x] add yaml_converter a flag to apply rules from given orig version ignoring the version of the file if it is newer.

**Comment by dflanderka** [comment]
point _check which test files are in use_
 - benchmark tests of native data (02 / 41, 02 / 42) are solved in branch DF_set_velocity_field
 - in dir 05_tutorial are tests with same number in filename
 - tests 12 / 15 and 12 / 20 return incorrect results
 - remaining resolved

**Comment by jbrezmorf** [comment]
@Paulie14 
- [ ] where are 02/41 and 02/42 ? 
- [ ] resolve duplicity numbers in tutorial tests
- [ ] separate issue for 12/15 and 12/20, these are tests of non-compatible mortar coupling, just describe where the difference started

Then close.

Proposed change in the yaml_converter not clear. Won't resolve.

**Comment by dflanderka** [comment]
Benchmark tests of native data 02/41 and 02/42 were moved to dir 03_generic_output.

**Comment by Paulie14** [comment]
I am not sure, why the duplicit numbers in tutorials are problem.
These are actually variants of the same problem (with/without fractures, with/without dual porosity),
so I would suggest 04a, 04b and 06a, 06b e.g..

**Comment by jbrezmorf** [comment]
I see. Unique numbers would be better for reference and for tutorials also for the user.
I suggest naming 04 the main and 04a the auxiliary variant.
Possibly replace "blind fracture" with "dead-end fracture".

**Comment by Paulie14** [comment]
OK, agree, I'm on it.

**Comment by Paulie14** [comment]
Several fixes and improvements by PR #1358.
Mortar tests issue #1357.
