### ISSUE TITLE
Documentation IST in LaTex format is incomplete - includes only selections.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1006]
The latex documentation in master contains only SelectionType keys.
The generated ```input_reference.json``` file seems to have all the keys, but the ```input_reference.tex``` contains only SelectionType keys.

Console output of ```make ref-doc``` for 2.2.1 and master seemed nearly the same to me, so I do not understand.

**Comment by jbrezmorf** [comment]
fixed
