### ISSUE TITLE
Simplify DofHandler

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1009]
- [x] Introduce unordered_map : global_to_local, mapping global element indices after partitioning to local own and ghost indices. Nevertheless mark this variable as **obsolete**. It is just temporary solution how to map ElementAccessors to DHCellAccessors until we have parallel mesh. So this mapping should be used only in 
corresponding method dh ->DHCellAccessor(ElementAccessors).
- [x] Replace/remove row_4_el, ghost_4_loc, el_4_loc.
- [x] Are other vectors in DH necessary? In particular edg_4_loc, node_4_loc, ghost_proc, ghost_proc_el (private?), cell_starts_seq, dof_indices_seq
- [x] cell_starts should map only local =own and ghost elements

**Comment by jstebel** [comment]
The arrays ghost_4_el, el_4_loc cannot be removed. Some information about local-to-global element index is needed. Maybe we should use one array for both local and ghost elements? In addition, this array has to be a part of Mesh object.

**Comment by jbrezmorf** [comment]
Problem is 'ghost_4_el' array, which do not scale. We should have its inverse which in fact should be part of el_4_loc. There we first index own elements and then provide local to global mapping for the ghost elements.

That should be part of parallel mesh, no doubts.

**Comment by jstebel** [comment]
Sorry, it is ghost_4_loc, not ghost_4_el. So shall we keep it now?

**Comment by jbrezmorf** [comment]
FIne, we keep it and finally we merge both into single array in the parallel mesh implementation.

**Comment by jstebel** [comment]
OK. Done.
edg_4_loc - needed in assembling of DG terms (maps local to global edges)
ghost_proc, ghost_proc_el - needed in communicating ghost dofs between processors.
Resolved in #1017.

**Comment by jbrezmorf** [comment]
global_to_local_el_idx is obsolete but used on many places, we have to reduce this having just:
- place where this aux map is created
- single method to create DHCell from global element index
