### ISSUE TITLE
Finish application of DHCell ranges

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1014]
We need replace methods of DOFHandler that depend on ElementAccessor with methods of DHCellAccessor with same functionality (method get_dof_indices). In the following cases we can make a replacement after the changes of DOF handler will be complete.

- [x] (blocking) (JS) #1009 global to local map and related DofHanlder simplification.
- [x] should fix calculation of FieldFE outputs (FieldFE, FEValueHandler and VectorSeqDouble) 
- [x] TrasnportDG - use calculation over ghost elements (only in methods assemble_fluxes_element_element and assemble_fluxes_element_side), done in #1018 
- [x] DOF handler unit test needs change loops over mesh elements

- [x] Remaining DofHandler methods to remove:
cell_dof, fe, el_is_local, n_dofs, el_index, get_loc_dof_indices, get_dof_indices, loffset
(possibly move some methods into protected section).

**Comment by dflanderka** [comment]
Only part of DofHandler methods can be removed:

- cell_dof: used only in DH - moved to protected 
- fe: used method of DHCellAccessor - replaced
- el_is_local: needs finish of DF_dh_sub_accessors (use in TransportDG + DH)
- n_dofs: used only in DH - moved to protected 
- el_index: used only in DH - moved to protected 
- get_loc_dof_indices: only global get_dof_indices method is used now
- get_dof_indices: need finish parallel cache and output (remains replace in field.hh, flow_mh_output.cc, field_fe.cc)
- loffset: removed, returned parameter loffset_ is used only locally

**Comment by jbrezmorf** [comment]
filed_fe.hh  - method "fill_output_data", will be replaced by direct output of computational fields or output fields
field_fe.cc - methods "calculate_native_values", "native_data_to_cache" ; input and output ofserial native element data cache, need to be sure that native data use global element indices
- check that we can perform serial native  output of parallel fields
- check that global dof handler indices of elements will be same for any number of processors, need carefull support in parallel mesh (sort of element ID that will be same for any mesh distribution)

darcy_flow_mh_output.cc - method "make_corner_scalar", replacement should work after parallel data caches are done

**Comment by jbrezmorf** [comment]
final resolution depends on #1015 and #1016.
