### ISSUE TITLE
Apply parallel DofHandler to TransportDG

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1015]
- [x] DHCellAccessor range to loop over sides using DHCellSideAccessor
- [x] DHCellSideAccessor range to loop over all Cells (of same dim) connected to the side
- [x] DHCellAccessor range to loop over all sides of the cells of higher dimension
- [x] Rewrite assembly in TransportDG to use single loop over elements and for every element call current main assembly methods for: volume assembly, edge or element-element assembly, boundary assembly, compatible neighbours assembly.
    - element-side: main loop over local elements
    - element-element: 
        - main loop over local elements
        - DHCellSide::edge_sides - return empty range if edge is not local (do not have any local element). 
        - for master_el loop over sides, get edge_sides range, if the first element of the range is not master_el continue. Else assembly local matrix and use only local rows for the global one.

- [x] Switch to parallel DofHandler ... parameter serial=False
- [x] [blocker ] #1016 - resending of parallel data to serial OutputStreams

**Comment by jbrezmorf** [comment]
- Start with setting data_.output_field to parallel DofHandler and let it make its own parallel vector and set it into output_vec.
- remove call to output vec gather

**Comment by jbrezmorf** [comment]
- add DHCell::is_own() ... using code from el_is_local
- unify all assembly methods to have main loop over all local elements, possibly use is_own to skip ghost elements
- in element-element assembly remove el_is_local:
    - replace loops over edge sides by loop over edge_side range
    - try to implement Iter wit conversion, use it in edge_side range and neigbour_side range in order to
      use EdgeSide and NeighbourSide classes only internally (for iterating), and using only DHCellSide for the access
    - try to remove first its usage, seems unnecessary
    - replace second usage by calling DHCell::is_own ( before the pair loop)
- in element-side  assembly remove el_is_local, similarly

**Comment by jbrezmorf** [comment]
- make Side::diameter() method, move there code from beginning of set_DG_parameters_edge
- move calculation of pflux, nflux into element_element assembly to the loop where fluxes vector is calculated
- remove branches for s1==s2
- move whole method into element-element assembly
- try to replace edg, s1,s2 by side accessors

**Comment by dflanderka** [comment]
Merged in ff06a57.
