### ISSUE TITLE
Parallel ElementDataCache

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1016]
- [x] Check how tests of parallel VTK output works.
- [x] Support for serialization of parallel element data caches:

- [x] Add reference output for parallel output tests in master branch. Use 3 processors.
- [x] Merge make_serial_master_mesh for continuous and discontinuous output mesh. Drop dependecy on orig_mesh_ extract all necessary data in create_mesh or create_submesh. Use auxiliary virtual methods for different code fragments.

- [x] Check all variants that should be covered by generic output tests:
    - serial solution, serial output, continuous/discontinuous, VTK/GMSH
    - parallel solution, parallel output, continuous/discontinuous, VTK
    - parallel solution, serial output, continuous/discontinuous, VTK/GMSH

- [x] Fix support for refined discontinuous output mesh.

**Comment by jbrezmorf** [comment]
@dflanderka wrote:
Check how tests of parallel VTK output works:
pro paralelní výstup se z EquationOutput volá OutputMeshDiscontinuous::create_sub_mesh(),
takže paralelní výstup funguje jako nespojitá síť.

Map from local to global element and node IDs:
- pro elementy máme už nyní k dispozici OutputMesh::orig_element_indices_, která pro
  paralelní výstup obsahuje pro lokální elementy seznam idx do globální (výpočetní) meshe.
  Z nich už IDs získáme jednoduše. Toto mapování by fungovalo i pro spojitou síť.
- pro nodes se podobným způsobem plní cache nodes_ a connectivity_, pro spojitou síť
  toto nefunguje

Implement renumbering of local element and node indices to global indices:
pro VTK už nám toto poskytují orig_element_indices_ a nodes_, pro GMSH získáme původní
indexy vytvořením ElementAccessor a NodeAccessor.

Z předchozích poznámek vyplývá, že mnoho máme implementované. Zbývá dořešit nodes_
pro paralelní spojitou síť a existující implementace jen 'jinak' použít.

**Comment by jbrezmorf** [comment]
1. Vidím (jak upozorňuješ), že metoda create_submesh() je implementována jen pro OutpuMeshDiscontinuous. My bychom to potřebovali mít i pro spojitou OutputMesh. 

2. Pro vystup do VTK (paralelni nebo seriovy) potrebujeme ElementDataCache promenne: nodes_, offsets_, connectivity_. V pripade paralelnho VTK jsou v poli connectivity_ indexy nodu do lokalniho pole nodes_. Ovsem v pripade serioveho VTK tam potrebujeme mit globalni indexy uzlu.

3. Řekněme, že máme na každém procesoru vytvořenou tu submesh (spojitou nebo nespojitou). Chceme na nultém procesoru získat pole nodes_, offset_, connectivity_ sloucena ze vsech procesoru a to same chceme umet pro data na te siti (na uzlech nebo na elementech). To proběhne následovně:
    1. Distribuce uzlů sítě, každý uzel bude patřit jen jednomu procesoru.
    2. Scatter pro elementová a uzlová data. Lze to udělat pomocí PetscScatter objektu, ale spíše si to
    zabalíme do něčeho vlastního. Jde o to vzít z každého procesoru jeho část dat a poslat ji na nultý
    procesor a tam ty časti dat do jednoho pole za sebe.
    3. na každém procesoru přečíslovat connectivity_ z lokálních indexů uzlů na globální indexy
    4. Přeposlat nodes_ pomocí scatteru pro uzlová data.
    5. Přeposlat connectivity_ pomocí scatteru pro elementová data. Pro kždý element se budou posílat 4
    indexy i když bude nižší dimenze. Prázdné indexy se musí nastavit na -1.
    6. Na nultém procesoru se projde sloučené pole connectivity_, odstraní se -1 a vytvoří se příslušné pole
    offset_.
     

Pro elementy tedy tu mapu máme. Pro nody tedy patrne ne, nerozumím poznámce "pro spojitou síť toto nefunguje". Budeme tedy potřebovat v metodě create_sub_mesh vytvořit tu mapu pro nody.
Další komplikace nastane se zavedením paralelní výpočetní sítě, ale to nás teď netrápí.

Máme tedy paralelní síť a na ní se vypočtou data, paralelní výstupní síť i data na ní jsou v ElementDataCache. V případě sériového výstupu však musíme nody a uzly v dílčích ElementDataCache přečíslovat podle těch map z lokálního na globální číslování (pokud to tak ještě není). A následně potřebujeme všechno poslat na nultý procesor a tam sloučit hodnoty pro uzly poslané od více procesorů.
Sloučení se udělá pomocí průměru, nebo se může předpokládat, že jsou hodnoty stejné a prostě tu hodnotu přepíše více procesorů.

**Comment by dflanderka** [comment]
ad bod 3. ii.
Není mi úplně jasné využití Distribution objektu. Výpočetní mesh má k dispozici svoji Distribution pro elementy, ale nikoliv pro nodes. Pokud se nevyhneme použití Distribution pro nodes, jak zajistíme, aby objekt odpovídal lokálním distribucím na jednotlivých procesorech vytvořeným v předchozím bodě?

**Comment by jbrezmorf** [comment]
1. modifikovat Mesh:distribute_nodes, aby node_4_loc zahrnovalo globalni indexy i pro ghost elementy.
    - pruchod pres vsechny elementy, pridat citac pro vsechny lokalni nodes
    - pruchod pre lokalni elementy roztridit node na OWN a GHOST
2.  sloucit create_serial_sub_mesh a create_parallel_sub_mesh. Algoritmus podobny ze serial, ale lokalni cisla uzlu v connectivity_
3. uprava make_serial_master_mesh: 
    - posilat jen OWN casti nodes poli, asi hlavne nodes_
    - pred poslanim precislovat (do noveho pole) connectivity na global
4. vyhodnocovani poli pro NODE_DATA jako pro CORNER_DATA
    v OutputTime (write_frame??): 
    - preposlani
    - prumerovani na NODE_DATA
    - vystup

**Comment by jbrezmorf** [comment]
- vypocty fields i preposilani delat na spojite siti
- konverzi connectivity a nodes na discontinuous provadet explicitnim volanim az v OutputTime

**Comment by dflanderka** [comment]
Úprava OutputMesh je v základních rysech hotová. Tvorba OutputMesh pro spojitou i nespojitou síť provádí create_sub_mesh (společná pro obě třídy) a make_serial_master_mesh. Původní metoda create_mesh je odstraněna. Veškeré výpočty (včetně node data) probíhají iterací přes elementy. Přibyly pomocné metody v ElementDataCache.   

Pro úplnou funkčnost testů zbývají dořešit následující dva body:
- v TransportDG<Model>::initialize se output vektory pro substances nastavují jen pro rank 0, kde se naplní všechny hodnoty. To potřebujeme změnit, aby se hodnoty ukládaly lokálně na procesorech.
- pro refined mesh nelze použít současný algoritmus v make_serial_master_mesh, který iteruje přes elementy. Pro vytvoření refined serial master mesh bude nejspíš třeba speciální metoda.

**Comment by jbrezmorf** [comment]
TransportDG: nech metodu set_fe_data at si vytvori vlastni paralelni vektor podle paralelniho DH.
Ani by se nemel nakonec pouzivat seq. DH: feo->dh()->sequential() ale paralelni DH.
V output_data by pak nemel byt nutny scatter.

Netusim, co to udela s reakcemi.

**Comment by dflanderka** [comment]
Metoda set_fe_data má VectorMPI jako optional parametr a pokud není zadaný, vytvoří si vlastní vektor podle DOFHandleru a ten metoda vrací. Reakce to neovlivní, ale tím, že vynecháme volání Scatteru, nenaplní se hodnoty output vectoru, které se v tomto kroku předávaly z LinSys (viz. TransportDG::output_vector_gather). 
Potřebujeme tedy jinou metodu metodu, která zajistí předání hodnot do output vec. Očekávám, že Linsys na každém procesu obsahuje lokální hodnoty a pořadí odpovídá indices v DOF handleru. Takže by je mělo stačit překopírovat.

**Comment by jbrezmorf** [comment]
DOF handler se vytvori vlasni paralelni vektor a ten predame do Linsysu jako vektor pro reseni. output vec bude mozna mozne zrusit.

**Comment by dflanderka** [comment]
Merged in 306e3aa
