### ISSUE TITLE
Improve MassBalance

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#102]
Weak points of current state:
- DarcyFlowMH has its own mass_balance output
- improve documentation including limitation and possible further developement
- monolithic output, uses unsafe fprintf, 
  make full output in machine readable format, that ideally still can be used e.g. for gnu_plot prinitng
- further make text output configurable by user, namely full balance information is mainly needed for debugging

**Comment by jstebel** [comment]
Resolved in #131 and #219.

**Comment by jbrezmorf** [comment]
Merged in 084284
