### ISSUE TITLE
version 3.0.9 (used to be 3.0.1)

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1042]
- [x] rename to 3.0.9
- [x] changes
- [x] test memory allocation with windows virtualization
- [x] documentation updates

**Comment by janhybs** [comment]
Under Windows, Docker for Windows uses static memory allocation meaning the memory is allocated when docker daemon starts. If maximum of 8GB is allowed by Docker for Windows, 8GB will be reserved. When Daemon is shut down, memory is released. Memory consumption does not change during the computation.
 
Below is memory consumption when daemon is 
:chart_with_upwards_trend:  running, :chart_with_downwards_trend: closed, :chart_with_upwards_trend: running and :chart_with_downwards_trend: closed again. 
![image](https://user-images.githubusercontent.com/894428/53735948-a965b480-3e88-11e9-9912-435f1559b7c2.png)

Below is config dialog where memory limit is set to 2 GB (image is from docs.docker.com)
![image](https://user-images.githubusercontent.com/894428/53736068-fe092f80-3e88-11e9-865b-0a350479e058.png)

More info here https://docs.docker.com/docker-for-windows/#docker-settings-dialog

**Comment by jbrezmorf** [comment]
Damned. This is even worse that behavior of VirtualBox. 
But at least the configuration and docker service restart is quite accessible.
I will check this.

**Comment by jbrezmorf** [comment]
Possibly resolved by the usage of Docker support for native Windows virtualization. Moreover, Linux for Windows may be used.
