### ISSUE TITLE
Native IO tests

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1053]
Issues:
- After change in dof distribution and fix of get_loc_dof_indices the tests for native input fail.

- tests:  02_generic_input/06, 21 - stored input data are incompatible with current dof handler and there is not mentioned how they were created

- seems that we have no test for native-data output 

TODO:
- create tests in 03_generic_output for native_data output
- use these output data (copy output files) in 02_generic_input  native input tests, mention in comment which test to use for generating native input data

**Comment by jbrezmorf** [comment]
- move part of OutputTime::prepare_compute_data into Field::compute_field_data
- Need to rethink how to set native DH for the native input fields. Currently there is no method in the abstract Field API through which one can pass the native DH. Not clear if we want to store the DH along with the mesh.

**Comment by jbrezmorf** [comment]
- seems that output of the Native data works fine (need tests)
- we must fix the input of the native data. Currently we want to support only input of serial output and parallel input when number of processors much (and dof distribution match as well)
- this issue depends on resolution of #1013

**Comment by dflanderka** [comment]
Done in pull #1125
