### ISSUE TITLE
2.2.1 performance regression

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1060]
Milan Hokr reported a significant performance regression:

version 2.1.2 (620b6da), build by JB:
charon.nti.tul.cz/home/milanhokr/test/x01-prazskyflow/
1 proc, time: 445s

version 2.2.1, build by JH:
charon.nti.tul.cz/home/milanhokr/test/x02-modulovyflow/
1 proc, time: 2000s

According to profiler files, majority of the additional time is due to balance output and form schur complement. Numerical results are nearly same.

**Comment by Paulie14** [comment]
I compared:

on my ntb
version 2.2.1, b04af7f
1 proc, time: 515 s, Darcy balance output 10 s

on Charon (module load flow123d/2.2.1)
version 2.2.1, b04af7fb0
1 proc, time: 2181 s, Darcy balance output 1554 s

There must be something wrong with the build on Charon, I guess..

**Comment by Paulie14** [comment]
Problem is also in 3.0.0:
on Charon (module load flow123d/3.0.0)
version 3.0.0, be59f6e6e
1 proc, time: 1894 s, Darcy balance output 1505 s

**Comment by Paulie14** [comment]
According to profiler, the problem is in the function Balance::calculate_instant() v balance.cc:705 in the part 'compute positive/negative sources'.

There is this code (not MatGetRow() particulary):
```for (unsigned int r=0; r<mesh_->region_db().bulk_size(); ++r)
	{
		MatGetColumnVector(region_source_matrix_[quantity_idx], mat_r, r);
		MatGetColumnVector(region_source_rhs_[quantity_idx], rhs_r, r);
```

The build is compiled with mpi-cxx compiler, I can't any other mpi compiler to test...

**Comment by jbrezmorf** [comment]
PETSC doc says this operation is slow and in principle it has to be.

Seems that the matrices region_source_matrix_[i] and region_source_rhs_[i] should be rather transposed.
Even then the problematic code can be rewritten as:
region_fluxes  =  region_source_matrix_ .dot. diag(solution) + region_source_rhs_
Then compute min_region_fluxes and max_region fluxes using MatGetRow which is efficient.

Consult with @jstebel  and reimplement.

**Comment by jbrezmorf** [comment]
**Comparison of the builds.**

fish://jan_brezina@charon.nti.tul.cz/home/jan_brezina/praha/local/flow123d_2.2.0/
commit:  620b6da
modules: openmpi (1.6.5), python-3.6.2-gcc, boost-1.55, gcc-4.9.2, debian8-compat
PETSC: 3.6.1, 
--download-metis=yes --download-parmetis=yes --download-blacs=yes --download-scalapack=yes --download-mumps=yes --download-hypre=yes --with-debugging=0 --with-shared-libraries=0 --with-make-np 8 --CFLAGS=-O3 --CXXFLAGS="-O3 -Wall -Wno-unused-local-typedefs -std=c++11"
Armadillo: 3.4.3
time: 445s

module flow123d/2.2.1
commit: b04af7f
modules:
PETSC: 3.8.3, 
--download-metis=yes --download-parmetis=yes --download-blacs=yes --download-scalapack=yes --download-mumps=yes --download-hypre=yes --with-debugging=1 --with-shared-libraries=1 --with-make-np 8 --CFLAGS="-O3 -DNDEBUG" --CXXFLAGS="-O3 -DNDEBUG -Wall -Wno-unused-local-typedefs -std=c++11"
Armadillo: 8.3.4
time: 2000s

**Comment by jbrezmorf** [comment]
Seems that PETSc 3.8.3 in use are build with debugging!!

**Comment by jbrezmorf** [comment]
So the performance issue is mainly due to debugging build.

**Comment by jbrezmorf** [comment]
Finish optimization in Balance anyway.

**Comment by janhybs** [comment]
ok, so I did a complete rebuild of all packages on Charon in both Debug and Release version (except pugixml and yamlcpp):

| lib | Debug | Release |
|-----------------|--------------------|--------------------|
| armadillo-3.4.3 | :heavy_check_mark: | :heavy_check_mark: |
| armadillo-8.3.4 | :heavy_check_mark: | :heavy_check_mark: |
| bddcml-2.4.0 | :heavy_check_mark: | :heavy_check_mark: |
| bddcml-2.5.0 | :heavy_check_mark: | :heavy_check_mark: |
| petsc-3.6.1 | :heavy_check_mark: | :heavy_check_mark: |
| petsc-3.8.3 | :heavy_check_mark: | :heavy_check_mark: |
| pugixml-1.9.0 | :x: | :heavy_check_mark: |
| yamlcpp-0.5.2 | :x: | :heavy_check_mark: |

Version of the flow(s) will remain the same as the linking is made on the run.

**Comment by janhybs** [comment]
I also run the test on the login node
```sh
module load flow123d/2.2.1
time flow123d /home/milanhokr/test/x01-prazskyflow/4O_flow.yaml
```

and got 
```
real	7m52,205s
user	7m37,400s
sys	0m12,824s
```
[profiler_info_19.04.04_09-56-14.log.json.txt](https://github.com/flow123d/flow123d/files/3042419/profiler_info_19.04.04_09-56-14.log.json.txt)
[profiler_info_19.04.04_09-56-14.log.yaml.log](https://github.com/flow123d/flow123d/files/3042432/profiler_info_19.04.04_09-56-14.log.yaml.log)

**Comment by Paulie14** [comment]
Changes in balance finished by 60b266f0156dc8a54e0ad587ecc9c4c3b48de08a.
Tested on ntb and Charon, the balance output itself shows speedup of factor 10-15.
Pull request  #1069.
