### ISSUE TITLE
DH subblock dof lists

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1062]
Create methods to extract DOFs of given component (of the FeSystem).
Two variants:
- extract only own dofs
- extract all local dofs

This will be used to perform local scatter from full DH to DHs of individual components.

Similar thing for local dofs on single cell.

**Comment by jstebel** [comment]
Need to check dof ordering of full DH and the sub-DH.
Create DH of component from full DH?

**Comment by jbrezmorf** [comment]
Update:
- introduce extraction of DH for given components (necessary for Schur complement and other block preconditioners)
  this has to return both the sub DH as well as the vector that maps sub DH local indices to the full DH local indices
- other use case is manipulation with the edge pressures in Richards
- yet another problem is creation of discontinuous DH to an continuous and interpolation between associated fields, this however is beyond the DH responsibility

**Comment by jbrezmorf** [comment]
Postpone design of interface after changes in DarcyFlow.

**Comment by jbrezmorf** [comment]
Operations:
- get vector of local/ghost dof indices for given components, 
  usage: block solvers
- get sub DH for given components (corresponding to these dofs), 
  usage: assembly using stored components
- extract sub DH dofs from full dof vector creating (scatter from full to sub vector for given components)
  usage: store components

Implementation:
- sub DH could contain just vector of local/ghost dof indices for given components
- extraction of the sub vector through a method of VecMPI, passing in the sub dofs from sub DH.
