### ISSUE TITLE
[windows] Setbacks with new installator

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#1063]
- [x] migration from **Docker Toolbox** to  **Docker for Windows**:

  - [x] causes old instances of flow123d to stop working (this is to be expected but note should be added to docs)
  - [x] requires Windows 10 64bit PRO (also add to the docs)
  - [x] results in non working installation since **Docker Toolbox** stores system variables which **Docker for Windows** loads and uses. Need to manually remove these variables (it is in the script, but does not work), also put it in the docs.

- [x] new mounting system, which always mounts `c` drive and dynamically mounts drive from `cwd` is unstable. On one PC the mouting works correctly, but on other detects wrong drive letter. When spoken to a customer, they would not mind mounting everything during an installation

**Comment by janhybs** [comment]
![image](https://user-images.githubusercontent.com/894428/55219593-9767ff00-5205-11e9-9d5a-8f064b26950c.png)

**Comment by jbrezmorf** [comment]
Very unpleasant. We need a working Flow123d version 2.2.1. So the only way is to backport installer to this stable branch.

The issue with dynamic mounting is not clear to me. Especially what is proposed workaround.

**Comment by janhybs** [comment]
A proposed workaround is to fetch disk letters during an installation and always mount all these drives when using fterm.bat

**Comment by janhybs** [comment]
I may have found the solution, which will dynamically mounts the drive from the `cwd` but need to verify this on a windows platform.

**Comment by janhybs** [comment]
Everything should be fine now, changes are in repo [flow123d-package](https://github.com/flow123d/flow123d-package/commits/master) and some also in branch [3.0.9](https://github.com/flow123d/flow123d/tree/3.0.9). Can be closed.
