### ISSUE TITLE
Slow running of DG transport.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1074]
Running of DG transport tests is too slow after modifying set_velocity_field method.

**Comment by dflanderka** [comment]
Profiler output in master:
[profiler-master.txt](https://github.com/flow123d/flow123d/files/3121300/profiler-master.txt)

**Comment by jbrezmorf** [comment]
Bottleneck function according to callgrind: FeValues<>::init_fe_data(...).

**Comment by jbrezmorf** [comment]
Resolution:
- introduce a getter for the FieldFE value handler for given dim of element and given quadrature
- this new value handler will have a method to compute values on single element

**Comment by jbrezmorf** [comment]
In the future can be extended to the evaluation of the field functionals (e.g. normal fluxes of the velocities).

**Comment by jbrezmorf** [comment]
Resolved in 64d205 and a few previous commits mainly due to avoiding FieldFE operating over the whole FESystem.
