### ISSUE TITLE
Failed tests.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1086]
Solve remaining failed tests in remove_mhdh branch:

- [x] slow runing computation of FieldFE (see #1074 )
- [x] test 02 / 11 flow_observe.yaml - change ref_out data (computes more accurate field values in projected observe points, not values in element center)
- [x] test 40 / 01 - parallel heat output - fix of local to ghost scatter in heat equation
- [x] test 05 / 07 - change ref_out data

**Comment by jbrezmorf** [comment]
Slow field evaluation doesn't matter now, we know how to do better.
Others should be resolved while we have the diff. Its easier to find the problem.
So the first two points come after @dflanderka and the other two after @Paulie14.

**Comment by jbrezmorf** [comment]
Resolved with exception of slow assembly that is solved in separate issue.
