### ISSUE TITLE
Improved Profiler formating

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1111]
Improved sorting of frames:
- for every frame add an "REMAINDER" subframe that is the time of frame - sum_of subframes
- sort subframes by their procentage/time
- show first 5 subframes only, colapse others into virtual subframe "OTHERS" 

... inspiration for the online performance tracker as well.

**Comment by janhybs** [comment]
I do not think that squashing the remainder of the frames by this rule brings anything new to the table - it can obscure the less important frames.
Also, I have yet to encounter a frame which has more than 7 children (couple frames have 6 children, but that would just squash the 6th frame to a "OTHERS")

I suggest to squash frames by the following predicate:
`[absolute-frame-percentage] < 1.0% and [frame-time] < 100ms`

Meaning, the non-significant frames will be collapsed, as their duration or overall impact is minimal.

Below is newly formatted profiler:
[profiler_info.log.human.txt](https://github.com/flow123d/flow123d/files/3836104/profiler_info.log.human.txt)

Other columns such as `[file]`, `[line]`, `[function]` can be easily added, suggestions are welcomed.

**Comment by janhybs** [comment]
Final format now looks like this:
[profiler_info.log.json.txt](https://github.com/flow123d/flow123d/files/3845427/profiler_info.log.json.txt)
