### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by keileg** [flow123d/flow123d#1115]
I would like to add a citation to flow123d in a paper we're writing. Do you prefer that we cite a specific paper we should point to, or should we use a web page?

**Comment by jbrezmorf** [comment]
Thank you Eirik,

unfortunately we do not have a paper devoted to the software yet
so for the software cite the web page,
for the continuum-fracture approach you can cite:


@incollection{Brezina2015,
  series = {Lecture {{Notes}} in {{Computer Science}}},
  title = {Analysis of {{Model Error}} for a {{Continuum}}-{{Fracture
Model}} of {{Porous Media Flow}}},
  copyright = {\textcopyright{}2016 Springer International Publishing
Switzerland},
  isbn = {978-3-319-40360-1 978-3-319-40361-8},
  language = {en},
  number = {9611},
  booktitle = {High {{Performance Computing}} in {{Science}} and
{{Engineering}}},
  publisher = {{Springer International Publishing}},
  author = {B{\v r}ezina, Jan and Stebel, Jan},
  editor = {Kozubek, Tom{\'a}{\v s} and Blaheta, Radim and {\v S}{\'i}stek,
Jakub and Rozlo{\v z}n{\'i}k, Miroslav and {\v C}erm{\'a}k, Martin},
  month = may,
  year = {2015},
  pages = {152-160},
  doi = {10.1007/978-3-319-40361-8_11}
}

Best regards,
Jan

**Comment by keileg** [comment]
Thanks. Will do.
