### ISSUE TITLE
Pass DHCellSide to Balance flux functions.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1117]
Instead of SideIter and dof_indices, use DHCellSide, which has access to both.
It can be done, when DH is usde in all equations and DHCellSide is available.
This is the last thing that remains from the issue #1070.
```
	void add_flux_matrix_values(unsigned int quantity_idx,
			SideIter side,
			const std::vector<LongIdx> &dof_indices,
			const std::vector<double> &values);
```
after:
```
	void add_flux_matrix_values(unsigned int quantity_idx,
			DHCellSide side,
			const std::vector<double> &values);
```

**Comment by Paulie14** [comment]
Possibly merge the matrix and vector methods to a single one add_flux_values.

**Comment by jbrezmorf** [comment]
That would be even better, it seems that they are mostly used together.

**Comment by jbrezmorf** [comment]
Depends on consistent usage of DH accessors in assembly of all equations.

**Comment by Paulie14** [comment]
The only blocker left for this is the old code in transport.cc: ```set_boundary_conditions()```, without DH accessors.

**Comment by Paulie14** [comment]
If we solve the boundary edge numbering, we can use it also for seepage BC, see #1141.

**Comment by Paulie14** [comment]
Passing just DHCellSide is not enough. We can get all the dofs, but we cannot dig out the information which dofs are corresponding to the side and the given values. Passing vector of local dofs is necessary.

**Comment by jbrezmorf** [comment]
Not sure if I understood. I agree that we need both DHCellSide and the vector with actual dof values.

**Comment by Paulie14** [comment]
Done by 40636e7b2ed4d125a5ba5703194be77d6a1167ad.
