### ISSUE TITLE
Failure after lot of timesteps

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1118]
Symptoms:
- calculation terminated after "random" time when many timesteps are preformed 
involving a sequence of steady MH flow problems and Transport DG inside the  TOS.

Probable cause is a memory leak. Possibly in Darcy flow, since I do not remember any case solving so many steady problems. It was reported, that the version 3.0.x runs fine.

Try valgrind for just few first times:
`bin/fterm exec bin/valgrind.sh --leak-check=yes -- inut.yaml`

See two runs in:
`astra.nti.tul.cz/public/josef.chudoba/Chudoba_spadle_ulohy/`

Inputs are nearly the same, 022 have all times where steady flow is solved 10x larger than 021.

**Comment by Paulie14** [comment]
Problem in version 2.2.1 (is almost equal 2.2.0, but adds fterm) is most probably due to the following memory leak (after just 10 time steps):
```
==45== 3,578,028 (19,448 direct, 3,558,580 indirect) bytes in 13 blocks are definitely lost in loss record 4,006 of 4,006
==45==    at 0x4C2FFC6: memalign (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==45==    by 0xC7C893: PetscMallocAlign (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x1224EA9: VecCreate (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0xD9778C: VecDuplicate_MPI (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0xD73797: VecDuplicate (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x7A41E2: DarcyMH::solve_nonlinear() (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x7A4D36: DarcyMH::update_solution() (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x78F273: HC_ExplicitSequential::run_simulation() (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x76C825: Application::run() (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0xC23283: ApplicationBase::init(int, char**) (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
==45==    by 0x75EC8E: main (in /home/paulie/docker_flow123d/build-2.2.1/bin/flow123d)
```

According to valgrind, there are no other major leaks (increasing with time steps) in version 3.0.2.
Valgrind output:
[valgrind_out_v302.log](https://github.com/flow123d/flow123d/files/3492137/valgrind_out_v302.log)
[valgrind_out_v221.log](https://github.com/flow123d/flow123d/files/3492140/valgrind_out_v221.log)

**Comment by jbrezmorf** [comment]
OK for 3.1.0.
