### ISSUE TITLE
Efficient FieldFormula

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1138]
FieldFormula can be evaluated efficiently for the vectors of points (see [muparserx](https://beltoforion.de/article.php?a=muparserx&s=idFeatures#idFeatures) and [exprtk](https://github.com/ArashPartow/exprtk) and the parser [comparison](https://github.com/ArashPartow/math-parser-benchmark-project). So we need to evaluate lot of points together. That is possible once the points are from elements of the same region.

## Speed test
In order to achieve that we have to test actual support in the parser libraries:
- reference manual implementation of expression calculation s in C++
- muparser - bulkmode
- muparserX - vector operations
- exprtk - see vector_view feature

We need to achieve evaluation on the vectors (about 1000 elements) that are almost as fast as native implementation.

## Adoption
Need to replace current implementation that use FParser.

**Comment by jbrezmorf** [comment]
FieldFormula can be evaluated efficiently for the vectors of points (see [muparserx](https://beltoforion.de/article.php?a=muparserx&s=idFeatures#idFeatures) and [exprtk](https://github.com/ArashPartow/exprtk) and the parser [comparison](https://github.com/ArashPartow/math-parser-benchmark-project). So we need to evaluate lot of points together. That is possible once the points are from elements of the same region.

In order to achieve that we have to test actual support in the parser libraries:
- reference manual implementation of expression calculation s in C++
- muparser - bulkmode
- muparserX - vector operations
- exprtk
-

**Comment by jbrezmorf** [comment]
IPython notebook for times fitting:
[parser times.zip](https://github.com/flow123d/flow123d/files/3772376/parser.times.zip)

1. Write reading of profiler JSON output.
2. Convert data to the dataframe.

**Comment by jbrezmorf** [comment]
Good results from timing vector evaluation in ExprTK lib:

using 10000 repetitions we have folowing times:
expr: "0.5" , 250 points
C++ code: 1 ms
exprtk: 1 ms

expr: "x+y+z" , 250 points
C++ code: 1.4 ms
exprtk: 2.5 ms
expr: "x+y+z" , 1000 points
C++ code: 5.3 ms
exprtk: 9.0 ms

expr: "2*x + y*3 + x*(z-y) + 2*pi*zx+y+z" , 250 points
C++ code: 3 ms
exprtk: 9.2 ms
1000 points
C++ code: 11.8 ms
exprtk: 32.8 ms

**Comment by jbrezmorf** [comment]
TODO:
- comparison of power operation to C++ `pow` function, should be slow as well
- determine dependency of evaluation time for single vector element on the vector size (under 250)
- make extract from exprtk documentation: 
   operations: +, -, *, /, ^
   functions: abs, exp, log, sin, cos, asin, atan, ...
   special: ( ? : ), min, max, ...
- measure: ^, functions, special

**Comment by jbrezmorf** [comment]
TODO:
- Add (and test) FieldFormula support for cache update
- use ExprTK with defined X,  Y, Z views and Result view 
- make test that caching works
- speed test

**Comment by dflanderka** [comment]
We are gradually implementing own solution - BParser.
@jbrezmorf We can close this issue.
