### ISSUE TITLE
TransportDG disable_where for boundary fields

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#114]
TransportDG has Vector valued boundary fields bc_typ, bc_flux, bc_robin_sigma;

several issues:
-  We either have to generalize disable_where method or finally have individual equation for every substance.

- (the fields should not be vector valued for heat transport, how can we achieve that)

- finally currently we can not set disable_where for dirichlet condition field since it is added in model constructor.

- think over default values for transport_dg, they are little overused. This disable error checking
 However currently we at least report warning when the default value is used.

**Comment by jstebel** [comment]
Depends on #323

**Comment by jstebel** [comment]
Implemented.

bc_conc need not be disabled because it is present in all types of b.c.
Default values are left (similarly as in DarcyFlow).
