### ISSUE TITLE
Fix assembly of seepage BC in DarcyLMH (iteration process).

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1141]
The seepage BC is dependent on the fluxes. Using 2nd Schur complement, we have only the edge pressure during the iteration process. We need to somehow reconstruct the flux in this particular BC case (not needed elsewhere at the moment).

Idea:
- postpone assembly_BC to the end of assembly
- pass the vector of edge pressure (Schur solution) to the non-linear assembly routines, so we can assemble the local system using edge pressure in different states
- if it cannot be done simpler, try doing:
(1) compute local system using previous edge pressure and BC
(2) reconstruct the fluxes from the edge pressure
(3) assemble new local system with updated fluxes

prerequisity: #1140

**Comment by jbrezmorf** [comment]
Proposed solution:
1. apply Dirichlet BC to the Schur complement of the local system
2. assembly eliminated rows into a separate sparse matrix B
3. use this matrix to compute BC fluxes after the linear solve of the whole Schure complement system
4. (optional) we should introduce numbering of the boundaries it can be used for the B matrix as well as in the Balance

**Comment by Paulie14** [comment]
Done by 55576c91b6bf07296d477eaff5771809ac22178c
by saving assembled local systems on the elements coinciding with seepage BC
and using it to reconstruct the fluxes.

Point 4 not considered.
