### ISSUE TITLE
Field Formula for field parameters

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1143]
- Field::set_dependency(field_set) calls FieldFormula::set_dependency
- FieldFormula::set_time extract field names from expression and find the fields in the field set
- in evaluation the predecessor fields are evaluated first and passed into eval function

**Comment by jbrezmorf** [comment]
How to deal with FieldCommon in `set_time`:
- check individual types of Feild template:
   Field<FieldValue<1,1, double>> -> define the field variable for formula parser
   Field<FieldValue<spacedim, 1, double>> -> define the variables for field components `<name>_{x,y,z}`
   Field<FieldValue<spacedim, spacedim, double>> -> define the variables for field components `<name>_{xx,xy, ...}`

- not supportied for other fields

**Comment by dflanderka** [comment]
Modifications in FieldFormula::set_dependency:
- field_set_names should be a map from field names to cache objects.
- we need sort of low level acces to the cache without templates
- can be done if we change implementation of Array and FieldValueCache
- Try to eliminate FieldValueCache object and use Array directly.

**Comment by jbrezmorf** [comment]
@dflanderka Toto je asi hotové. Máme na použití fields ve FieldFormula nějaký unit test?

Je třeba dodělat:
- [ ] unit test jen té třídy FieldFormula.
- [ ] Testovací úlohu v 02_generic_input, just modify test 15 and rename it to 15_formula.
- [x] Upravit dokumentaci.

**Comment by dflanderka** [comment]
Solved in branch Df independent subsets (pull #1314)

**Comment by jbrezmorf** [comment]
@jbrezmorf Fix documentation, mention BParser, but keep FParser syntax for ver 3.1.0.

**Comment by jbrezmorf** [comment]
Documentation fixed in b4b1a25.
