### ISSUE TITLE
OutputTime unit test

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1148]
- output_test.cpp
Old unit test was replaced by the new concept, but test of GMSH output is missing.
- mesh_lib depends on io_lib due to mesh_readers, io_lib depends on fem_lib why?
- call OutputMesh::create_sub_mesh automatically if not created.
- try to simplify process of output of some element data to VTK of GMSH file.

**Comment by jbrezmorf** [comment]
Resolve just the first three points. The last one is possibly related to some minor code duplicities in the outputs, but not critical.

**Comment by dflanderka** [comment]
1. New unit test output_msh_test.cpp created
2. There is no dependency of mesh_lib on io_lib. But io_lib depends on fem_lib - class ProjectionHandler (in observe.cc) uses MappingP1.
3. Method create_sub_mesh is called from EquationOutput::make_output_mesh which is called from EquationOutput::output.

**Comment by jbrezmorf** [comment]
New dependency issue: #1341

**Comment by dflanderka** [comment]
Merge in a473ee4
