### ISSUE TITLE
Improve DOFHandler size getters.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1150]
- do not use "size" in names of getters for number of cells and dofs
- add getters for number of dofs
- distinguish between number of cells and number of dofs

Proposal:
```
n_own_dofs(), n_own_cells()
n_loc_dofs(), n_loc_cells()
n_ghost_dofs(), n_ghost_cells()
```

**Comment by jbrezmorf** [comment]
Do after DF_transport_asm merge.

**Comment by jbrezmorf** [comment]
Potential usage of n_dof getters:

Balance::allocate: `n_loc_dofs_seq_ = dh->get_local_to_global_map().size();`

**Comment by jbrezmorf** [comment]
Rename DofHandler: own_size, local_size, ghost_size to n_own_cells, n_local_cells, n_ghost_cells.

Do not introduce getters for number of dofs as the usage is very sparse and in fact should not be necessary in most cases.

**Comment by dflanderka** [comment]
Merge in d361259a1
