### ISSUE TITLE
Try to avoid virtual methods in the assembly classes.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1157]
Can we avoid the functions of different assembly implementations to be virtual? This is in contrast with storing assembly objects in an array indexed by dimension. But we can use the Mixed<> construction instead, that way we can mostly avoid virtual calls during assembly.

**Comment by jbrezmorf** [comment]
Virtual call have some cost, but for functions with substantial payload the call time is amortized. 
Resolved with the new assembly scheme.
