### ISSUE TITLE
Constructing field by FieldFE without keeping shared_ptr.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1163]
When we construct output fieldFE, we need to have
```
Field<3, FieldValue<3>::Scalar > saturation;
std::shared_ptr<FieldFE<3, FieldValue<3>::Scalar>> saturation_ptr;
```
and then do:
```
data_->saturation_ptr = std::make_shared< FieldFE<3, FieldValue<3>::Scalar> >();
data_->saturation_ptr->set_fe_data(data_->dh_p_, 0);
data_->saturation.set_mesh(*mesh_);
data_->saturation.set_field(mesh_->region_db().get_region_set("ALL"), data_->saturation_ptr);
```
This must be simplified, so we do not keep the shared_ptr globally.
This is also connected with this comment in ```darcy_mh.hh:364```:
```
// Temporary objects holding pointers to appropriate FieldFE
// TODO remove after final fix of equations
```
which is not 'very clear'...

**Comment by jbrezmorf** [comment]
1. the shared pointer can be local
2. FieldFE can be created efficiently using `create_field_fe` functions.
The code can look like:
```
data_->saturation.set_mesh(*mesh_); // usually called once for the whole FieldSet
data_->saturation.set_field(mesh_->region_db().get_region_set("ALL"),
                                            create_field_fe(data_->dh_p_, 0));
```
Is this acceptable?

**Comment by Paulie14** [comment]
- at the moment, it is already used in many places
- the rest, with some other clean up, done by d845b838db5b925e7ab42d950a04ee9972fa0922
