### ISSUE TITLE
Long numbers in the input file

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#117]
JSON reader truncates long numbers without any notification.

**Comment by jbrezmorf** [comment]
Partly fixed. Correct conversion from Int64 to Double. Need to add support how to read Int64 through the interface. Use Int64 for integer by default. 
Programer friendly way to specify range. Exceptions when converting to regular int ( Have to elaborate dispachers in accessors.]

**Comment by dflanderka** [comment]
Done in 0df49b7.

**Comment by jbrezmorf** [comment]
merged in 45f232a
