### ISSUE TITLE
fterm.bat problém při spuštění z Pythonu

### ISSUE THREAD

**Issue by petrralek** [flow123d/flow123d#1189]
fterm.bat:

SET "cdir=\%CD:~0,1%\%CD:~3,256%"
docker run --rm -v "%~d0\:/%CD:~0,1%/" -v "C:\:/c/" -w "%cdir:\=/%" flow123d/3.0.1 %*
pause

spuštění z cmd:

C:\Users\peta>c:/Users/peta/AppData/Local/Flow123d/v3.0.1/bin/fterm.bat --output_dir output_01_hm 01_hm.yaml

C:\Users\peta>SET "cdir=\C\Users\peta"

C:\Users\peta>docker run --rm -v "c:\:/C/" -v "C:\:/c/" -w "/C/Users/peta" flow123d/3.0.1 --output_dir output_01_hm 01_hm.yaml
error: exec: "--output_dir": executable file not found in $PATH

C:\Users\peta>pause
Press any key to continue . . .

C:\Users\peta>

**Comment by jbrezmorf** [comment]
@petrralek: Zkus veerzi 3.0.3dev, koukal jsem, ze tam jsou ty bataky predelane a melo by to fungovat lepe. Nejsem si jist, zda tam bude fungovat --no-term, zkus to kdyztak bez nej. Zkus fterm nejdriv z prikazove radky. Kdyby byl problem, tak to sem zase nakopiruj.

**Comment by petrralek** [comment]
Tak aktuální stav:
E:\skola\endorse\WGC2020-THM-MC\venv\Scripts\python.exe E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py output
total mean size:  400.0
True [77]
True [105]
True [28]
True [2]
True [165]
Running:  c:/Users/peta/AppData/Local/Flow123d/v3.0.3/bin/flow123d.bat --output_dir output_03_th 03_th.yaml
Exit status:  1
Traceback (most recent call last):
  File "E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py", line 613, in <module>
    sample(config_dict)
  File "E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py", line 591, in sample
    th_succeed = call_flow(config_dict, 'th_params_ref', result_files=["energy_balance.yaml"])
  File "E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py", line 387, in call_flow
    conv_check = check_conv_reasons(os.path.join(output_dir, "flow123.0.log"))
  File "E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py", line 348, in check_conv_reasons
    with open(log_fname, "r") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'output_03_th\\flow123.0.log'

Process finished with exit code 1

**Comment by petrralek** [comment]
Při spuštění z příkazové řádky
(c:/Users/peta/AppData/Local/Flow123d/v3.0.3/bin/flow123d.bat --output_dir output_03_th 03_th.yaml) to něco dělá, jen úloha nezkonverguje, ale aspoň to vyrobí adresáře, log apod. Při spuštění z Pythonu to pořád vypadá, že se vůbec Flow nezavolá (a pak Python nenačte log, který neexistuje).

**Comment by jbrezmorf** [comment]
OK. problem tedy uz asi nebude na strane flow. 
V `call_flow` se to vola skrze `subprocess.run`. Melo by to presmerovat stdout a stderror do souboru, ty bys nekde mel mit a v nich bych cekal nejakou chybovou zpravu/ Bylo by dobre, kdyby sis tam nechal rovnou vypsat `completed.returncode`. Take muzes zkusit volat `subprocess.run` s parameterm shell=True.

**Comment by petrralek** [comment]
03_th_stderr:
the input device is not a TTY.  If you are using mintty, try prefixing the command with 'winpty'

03_th_stdout je prázdný
completed.returncode je 1

Takze si musim nainstalovat to winpty nebo to pujde jeste jinak, kdyz spusteno z cmd to funguje?

**Comment by jbrezmorf** [comment]
To ne spis bude probelm se spoustenim dockeru mimo terminal. To by mel resit ten --no-term ale cert vi jak to funguje na windows. Musim se na to u tebe kouknout.

**Comment by jbrezmorf** [comment]
Confirmend problem with flow123d.bat and fterm.bat. We need kind of --no-term option to turn off the '-ti' docker argument, when the BAT is called from a (Python) script.

**Comment by jbrezmorf** [comment]
TODO:
- Modify fterm.bat to be somehow consistent with bin/fterm. 
- Use bin/fterm in Linux installation?

**Comment by jbrezmorf** [comment]
See: [windows package configurationinstaller](https://github.com/flow123d/flow123d-package/tree/master/project/src/windows)
