### ISSUE TITLE
large mesh on charon -no computation -  1,9 mil elements

### ISSUE THREAD

**Issue by ales-balvin-tul** [flow123d/flow123d#1191]
**Describe the bug**
computation with large mesh 1,9 mil elements

the computation finished after reading elements:
```
"00:01:29.035      - Reading nodes...
00:01:37.987      ... 973450 nodes read. 
00:01:37.988      - Reading elements...
00:01:59.543      ... 1943398 bulk elements, 1400 boundary elements."

than only this message:
===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   EXIT CODE: 9
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
```

**To Reproduce**
- software version / branch / commit hash - This is Flow123d, version 3.0.3 commit: eedc5859a
- steps to reproduce the behavior
- link to source files, input files are here: /auto/liberec3-tul/home/alesbalvin/TACR_PUKLINA/VYPOCTY_PUKLINA/2020-02-21_VYPOCTY_Puklina2/B01_opramesh_ERROR

**Comment by milanhokr** [comment]
Mě to dělá taky (je to tatáž úloha od Aleše, ale dělal jsem nějaké úpravy vstupů), ale mám pozorování i jiných případů:
\\\Secure FTP\metacentrumLbcNove\storage\liberec3-tul\home\milanhokr\puklina\fm2\test-par\PUKLINA-MS2_tran_direct01_1mm.o1019305
nejnovější spuštění, totéž chování co Aleš
výstup zde 
\\\Secure FTP\metacentrumLbcNove\storage\liberec3-tul\home\milanhokr\puklina\fm2\test-par\MS2_tran_direct01_1mm\

Předchozí spuštění identického vstupu - pracovalo asi 5 min jen na načítání vstupů, cca do stejného místa v logu, ale pak zůstalo viset a až po dvou hodinách bylo ukončeno na překročení času
\\\Secure FTP\metacentrumLbcNove\storage\liberec3-tul\home\milanhokr\puklina\fm2\test-par\PUKLINA-MS2_tran_direct01_1mm.o1013549
\\\Secure FTP\metacentrumLbcNove\storage\liberec3-tul\home\milanhokr\puklina\fm2\test-par\job_1013549.meta-pbs.metacentrum.cz\

A druhé pozorování je, že tatáž úloha zadaná na sériový výpočet proběhne bez uvedeného problému. (jsou jiné, numerické, které napíšu zvlášť)

**Comment by jbrezmorf** [comment]
EXIT CODE: 9

... means that the process was killed by the system. Here it is probably because of 
overcoming the memory limit that you specified in your PBS script.

**Comment by milanhokr** [comment]
S Honzou jsme mluvili po telefonu a upozornil jsem ze se chova jinak nez kdyz ukonceni udela PBS kvuli prekroceni prostredku.
Protoze pamet se k limitu blizila tesne (86G z 88G), tak jsem spustil jeste jednou s alokaci 93GB coz je uvadene maximum hw (ok?).
Vyseldne chovani je analog pripadu 1 z meho komentare: tj. vypis v logu "zatuhne" behemnacitani msh na nejakych 3 minutach a dal nepribyva. Na PBS vypisu ovsem dal bez a spotrebovava cpu. Pamet vzal stejnych 86G.
Vypis \storage\liberec3-tul\home\milanhokr\puklina\fm2\test-par\vystup 1024519\

**Comment by jbrezmorf** [comment]
@Paulie14 Koukni na tu Milanovu ulohu. Ze to projde seriove a neprojde paralelne pro tak velky limit pameti je divne. 2M elementu by melo projit seriove i paralelne. Pokus se to reprodukovat.

**Comment by jbrezmorf** [comment]
A direct solver was used:
```
    nonlinear_solver:
      linear_solver: !Petsc
        options: -ksp_type preonly -pc_type lu
        r_tol: 1.0e-15
        a_tol: 1.0e-15 
```
The LU was long time supported only in serial so I wonder that it works somehow in parallel now. 
However in this particular case the expected memory consumption is in order of tens of GB (1000 x 3e6 x 8 for an efficient frontal solver) in a serial run. For the parallel case, the matrix fill will be probably larger and can easily be beyond the HW limit. Moreover the process was probably killed directly by the kernel, so the PBS scheduler did not inform the user about excessing the reserved resources.

would be on the edge of the in PThe behavior of LU running in parallel is not

**Comment by jbrezmorf** [comment]
Closing, as it seems to be problem size issue in combination with the inappropriate solver.
