### ISSUE TITLE
Vypne vystup observe_fields pri vypnuti fields(msh)

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1194]
**Describe the bug**

V řídícím souboru se samostatně nastavuje výstup do MSH pole a do pozorovacích bodů (observe points)   
 
-----
    output:
      fields: [ ]
      observe_fields: [ piezo_head_p0, pressure_p0, velocity_p0 ] 
-----
Ve dřívějších verzích se výše uvedené nastavení chovalo korektně tak, že negeneroval MSH výstup (úspora disku) a přitom generoval observe.yaml v zadaných krocích. V aktuální verzi jakmile má první řádek prázdné pole, nezapisuje ani do observe - resp. do observe.yaml zapíše hlavičku a souřadnice bodů ale již nezapisuje hodnoty veličin.
Nemyslím si, že to bylo záměrem, každopádně by to bylo zcela nepraktické.

**To Reproduce**
- software version / branch / commit hash
  - This is Flow123d, version 3.0.3 commit: eedc5859a 
- steps to reproduce the behavior
- link to source files, input files
Zde je podoba s nežádoucím chováním (vypnutí MSH vypne i OBS)
\storage\liberec3-tul\home\milanhokr\test\y02-zadnyvystup\
Zde je podoba, kdy stačí zapnout jedno pole MSH a pak už se OBS zapisuje taky.
\storage\liberec3-tul\home\milanhokr\test\y01-vystupMSHiOBS\

**Comment by Paulie14** [comment]
Fixed by cb62583e8f51e4744aa39e8b04d692dc49d9f62a.
Tested by integration test 03-14.
