### ISSUE TITLE
geomop na linuxu

### ISSUE THREAD

**Issue by corund7266** [flow123d/flow123d#1195]
instaloval jsem geomop na opensuse pomocí příkazu dpkg, hlásilo následující to chyby při nistalaci (ale zmíněné package nainstalovány mám):
 
shadow:/home/repository/geomop # dpkg -i geomop_1.1.0-1_all.deb 
(Reading database ... 921 files and directories currently installed.)
Preparing to unpack geomop_1.1.0-1_all.deb ...
Unpacking geomop (1.1.0-1) over (1.1.0-1) ...
dpkg: dependency problems prevent configuration of geomop:
 geomop depends on python3; however:
  Package python3 is not installed.
 geomop depends on python3-pip; however:
  Package python3-pip is not installed.
 geomop depends on xclip; however:
  Package xclip is not installed.

dpkg: error processing package geomop (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 geomop

při pokusu o spuštění to hlásí:
(base) jiri.landa@shadow:~> geomop-me
/usr/bin/geomop-me: řádek 5: /usr/local/bin/virtualenvwrapper.sh: Adresář nebo soubor neexistuje
/usr/bin/geomop-me: řádek 7: workon: příkaz nenalezen

**Comment by jbrezmorf** [comment]
dpkg zarizuje jen instalaci samotneho balicku, neresi zavislosti
Na ubuntu a debianu instalace zarizuje 'apt', na OpenSUSE, je neco jako 'yum', ale balicky pro yom nemame. 
Mozna reseni:
1. rucne instalovat pozadovane balicky, jak to pise v chybe. To muze byt pomerne trnita cesta.
Ale vypada to, ze tech balicku neni moc, tak by to treba slo. Potrebujes instalovat: python3, python3-pip a xclip. Ty balicky se na OpenSuse mohou pripadne jmenovat trochu jinak.
2. Zkusit 'alien': viz. [blog](https://forums.opensuse.org/showthread.php/434672-installing-deb-packages-in-opensuse)

Zaver, neni to chyba geomopu.

**Comment by jbrezmorf** [comment]
Jeste teprve pozoruju, ze se toto issue tyka geomopu a ne flow123d.
Zatim tedy zaviram.
