### ISSUE TITLE
bgem-PE_greet_mesh

### ISSUE THREAD

**Issue by petrralek** [flow123d/flow123d#1196]
Ahoj Pavle,
stahnul jsem si tvou rozdelanou vetev bgem-PE_greet_mesh, vrazil si to k sobe do projektu, zkusil spustit a hazi to tuhle hlasku:

E:\skola\endorse\WGC2020-THM-MC\venv\Scripts\python.exe E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py output
Traceback (most recent call last):
  File "E:/skola/endorse/WGC2020-THM-MC/mlmc_random_frac/process.py", line 623, in <module>
    create_geom.generate_mesh(geometry_dict)
  File "E:\skola\endorse\WGC2020-THM-MC\mlmc_random_frac\create_geom.py", line 184, in generate_mesh
    gen = gmsh.GeometryOCC("greet_mesh_tunnel", verbose=True)
  File "E:\skola\endorse\WGC2020-THM-MC\mlmc_random_frac\../bgem-PE_greet_mesh/src\bgem\gmsh\gmsh.py", line 198, in __init__
    self.model = gmsh.model.occ
AttributeError: module 'gmsh' has no attribute 'model'
Exception ignored in: <function GeometryOCC.__del__ at 0x00000292D479C948>
Traceback (most recent call last):
  File "E:\skola\endorse\WGC2020-THM-MC\mlmc_random_frac\../bgem-PE_greet_mesh/src\bgem\gmsh\gmsh.py", line 545, in __del__
    gmsh.finalize()
AttributeError: module 'gmsh' has no attribute 'finalize'
generate mesh

Process finished with exit code 1

gmsh.py bych mel mit ten spravnej z adresare bgem, tak nevim, v cem je chyba; asi to bude nejaka ma blbost
Dik, P.

**Comment by jbrezmorf** [comment]
Hej hola Petre, hod to prosim do repozitare bgem. S Flow to nema nic spolecneho.

**Comment by Paulie14** [comment]
neni mi uplne jasne, co jsi zkombinoval dohromady..
Vidim tam WGC2020-THM-MC, pracujes tedy s timto repozitarem?
K tomu sis stahl bgem-PE_greet_mesh ?
Mas svou praci v nejakem repozitari, ze bych se na to mrknul?

Vzhledem k tomu, ze to pada v gmsh.py  a nevidi to "model", tak se mi zda, ze jak to nahore importuje gmsh, tak to importuje neco jinyho...

**Comment by petrralek** [comment]
> Hej hola Petre, hod to prosim do repozitare bgem. S Flow to nema nic spolecneho.

Nj, ja to nemohl najit.:o)pardon.

**Comment by jbrezmorf** [comment]
https://github.com/GeoMop/bgem

Prosim cvicne tam ten report pretahni a ja se k tomu pak vyjadrim tam. diky.
