### ISSUE TITLE
Weird interface in reactions.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1198]
- CFL constraints seem to take no effect in reactions, target time is passed, but not set, fixed bool is returned
- `compute_reaction` takes argument concentrations, but it does not use it - concentrations are member in the base class ReactionTerm
- problem in all - soprtion, dual porosity, foreactions...

**Comment by jbrezmorf** [comment]
That could be an issue. Try to look if this case is covered by the tests. We should have some simple test to demonstrate the problem.

**Comment by jbrezmorf** [comment]
- [ ] Remove `evaluate_time_constraint` from mechanics.
- [ ] `evaluate_time_constraint` seems to return false always. Even for reactions based on the LinearODESolver. It is possible, that we modified the ODE solver to not have any CFL constrains, then we can return true directly from ReastionTerm removing many virtual functions.

However it seems, that this is not a bug, just a dead code.

**Comment by Paulie14** [comment]
Dead code removed by 3679893c7afb5170680b9e2e30a770462a4ee705 in branch `PE_transport`.
