### ISSUE TITLE
Reactions - create tests for different combinations of reaction models

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#121]
Suggest reference tests for different combinations of reaction models. 
Example input files have been created in Test_23 and are described in 'description.txt'.

These model combinations are possible:

- DualPorosity  -> Linear reaction in mobile zone
                        -> Linear reaction in immobile zone
                  
- DualPorosity  -> Pade approximation reaction in mobile zone
                        -> Pade approximation reaction in immobile zone
                  
- DualPorosity  -> sorption in mobile zone
                         -> sorption in immobile zone
                  
- DualPorosity  -> sorption in mobile zone    -> Linear reaction
                        -> sorption in immobile zone  -> Linear reaction

- DualPorosity  -> sorption in mobile zone    -> Pade approximation reaction
                        -> sorption in immobile zone  -> Pade approximation reaction

**Comment by jbrezmorf** [comment]
partly duplicate of #124
