### ISSUE TITLE
Test 22/04

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1210]
All calculations are performed during about 40s, but the the test hangs during final timestep after matrix rescaling. Seems to be an error in timestepping logic.

The problem was tracked down to the merge: c1fdb1a608

**Comment by jbrezmorf** [comment]
I did profilling with 'oprofiler' it reports TimeGovernor::step as one of the most consuming functions, but I failed to retrieve the callgraph. Seems that manual debugging is way to go.

**Comment by jbrezmorf** [comment]
Problem observed for modified input for shorter calculation.
[04_unsteady_flow.zip](https://github.com/flow123d/flow123d/files/4529174/04_unsteady_flow.zip)

**Comment by Paulie14** [comment]
There were two problems:
- length of the test - fixed: step increased, length adjusted
- in posted JB test case, the flow was running longer than transport and got stuck in time loop - fixed bug

all fixed by b2051dd42284467fb9c48d2100fd15e2e61a7a3d
