### ISSUE TITLE
Region from elements - overwriting mesh regions.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1218]
Problem by Jiri Landa.
Path:
`auto/liberec3-tul/home/pavel_exner/2020_05_JL_elereg/`

I found that the core problem is that the user is not aware of that by creating region from element list,
he can overwrite the region which is set in the msh to the particular elements.
The input file
`l2_cer_s4_det_z3_hre_p0_zkl_c1_Ixxxx_vyp00001.yaml`
`l2_cer_s4_det_z4_h2d_p0_zkl_c1_Ixxxx_vyp00001.yaml`
differ "only" at the point, that the later includes some 2d elements in the region `zdroj_2d`.

However, the elements in the list has already specified region id in the mesh. This way it gets overwritten.

Later it caused problem due to prescribing wrong cross section on the 2d elements, because these were not in the region set `tektonika` any more, but in the region `zdroj_2d`.

TODO:
We should probably report a warning, if the element already has region id prescribed from the mesh.
It can be still used intentionally, but it can also create unsuspected behaviour..

**Comment by jbrezmorf** [comment]
TODO:
- implement a warning when overwriting an existing region

**Comment by jbrezmorf** [comment]
Proposed solution: Overalys #1438
