### ISSUE TITLE
Charon build, warning error

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1222]
Build on charon use GCC 6.4 which have new warnning 'missleading-indentation' this 
cause error build.
See: http://ciflow.nti.tul.cz:8080/job/flow123d-charon-build/

We should turn on -Werror only for test builds and leave it turned off for statndard builds.
In particular we can add -Wno-missleading-indentation at least for foptimizer.c

**Comment by Paulie14** [comment]
Fixed by 71fc67f15c4e509efc6d696cc777d0744d6b2f6e.

However, charon build still fails on some template errors..

**Comment by janhybs** [comment]
The [charon build](http://ciflow.nti.tul.cz:8080/job/flow123d-charon-build/269/consoleFull) fails on:

https://github.com/flow123d/flow123d/blob/remove_mhdh/src/transport/assembly_dg.hh#L107-L109

It appears the compiler does not know `.template` constructs
https://github.com/flow123d/flow123d/commit/0899a1fc5869453e329413f6ee6cbd4e36d0202b

**Comment by Paulie14** [comment]
Are you sure, you are looking at the correct build?
I see it in green, in particular the merge to master in build http://ciflow.nti.tul.cz:8080/job/flow123d-charon-build/274/

**Comment by Paulie14** [comment]
the build you are referencing is before the fix with `.template`

**Comment by janhybs** [comment]
Oh, i overlooked the green remove_mhdh build. Could you link me specific build which is not passing on charon?
