### ISSUE TITLE
Support for empty or nonexisting regions

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1228]
When using random fracture networks some regions (e.g. X) resulting from the intersections may be empty. BGEM in combination with GMSH produces a mesh lacking X.
Then Flow123d fails as the input file reference X and it is not among the physical groups in the mesh file.

TODO:
- allow introduction of these regions probably through From_Label 
- using some new option the user can confirm that the region can be empty effectively overriding the input checks

**Comment by Paulie14** [comment]
See pull request #1231 for suggested solution.

If region in region set `From_Label` is not found and user set `allow_empty`, it creates new Region with given name. Later in the region check, I kept the warning on 'no elements in the region'.

**Comment by Paulie14** [comment]
Done in 9499e579b155c913645bc59f45d2d6a03a2decf0.
Backported to 3.0.4.
