### ISSUE TITLE
boundary FieldFE

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1234]
**Problem 1**

We can not have boundary FieldFE since we need boundary DofHandler and boundary Mesh.
This is sort of optimization as we should be able to evaluate the bulk fields on the boundary as well.
Current concept of FieldBC only means that this kind of optimization can be applied.

**Problem 2**
Support both bulk and boundary FieldFE for boundary fields. Or have some adaptor of the bulk fields.

**Problem 3**
Special fields for boundary elements: X, Y, Z, D, normal

**Comment by jbrezmorf** [comment]
@jstebel Make the `MeshBase` class with members and methods used by DofHandler, 
mark separately those used by the `duplicate_nodes`.

**Comment by jbrezmorf** [comment]
TODO: 
- [ ] Finish common mesh interface, PR #1246. 
- [ ] Make BC Mesh.
- [ ] Make an issue for FieldFE on the BC Mesh (have to test DofHandler etc.)

**Comment by jbrezmorf** [comment]
TODO @jbrezmorf :
How to work with boundary elements in the patch for two source meshes (bulk and boundary)?
Are explicit boundary elements necessary?

**Comment by jstebel** [comment]
After merging master to JS_mesh_interface, the code fails on all tests excluding flow problems. After some attempts I am still not able to resolve the problem. It fails on segmentation fault, probably due to access outside of some array. Snippet of log message:

          ##                   region_idx 3: A_init_conc, 
          ##                   region_idx 4: A_init_conc, 
          ##                   region_idx 5: A_init_conc, 
          ## 00:00:04.263      DEBUG.(/src/coupling/generic_assembly.hh:429)Order of evaluated fields (InitConditionAssemblyDG):
          ##                   region_idx 0: A_init_conc, 
          ##                   region_idx 1: A_init_conc, 
          ##                   region_idx 2: A_init_conc, 
          ##                   region_idx 3: A_init_conc, 
          ##                   region_idx 4: A_init_conc, 
          ##                   region_idx 5: A_init_conc, 
          ## 00:00:04.831      DEBUG.(/src/coupling/generic_assembly.hh:429)Order of evaluated fields (StiffnessAssemblyDG):
          ##                   region_idx 0: cross_section, A_bc_type, A_bc_robin_sigma, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ##                   region_idx 1: porosity, water_content, cross_section, flow_flux, A_sources_sigma, A_bc_type, A_bc_robin_sigma, A_disp_l, A_disp_t, A_diff_m, v_norm, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ##                   region_idx 2: cross_section, A_bc_type, A_bc_robin_sigma, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ##                   region_idx 3: cross_section, A_bc_type, A_bc_robin_sigma, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ##                   region_idx 4: cross_section, A_bc_type, A_bc_robin_sigma, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ##                   region_idx 5: cross_section, A_bc_type, A_bc_robin_sigma, sources_sigma_out, advection_coef, diffusion_coef, A_fracture_sigma, A_dg_penalty, 
          ## terminate called after throwing an instance of 'boost::exception_detail::clone_impl<ExcSignal>'
          ##   what():  --------------------------------------------------------
          ## Program Error: [ Signal 11 (Segmentation fault) received! ]
          ## 
          ## ** Diagnosting info **
          ## /home/stebel/dev/git/flow123d/src/system/application_base.cc(59): Throw in function PetscErrorCode petsc_signal_handler(int, void*)
          ## Dynamic exception type: boost::exception_detail::clone_impl<ExcSignal>
          ## [EI_Signal_TAG*] = 11
          ## [EI_SignalName_TAG*] = Segmentation fault
          ## 
          ## ** Stacktrace **
          ##   0  petsc_signal_handler(int, void*)
          ##   1  ) [0x2a1535d]
          ##   2  
          ##   3  arma::Mat<double>::fixed<3u, 3u> Armor::Array<double>::mat<3u, 3u>(unsigned int) const
          ##   4  FieldValue_<3, 3, double>::get_from_array(Armor::Array<double> const&, unsigned int)
          ##   5  FieldValue_<3, 3, double>::return_type ElementCacheMap::get_value<FieldValue_<3, 3, double> >(Armor::Array<FieldValue_<3, 3, double>::element_type> const&, unsigned int, unsigned int) const
          ##   6  Field<3, FieldValue_<3, 3, double> >::operator()(BulkPoint&)
          ##   7  StiffnessAssemblyDG<2u, ConcentrationTransportModel>::cell_integral(DHCellAccessor, unsigned int)
          ##   8  void GenericAssembly<TransportDG<ConcentrationTransportModel>::StiffnessAssemblyDim>::assemble_cell_integrals<2u>()
          ##   9  GenericAssembly<TransportDG<ConcentrationTransportModel>::StiffnessAssemblyDim>::assemble_integrals()
          ##  10  GenericAssembly<TransportDG<ConcentrationTransportModel>::StiffnessAssemblyDim>::assemble(std::shared_ptr<DOFHandlerMultiDim>)
          ##  11  TransportDG<ConcentrationTransportModel>::preallocate()
          ##  12  TransportDG<ConcentrationTransportModel>::zero_time_step()
          ##  13  TransportOperatorSplitting::zero_time_step()
          ##  14  HC_ExplicitSequential::advection_process_step(HC_ExplicitSequential::AdvectionData&)
          ##  15  HC_ExplicitSequential::run_simulation()
          ##  16  Application::run()
          ##  17  main

**Comment by jbrezmorf** [comment]
- fix add_boundary_integral, it calls point_bdr which use position_in_cache before element_to_map_ is created.
- FieldFE::cache_update - detect boundary regions and bulk regions, evaluate the field only on regions matching the type of the field.
- add_boundary_integral can be same, but we have problem with element idx to patch idx map: element_to_map_
- Modify existing assembly to call Field<>::operator() with the boundary point, do not extracting the bulk point on the boundary element explicitly. For allowing evaluation of the bulk fields on the boundary, modify Field<>::operator() for the BoundaryPoint. In the case of bulk field, extract the corresponding SidePoint firm the bulk element, only in the case of boundary field use BoudaryPoint::point_bdr to get value in BulkPoint on the boundary mesh element.

**Comment by jbrezmorf** [comment]
@Paulie14  found problem in check_compatible_mesh, which doesn't work for discontinuous input mesh (i.e. produced by corner data outputs). This will be fidex in separate issue, but there is a new code dealing with BCMesh introduction which is certainly wrong as the method returns map from elements of computational mesh to the elements of the input mesh. This map must be separated for the bulk and boundary mesh. Not clear if the input mesh is also split into bulk and boundary part. we should somehow prevent it in the GMSH reader.

**Comment by jbrezmorf** [comment]
Further development should consider implementation of the boundary mesh as a general submesh as proposed in #1360.

**Comment by Paulie14** [comment]
Considering current state - split mesh for bulk and boundary mesh - the `check_compatible_mesh` is fixed by PR #1361.
- fixed case with discontinuous mesh
- fixed split map for bulk and boundary mesh

**Comment by dflanderka** [comment]
Segfault in JS_mesh_interface fixed in 796afc5.

**Comment by jbrezmorf** [comment]
Can not implement FieldFE working in the case of BoundaryField with bulk of handler (i.e. a bulk field evaluated as a boundary field). We should introduce a kind of interpolation wrapper to this end. Generic wrapper is problematic, since this introduce a filed on some region dependent on the other field on other region. This kind of dependency i s currently not supported by the FieldSet, can be possibly introduced when we turn current Field<> into sort of FieldRegion<> derived from FieldAlgoBase. Then we should introduce dependency of particular FiledAlgoBase objects.

**Comment by jbrezmorf** [comment]
Fixed tests for parallel boundaryFieldFE tests, see #1422

**Comment by jbrezmorf** [comment]
Problem 1 - resolved.
Problem 2 - postponed, see note from Aug 16
Problem 3 - For normal see issue #1417
Resolved.
