### ISSUE TITLE
User's bug report - chyba parametrů při volání PETSC

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1237]
**Describe the bug**
Řešič transportu při volání PETSC vyvolá hlášku "nnz cannot be greater than row length ..." která se zobrazí je na obrazovce ale ne do logu (tam jsou jen programátorské klikyháky).
Samotná úloha proudění se spočte.
Původně byla úloha na větší 1D síti, kde chodila, ale na analogické síti jen s 2 nebo 3 elementy se děje toto.

**To Reproduce**
- verze 2.2.1 pro PC  commit: b04af7f
- data úlohy zde \\astra.cxi.tul.cz\Public\milan.hokr\predat\F123\problem20200610\  (tran3elm.yaml je verze s chybou, tran-puv.yaml je analogická funkční), včetně snímku s hláškou
Ve verzi 3.0.3 se pro tuto úlohu chyba neobjevuje, ale po dohodě kvůli potenciální skrytosti přesto vkládám sem.

**Comment by jbrezmorf** [comment]
- [ ] Ověřit kde k chybě dochází. Divné je, že výpočet doběhne.
- [ ] Zkusit reprodukovat v 3.1.0.

**Comment by jbrezmorf** [comment]
Bug happens in our preallocation preallocate_mattrix in linsys_PETSC.c when calling MatCreateAIJ. 
The computation did not finish rather ended with SEG FAULT.

Can not reproduce in 3.1.0.
