### ISSUE TITLE
User's bug report - text manuálu k sorpci

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1241]
V manuálu je ještě jeden historický relikt, na str. 21 druhý odstavec (sekce 1.5.5) ze starší verze F123 s jinou podobou koeficientu K_D (je revidováno "opačným" textem v 2.5.2  - str 38 nahoře). 

Pak mi chybí komentář (nebo jsem nenašel) k řízení časových kroků pro štěpení operátoru (OS) a pro samotný transport. Možná, že není co komentovat (dle jednoho pokusu s v3.0.3 jde vždy o tentýž časový krok), ale verze 2.2.1 se chovala jinak (pro mě špatně), že časový krok výpočtu se použil pro DG, zatímco kroky sorpce v Reaction byly dle časového kroku pro zápis, takže se stávalo, že zůstávala pevná conc_solid a měnil se conc a až s krokem štěpení se srovnalo. Možná to byla chyba, která byla novou verzí odstraněna. Ale nejsem si pak jistý, zda nejde také o nastavení, které řídí věci jinak a je někde skryté.

Další je záležitost při propojení OS s DG diskrétními hodnotami - dělá nějaký přepočet z DG hodnot do elementových? Z textu je patrné, že OS bylo určeno primárně pro FV, píše o bilanci v elementech. Takže asi jde o nějakou interpolaci, ale otázka je zda jedním směrem nebo i zpět a jak se chyba v časových krocích kumuluje.

**Comment by Paulie14** [comment]
ad 1: opravim

ad 2: nevim, jestli dobre rozumim, ale je potreba odlisit 2 klice:
`solute_equation(Coupling_OperatorSplitting) -> time` nastavuje casovou osu (a tedy krok) OS (nazval bych krokem metody) a tedy omezuje pripadne i krok v DG
`transport (v OS muze byt FV nebo DG) ->output->times` rika, v techto casech proved zapis vystupnich dat (metoda pak musi nutne prispusobit casovou osu, aby se do techto casu trefila)

ad 3: podivam se, nejsem si jisty, ale urcite ocekam interpolaci DG -> P0

**Comment by Paulie14** [comment]
ad 3:
DG - > P0: spočítá průměrnou hodnotu z DoFů (pro DG P1 prvky tedy průměr uzlových hodnot koncentrace), zároveň ořezává případné záporné hodnoty na 0

P0 -> DG: k hodnotám DoFů přičte rozdíl předchozích průměrných hodnot (bez ořezu) a hodnoty z reakčního členu

**Comment by jbrezmorf** [comment]
Review related doc and close.

**Comment by jbrezmorf** [comment]
Seems not even touched.
ad 1. fixed, updated commented input file
ad 2. add comment to Operator splitting
ad 3. postponed to 4.0.0 #1250
