### ISSUE TITLE
Verze 2.1.2 přestala chodit kvůli TLS certifikátu

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1249]
![F123-docker-regenerovani](https://user-images.githubusercontent.com/56994529/85225578-afabd700-b3d2-11ea-9e1f-72738aca788a.png)
![F123-docker-chyba](https://user-images.githubusercontent.com/56994529/85225579-b0dd0400-b3d2-11ea-9577-b9e14ccceb79.png)

**Describe the bug**
Vypadá to že i Flow123d (resp. ve skutečnosti Docker) v sobě obsahuje "kurvítko", tj. vypršením nějakého datumu přestane fungovat :-).
Při spuštění vyskočí dvě hlášky - první s informací o certifikátu je zakrytá a po pár sekundách zmizí, druhá pak píše že se Docker nepřipojil na jakousi adresu s podle mě nekorektním formátem s mnoha lomítky. Obě dohromady na prvním snímku.
Pokud zkusím to regenerování (druhý snímek) tak to sice proběhne, ale chyby při spuštění zůstanou stejné. Nepochopil jsem zda to mám spustit v nějakém adresáři nebo s nějakým [name] ale kdyby to bylo blbě, tak by si asi stěžoval. 

**To Reproduce**
Viz snímky. Laptop s Win10, F123 2.1.2, dle starých úloh "commit: 6a13a75" ale na 100% to nevím protože se log nevytvoří.

**Comment by jbrezmorf** [comment]
Dost možná to souvisí s ukončením podpory SHA1 hashe v SSH, viz [článek](https://www.zdnet.com/article/openssh-to-deprecate-sha-1-logins-due-to-security-risk/).

Asi bude potřeba vyrobit pro 2.x řadu nové Docker image s novějšími verzemi základních knihoven.

**Comment by jbrezmorf** [comment]
Tak jinak, po konzultaci s Honzou Hybšem to je jen přirozená omezená platnost certifikátů. 

Zkus spustit (jak to ostatně radí ve zprávě):

    docker-machine regenerate-certs --client-certs dev

viz:    [popis](https://docs.docker.com/machine/reference/regenerate-certs/)

**Comment by jbrezmorf** [comment]
Tak jeste oprava, pouze:

    docker-machine regenerate-certs --client-certs

nebo
   
    docker-machine regenerate-certs --client-certs default

**Comment by milanhokr** [comment]
Díky ale bohužel nefunguje - níže hlášky na příkazové řádce, stejné je s "default" i bez. Nenabízí to relevantní option. Bez toho jsem to spouštěl předtím (proběhlo a nepomohlo). docker version mi dá 1.12.2. Ale s nalezenými informacemi o volbách a řešení nejsem schopen pracovat.
P.S. Flow123 na druhém PC ve verzi 2.2.1 (tj. novější ze série 2.x) funguje

C:\Users\milan\Documents\_tmp\1Dtran-disperze>docker-machine regenerate-certs --client-certs
Incorrect Usage.
Usage: docker-machine regenerate-certs [OPTIONS] [arg...]
Regenerate TLS Certificates for a machine
Description:
   Argument(s) are one or more machine names.
Options:
   --force, -f  Force rebuild and do not prompt
flag provided but not defined: -client-certs

**Comment by jbrezmorf** [comment]
OK. Tak to spusť bez --client-certs:

    docker-machine regenerate-certs default

**Comment by milanhokr** [comment]
Udělal jsem v tomto pořadí:
regenerování
F123 ... chyba
regenerování
restart PC
regenerování ... seklo se na Waiting for SSH ... (asi tím že nebyl dosud spuštěn Docker?) ... ctrl+c
F123 ... chyba (zachytil jsem hlášky navíc při prvním spuštění po restartu, je tam také "...may have new IP ... rerun docker-machine env ..." a v hláškách potom je pořád IP kterou jsem měl doma, i když nyní spouštím na TUL na eduroam, ale to spíš vypadá že jde o samostatnou IP virtualboxu nikoli skutečnou kterou mám v jedné nebo druhé síti (logika mi uniká)
regenerování (teď proběhne - pro jistotu, pokud by předtím zůstalo nějak napůl něco)
restart PC
F123 ... chyba stále stejná :-(

v radách na jednom z odkazů bylo také vyčistit pozůstatky všeho starého, ale tam byly takové divoké věci s dockerem a "machinami" ve kterých jsem se nevyznal (co je pro mě relevantní)
jedna z rad byla taky srovnat systémový čas PC a virtuálního stroje (to jsem nabídkutým příkazem udělal a zdálo se že proběhlo)

**Comment by janhybs** [comment]
@milanhokr Můžu se zastavit a mrknout se na to osobně, jestli problém ještě přetrvává, stačí zavolat.

**Comment by janhybs** [comment]
S nižší verzí **Docker Toolboxu** nelze generovat clientské certifikáty, takže jediné řešení je manuálně odstranit machine `default` a nainstalovat flow123d znovu. Tento problém souvisí pouze se starší řadou `Flow123d 2.x.x`, řada `3.x.x` pracuje s **Docker for Windows** a vše by mělo fungovat.

Další problém, po reinstalaci nefungoval `flow123d.bat` ale pouze `fterm.bat`, je to tím, že u @milanhokr přestal mít současný uživatel `group id` (asi po nějaké aktualizaci) a to způsobilo, že spouštění containeru selhalo.

Řešení je odebrat `group id` a další parametry z `docker run` příkazu ve skriptu `fterm.sh`, avšak to způsobí, že vytvořené soubory budou mít špatné oprávnění (což na Windows tak nevadí, ale na linuxu by to byl problém)
