### ISSUE TITLE
Záhadná chyba F123 na Charonu - "Python Error" a "No profiler"

### ISSUE THREAD

**Issue by milanhokr** [flow123d/flow123d#1257]
**Describe the bug**
U některých úloh se objevuje série chybových hlášek při běhu F123 ale nejsou to typické hlášení chybného zadání F123.
začíná to tímto: 
"terminate called after throwing an instance of 'boost::exception_detail::clone_impl<PythonLoader::ExcPythonError>' "
V jednom případě na konci běhu (vše už spočteno, uloženo) a v druhém případě úplně na začátku, ještě než začne asi načítat yaml. Nedokázal jsem rozlišit čím se úloha liší od jiných funkčních.

**To Reproduce**
- software version / branch / commit hash
version 3.0.3 commit: eedc5859a (instalace charon)
- steps to reproduce the behavior
- link to source files, input files
\storage\liberec3-tul\home\milanhokr\puklina\fm2\msjv1r-3D\07\
úloha kde se to děje na konci po spočtení (ve f123-log je vše ok, hlášky jsou v stdout)
\storage\liberec3-tul\home\milanhokr\puklina\fm2\msjv1r-3D\t01\
\storage\liberec3-tul\home\milanhokr\puklina\fm2\msjv1r-3D\t01s\
úlohy kde se to děje na začátku a nezačne nic dělat (ve f123-log jen skončí, hlášky jsou v stdout)
Od předchozí se liší přidáním transportu. Jsou to paralelní a sériová varianta, myslel jsem původně, že je to podobý případ jako dříve, nezachycení přetečení paměti, ale to nedává smysl, když je to na začátku před alokacemi.
Přijde mě, že úlohy se nijak neliší od předchozích funkčních např. v adresáři \home\milanhokr\puklina\fm2\msjv1b-3D\ (jen jiná síť, názvy regionů), ale nic nehlásí ve vazbě na uživatelské zadání. Není moc prostoru ty funkční a nefunční kombinovat dohromady, nejdřív počkám, zda někdo těm hláškám rozumí.
Zkusil jsem znovu pustit jednu dříve funkční a hláška se nově objevila také (po výpočtu, úloha proudění) - ty dva běhy se rozliší podle datumu souborů (13.7. chyba vs 26.6. ok).
\storage\liberec3-tul\home\milanhokr\puklina\fm2\msjv1b-3D\f05\

Zkusil jsem ještě jestli není nějak přeplněným diskem, odmazal jsem cca 10GB a zkusil t01s, totéž.

**Comment by Paulie14** [comment]
Milane, nevim, proc se to deje, ale zrejme se jedna o problem profileru. S tim ty nyni pocitat nepotrebujes, tak to zkus sebehnout s parametrem `--no_profiler`. Pak verim, ze to pujde a ja se zatim podivam, proc to tu chybu hlasi.

**Comment by Paulie14** [comment]
The important part of the output is:
```
00:00:01.096      MPI size: 1
00:00:01.099      This is Flow123d, version 3.0.3 commit: eedc5859a
00:00:01.099      Branch: 3.0.3
                  Build: Feb  4 2020, 11:28:46 flags: -O3 -DNDEBUG -Wall -Wno-unused-local-typedefs -Wno-deprecated-declarations -std=c++11
                  Fetch URL:  https://github.com/flow123d/flow123d.git
terminate called after throwing an instance of 'boost::exception_detail::clone_impl<PythonLoader::ExcPythonError>'
  what():  --------------------------------------------------------
Program Error: Python Error: 
Type: <class 'ModuleNotFoundError'>
Message: No module named 'profiler'
Traceback: 

Paths: 
/software/flow123d/local/lib/python3.6/site-packages
/software/python36-modules/gcc/lib/python3.6/site-packages
/software/python-3.6.2/gcc/lib/python36.zip
/software/python-3.6.2/gcc/lib/python3.6
/software/python-3.6.2/gcc/lib/python3.6
/software/python-3.6.2/gcc/lib/python3.6/lib-dynload
../lib/python/flow123d
/auto/liberec3-tul/home/pavel_exner/workspace/flow123d-release/flow123d/lib/python/flow123d
/opt/flow123d/lib/python/flow123d
/opt/flow123d/flow123d/lib/python/flow123d
```
It can find the profiler python files in the given paths.
Somehow, there is the path `/auto/liberec3-tul/home/pavel_exner/workspace/flow123d-release/flow123d/lib/python/flow123d`,
leading to my dir, from which I did the install.
And in contrast to that, there is no path `/software/flow123d/3.0.3-dev/lib/python/flow123d/`, where I would expect the python modules to be.

Is it a problem in the installation process?

**Comment by jbrezmorf** [comment]
Installation seems OK:
```
jan_brezina@charon:~$ ls /software/flow123d/3.0.3-dev/lib/python/flow123d/
benchmarks  coverage  __init__.py  ist  loggers.py  profiler  scripts  system  utils
```

In particular, the module "profiler" is available.

@janhybs : According to my limited knowledge of the installation process there is a step that set python paths. It seems that both relative "../lib/python/flow123d" and absolute "/auto/.../pavel_exner/.../flow123d" are added. Why there are the "/opt/..." paths?

@Paulie14 : It seems that version 3.0.3-dev fails after some date. Did you removed the "/auto/.../pavel_exner/.../flow123d" directory?

**Comment by janhybs** [comment]
@jbrezmorf Installation process is different on each platform and with/without docker and also for packed/local sources. In CMake, we include relative/absolute and docker paths:
![image](https://user-images.githubusercontent.com/894428/87514108-04f9a200-c67a-11ea-8195-14c9109894c5.png)

When packing, auxiliary scripts extend python path to some degree. Also when creating docker images, we modify paths as well.
For now, along with @Paulie14 we fixed 3.0.3-dev on charon and all future releases should have extra path set on charon.

fyi. python paths haven't been touched in 4 years, so I'm not sure why the error occurred now.

**Comment by Paulie14** [comment]
Well, I did remove the install files for 3.0.3-dev when I was doing the 3.0.4-dev version. That is why it cannot find the path to my dir. Should I always keep it for future??
@janhybs How can I update the module file also for 3.0.4-dev? (I was not able to overwrite the file..)

**Comment by Paulie14** [comment]
fixed, both 3.0.3-dev and 3.0.4-dev modules working at the moment.
