### ISSUE TITLE
Empty balance files when no field for output is selected in steady case.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1262]
Considering suppressed output fields:
```
output:
      fields: []
```
then water balance file in DarcyFlow is empty in steady case.
Found solution is to add auxiliary output time at t=0:
```
output_stream:
      times: [0]
```
This is however not very clear usage for the end user.
(Try it e.g. in test 11/01.)

Problem investigated up to `Balance::is_current()`, where the only TimeMark of `balance_output_type` is at infinity,
so false is returned at time t=0 and balance output is skipped.

**Comment by jbrezmorf** [comment]
Possibly mark also time 0 by the balance_output_type.

**Comment by Paulie14** [comment]
Solved by 18a669ea53767c46840099176af198df1a41d118.
