### ISSUE TITLE
Problem in balance if order of elements on input mesh is changed.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1273]
After MeshOptimizer implementation we have problem with correct output of mass_balance in tests with long time steps (03 / 09 and 21 / 03).  Data in column "error" of region "ALL" and quantity "age" is too different from ref_output and and they differ for np=1 and np=2. The problem arose in commit e099032. Original and both changed mass balance files are attached.
[mass_balance-orig.txt](https://github.com/flow123d/flow123d/files/5584423/mass_balance-orig.txt) - output before MeshOptimizer implementation
[mass_balance-changed-1.txt](https://github.com/flow123d/flow123d/files/5584724/mass_balance.txt) - output after MeshOptimizer implementation np==1
[mass_balance-changed-2.txt](https://github.com/flow123d/flow123d/files/5584714/mass_balance.txt) - output after MeshOptimizer implementation np==2

**Comment by jbrezmorf** [comment]
Problem 21/03 is a FV transport with very large time step (6 convection steps per 100k s TOS steps).
- difference 1e-2 in 'age_conc' in last step
- velocity about 1e-6

Not clear why this is dependent of the ordering of elements.

**Comment by dflanderka** [comment]
Problem is temporarily fixed in commit 10fbd8a1a. Problematic serial tests are switched off now. Please revert this commit after fix this problem.

**Comment by jstebel** [comment]
I have checked the changes in mass_balance files and it seems that the
"error" values (original of order 1e-9, changed 1e-5) are both very small
in comparison to the size of cumulative sources/fluxes (1e5), which have
not changed. So I would ignore/suppress the difference as it probably is
the result of truncation error when sum is evaluated in different order.

**Comment by jbrezmorf** [comment]
Truncation error is probably not the source of the problem as the mesh is small and there are just a few time steps.

**Comment by jbrezmorf** [comment]
Here is difference in the 'age_conc' field for the first and the last output time.
![21_03_age_diff_01](https://user-images.githubusercontent.com/326204/100624759-0fb08d00-3324-11eb-8eb4-3c6d3c8a3ff7.png)
![21_03_age_diff_10](https://user-images.githubusercontent.com/326204/100624760-10492380-3324-11eb-9e81-c7384593376d.png)


Maximal difference is about 1e-2 that is relative error about 1e-6. That can not be attributed only to the truncation error.

**Comment by jbrezmorf** [comment]
However, the relative difference in U235 is of a similar or even greater order:

![21_03_U235_rel_diff_02](https://user-images.githubusercontent.com/326204/100626279-eb55b000-3325-11eb-90ed-f7e73ed75998.png)

**Comment by jbrezmorf** [comment]
The comparison has to be done on commit 95d19916. This is a commit where VTK output is temporarily permuted to the inial mesh ordering.

**Comment by jbrezmorf** [comment]
Seems that problem is not from sources. Here is the relative difference `(new - ref)/ref` for the problem `20/02_sources` that is FV transport with two volume sources. Relative error is under 1e-10.
![20_02_rel_diff](https://user-images.githubusercontent.com/326204/100630238-95cfd200-332a-11eb-9c4e-9e463770cd9a.png)

**Comment by jbrezmorf** [comment]
So we can possibly blame the operator splitting and reactions.

**Comment by jbrezmorf** [comment]
... that is not the case. As for the test 21/02 (reaction, FV transport)  the relative difference is about 1e-8.

![21_02_reaction_FV_diff](https://user-images.githubusercontent.com/326204/100632444-1d1e4500-332d-11eb-9480-3b0161e3aa0c.png)

**Comment by jbrezmorf** [comment]
More tests are necessary with that particular mesh of the test 21/03.

**Comment by jbrezmorf** [comment]
@dflanderka wrote on Slack:
Dokončil jsem změny v DF mesh optimizer, které se týkají úprav kódu (mimo unit testy). Mám dvě zprávy - jednu dobrou a jednu špatnou, ale špatnou jen mírně.
- začnu tou špatnou. Úpravy metody calculate_size nám opět rozbily výstupy VTK. V některých testech jde jen o několik prohozených dvojic elementů, v jiných jsou rozdíly větší, ale vizuální kontrolou v paraview si výstupy odpovídají. Takže stačí změnit ref_out.
- dobrou zprávou je, že úprava vyřešila problém v bilancích i v dalších testech. Pro bilance jsem vrátil původní hodnoty ref_out a pro oba testy bilance projdou sériově i paralelně. Dalším problematickým testem byl test 26 / 02, kde se v okolí puklin změnily výrazně koncentrace, že to bylo vidět na pohled v paraview. Pokud porovnám původní data ref_out s novými, změny v paraview už nejsou viditelné. Podobně funguje i ten test, kde byla jediná chybová hodnota. Sice jsme uvažovali, že problém vznikl kvůli tomu, že problematická hodnota je velmi malá, ale ani zde nešlo hodnotu nastavit tak, aby test prošel pro sériové i paralelní spuštění. To už teď funguje.

**Comment by jbrezmorf** [comment]
TODO: We need carefull tests and review of the Mesh Optimizer.

**Comment by jbrezmorf** [comment]
Improvement in the stability of the problematic test was due to commit 66306e594 and the subsequent one.

**Comment by jbrezmorf** [comment]
Test of the Mesh Optimizer: `output/optimizer_output_test.cpp`. Possibly move to the mesh and convert to the real unit test.

**Comment by jbrezmorf** [comment]
TODO:
- repeat comparison of the test 21/03 with and without initial MeshOptimizer step

**Comment by dflanderka** [comment]
Balance outputs are same for running with and without initial MeshOptimizer step.
