### ISSUE TITLE
Changed DG output in test 26 / 03.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1274]
After MeshOptimizer implementation output of B_conc field is partly changed. Different values are near fractures. Number of incorrect values decreases in time. Original and changed output files in different time steps:

Time 0.5:
[transport-000001-orig.vtu](https://github.com/flow123d/flow123d/files/5588707/transport-000001.txt)
[transport-000001-changed.vtu](https://github.com/flow123d/flow123d/files/5588712/transport-000001.txt)

Time 5.0:
[transport-000010-orig.ftu](https://github.com/flow123d/flow123d/files/5588721/transport-000010.txt)
[transport-000010-changed.vtu](https://github.com/flow123d/flow123d/files/5588726/transport-000010.txt)

**Comment by jbrezmorf** [comment]
Difference of B_conc in the time 1, the CORNER data were first converted to NODE data then interpolated to the other dataset mesh:
![difference_B_conc_time_1](https://user-images.githubusercontent.com/326204/144266381-abb3ff1b-2818-405a-b470-e63b1712cee4.png)

Seems there are few significant differences. Not clear which test it is.

**Comment by jbrezmorf** [comment]
Result change confirmed:
- before optimization difference about 1e-6
- after optimization difference about 0.2 (20% relative error !!!)

Further code changes decrease the error to about 10%.

**Comment by jbrezmorf** [comment]
- Confirmed substantial difference in results of 26/02 when using and not using the the optimization. Result is about 20% 
nearly same with and without sorption. 
- Further tests should be done without sorption and try to make problem as simple as possible. 
- Created a script to calculate both cases and compute difference.
- TODO: set better vtk mapper to see differences and plot the scale.

**Comment by jbrezmorf** [comment]
Both differences in 26/02 and 26/03 were caused just by incorrect merging of the corner data to the point data. The VTK filter in use does not take care of averaging the values, rather it takes the first or the last one making it sensitive to the node numbering.
After performing filter chain: PointDAtaToCellData -> CleanToGrid -> CellDataToPointData
the fields get very blured byt the relative difference is of order 1e-10.
