### ISSUE TITLE
Problems in simple tests in mechanics.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1302]
Created 2 tests according to A. Verruijt (2014)
and
https://www.researchgate.net/publication/222660034_A_fully_coupled_3-D_mixed_finite_element_model_of_Biot_consolidation

- 50-02 Terzaghi's problem
   - 1D problem of soil sample confined at the bottom (and along the 1D sample)
   - applying load at the top, drainage (h=0) at the top
   - poor convergence for small storativity (solved by different time scale)
   - [x] PROBLEM - the initial pressure should only decrease (zero in infinity) from the top where is the drainage,
     but instead it increase in the first step

- 50-04 Terzaghi's problem
    - similar to 50-02, data according to article, analytical solution available as pvfilter
    - [x] PROBLEM - pressure solution far from analytic
 
- 50-03 Mandel's problem
   - 2D problem of soil sample confined at the bottom
   - applying load at the top, while there is no drainage
   - the soil sample deforms (expands) only in horizontal direction while draining on sides
   - [x] PROBLEM - cannot prescribe roller at the bottom
   - [x] PROBLEM - large deformation at zero time step, then the sample goes back up!
   - [x] PROBLEM - same behaviour is also in 3D case, computed on 1/4 of the domain (can fix normal disp. on the left and at the bottom)

- 50-05 Mandel's problem
    - similar to 50-03, data according to article, analytical solution available as pvfilter
    - [x] PROBLEM - pressure solution far from analytic

- [x] PROBLEM - both tests 50-02, 50-03 fail in parallel run (different results in mechanics, see especially the zero time step)

**Comment by jbrezmorf** [comment]
After discussion with @jstebel at 28.5.:

Seems that we should be more careful with the meaning of prescribed traction in the mechanics. Currently only $\sigma \cdot \vc n$ is prescribed, but we should rather work with balance of internal and external forces. Let us assume a Robin boundary condition in the Darcy flow with $p_0$ be the outer pressure and $p$ be the interior pressure at the boundary.

Total internal force on an elementary surface is: 
$ \sigma \cdot \vc n + \alpha p$
which comes from the balance of forces on a virtual internal interface.

The total external force is in general:
$ F + p_0 \beta$
where $F$ is a mechanical force applied to a virtual piston. The atmospheric pressure $p_0$ is applied only on the surface of open pores and possibly further reduced if the pores in the piston have a smaller surface. 

The limit case of Dirichlet BC in the Darcy flow, means $p_0 = p$ and the pressure difference should cause no additional force so the balance of forces should be:
$ F = \sigma \cdot \vc n$

The limit case of Neumman BC, means $p_0 = 0$ and balance of forces should be:
$ F = \sigma \cdot \vc n + \alpha p$.

Considering these cases we propose BC in the form:
$F = \sigma \cdot \vc n + \alpha (p-p_0)$
this should be consistent with basic scenarios, but it is unclear if there are scenarios where $\beta$ differs from $\alpha$.

**Comment by jstebel** [comment]
Comments to 50-03:
- Roller b.c. - my experience is that with iterative linear solver (default) it works, but direct solver fails due to nonuniqueness of solution.
- wrong displacement field - fixed mistake in update of initial displacement divergence. Also related to the proper mechanical b.c. on top (currently mechanical traction, It seems that correct is full poroelastic traction).

**Comment by jstebel** [comment]
Done in #1295.
- implemented generalized stress b.c. which distinguishes Dirichlet condition in flow
- fixed some bugs in HM solver
- corrected analytical solutions
- reduced some tests and added 1 test for Terzaghi's problem in 3D.
