### ISSUE TITLE
Mass balance - wrong results in general case with reactions involved

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#131]
Problem: 
Current MassBalance calculates in ConvectionTransport.calc_elem_sources sum of concentrations over all phases - in general case it will not give proper results because different quantities are conserved e.g. in sorptions and reactions.

Calculation of mass_balance over boundaries is ok.

- [x] temporary solution: the mass_balance is calculated only over the mobile phase. This will give good result when no reaction_term is present. Otherwise it writes warning. Leave mass balance only in tests in which only transport is considered. Done in commit 31a94bbd59cf856b1c75fbf4d489c7ccd035dff0

- [x] go through the equations in reaction term and check what quantities are conserved and how to calculate mass balance on elements

- [x] suggest new mass balance computation that will be able to include all the models in reaction term

related to :#102

**Comment by jbrezmorf** [comment]
merged in 084284
