### ISSUE TITLE
Elasticity improvements

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1316]
- Clarify zero pattern and preallocation in the Elasticity, possibly use separate linsys and matrix for zero step and update solution, keeping the nonzero structure.
- Simplification of mechanics assembly.
- HM Iterative is dependent on lame_* functions which are models now.
- avoid LinSys_PETS explicit pointer type cast. If possible move construction and initialization of the LinSys into single method avoiding typecasts.
- How was data_ used? Do not see declaration of data_. How it is related to the coupling?
- elasticity.cc, solve_linear_system: 
  ```
      if (rhs == nullptr) VecDuplicate(*( eq_data_->ls->get_rhs() ), &rhs);
        VecCopy(*( eq_data_->ls->get_rhs() ), rhs);
  ```

**Comment by jstebel** [comment]
- Zero pattern as well as assembly is the same for zero time step and update_solution. Removed unnecessary flag "allocation_done".
- No cast to LinSys_PETSc found any more.
- EqData simplified, but still contains dof handlers, balance and linsys objects.
