### ISSUE TITLE
Check whether HM iterative solver diverges.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1343]
- can we check that HM iterative solver diverges?
- we should write it to std output - e.g. `HM Iteration diverges` or `HM Iteration did not converge in <max_it> iterations`
  so that it can be checked later in log
- should we continue computation or end the process? (currently continue)

(Motivation - need to detect diverging samples when solving problems with random parameters)
(I would add the message `HM Iteration did not converge in <max_it> iterations` at least)

**Comment by jbrezmorf** [comment]
For 3.1.0 merge current solution to master.
For 4.0.0 we should use common reporting when using various non-linear solvers.

**Comment by Paulie14** [comment]
Done by 61fc49753d482405c64f63ea093ed825f3b751a9, continues by #1362.
