### ISSUE TITLE
Field output via value cache and output to multiple interpolations.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1344]
- [ ] Input format chage interpolation to Array of interpolations.
- [ ] Move interpolation from fields into OutputtimeSet. Add it as std::array<bool, 4> , add typedef as DisceteSpaceFlags.
- [ ] Pass DiscreteSpaceFlags  intofield->field_output(...)
- [ ] Change field->fill_output_cache to use new assembly separate assembly step for NODE / CORNER data and for ELEMENT data.

**Comment by jbrezmorf** [comment]
@dflanderka Seems this issue is done. At least part of it is in commit ed1b00a4afcd76648c0b230caf6e0b29623d56d6. 
If this is true just close the issue.

**Comment by dflanderka** [comment]
Issue was solved in #1347.
