### ISSUE TITLE
Reading FieldFE from gmsh is broken - reconsider component indexing approach.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1366]
Issue based on observations in PR #1361

Reconsider component (substance) indexing approach:
We used to support multiple substance values as vectors inside `ElementData` section in MSH format in the past.
This is no longer supported, although some parts of code still exist (especially in `get_element_data` in `msh_basereader.cc`).
This approach was also not appropriate due to the fact that the substance names were not written in the msh format and 
the order of substances must have been kept (equal to order in yaml) while reading.
Currently the MSH format should behave more like VTK - for each component (substance) have its own `ElementData` section.
The field names would then be same as in VTK, e.g. `A_conc`, `B_conc` for substances `A` and `B`.
This approach would also enable to read (in MSH) what is written by Flow123d (in MHS) which does work for substance components at the moment.

TODO:
- [x] change default value of `component_idx` in FieldAlgorithmBase (`.impl.hh`) to zero (currently undef_int, and then checked in heat eq.)
- [x] both VTK and MSH will not support components (substances) - remove `can_have_components_` flag
- [x] then simplify the `get_element_data` function, avoid some of the conditions [Partialy done.]
- [x] prepare tests for writing and reading MSH data (analogical to test 03-44 and 03-45 for VTK)
- [ ] the interface of the reader lacks proper documentation
- [x] consider merging two phase reading: `find_header` followed by `get_element_data` in `FieldFE`
- [ ] consider further the polymorphism in reader classes (what is common and what is format dependent - see `MeshDataHeader` struct)

**Comment by Paulie14** [comment]
@jbrezmorf please confirm the statements and todo list

**Comment by Paulie14** [comment]
- seems that we can remove the `component_idx` from the reader altogether
- then also `CacheData` in `ElementDataCache` would be always vector of size 1 (every substance field would have its own `ElementDataCache`, correct?)

**Comment by Paulie14** [comment]
I removed `component_idx` and `can_have_components_` and the condition from `get_element_data`.
I have now working test on write-read MSH data with `equivalent mesh`.

However using `identic_mesh`, the element data are permuted and I cannot figure out how..
Similar behaviour can be seen with VTK.
If this not the case for using identic mesh then I have no idea when to use it..
Is the mesh optimizer and its permutation somehow involved?

**Comment by Paulie14** [comment]
Update: VTK with identic mesh give different results only when running parallel

**Comment by Paulie14** [comment]
Note: In unit tests `mesh/msh_vtkreader_test.cpp`, `output/reader_cache_test.cpp`, we read componentwise the vector data from vtk into multifield.. Apart from the unit test, I don't see any other usage of this MSH-like approach.

**Comment by jbrezmorf** [comment]
Identic mesh can not work with permutation of element for memory locality. We would like to drop this option, but it is essential to allow calculations with mesh deformations. So we should allow this , but do not trust the user and check if the mesh is topologically equivalent. Next essential step to make it work in key use cases is to support mesh output after permutations. Ideally out of the Flow123d. We should try to start a Python interface to some Flow123d features.

**Comment by jbrezmorf** [comment]
TODO: Implement mesh output after permutations.
Currently, the GMSH output keeps the input permutation of the elements.
