### ISSUE TITLE
New assembly algorithm in observe output

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1374]
For observe output and XFEM we have to design and implement a variant of the patch creation that changes the EvalPoints for every new patch. 

Prerequisity: FEValues and ElementValues implemented as FieldCaches.

**Comment by jbrezmorf** [comment]
Idea:
- have the main loop over observe points in the EquationOutput
- create a single patch for all observe points setting up ElementCacheMap in order to make Field<>::cache_update work

**Comment by jbrezmorf** [comment]
DONE
