### ISSUE TITLE
Fix test 50/01 after permutation of element nodes

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#1378]
After merging master into JS_bc_mechanics, test 50_mechanics/01_inject shows small deviations of pressure and velocity from the reference solution (histogram in ParaView). Comparison in ParaView is limited due to permutation of nodes, so there should be some improvement made to check exact differences. Also recompute reference solution with improved tolerances.

Parent commit JS_bc_mechanics: fef992e1d1bed4d6e14fa50b68761fe72e368a1a
Parent commit master: f2ad740aab7d37eb5078c25ab7137f3e9a73c0ad

**Comment by jbrezmorf** [comment]
Prerequisity is an (optional) inversion node permutation at GMSH output.
Then we can compare results exactly and spot the source of differences.

**Comment by jstebel** [comment]
The problem was caused by insufficient tolerance of HM coupling. After recomputing the reference solution, test passes.
