### ISSUE TITLE
Failing unit tests 04/2022 in debug master

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1444]
unit-test-fields 
    / field_set_test / SomeEquation.add_operator_death
    / field_model_test Violated assert
    / field_algo_base_test / FieldFix/0.set_mesh   Seg fault
Time limits:
unit-test-intersection / speed_simple_22
unit-test-fields / FieldSpeed/1.field_fe

and more...

**Comment by jbrezmorf** [comment]
Add pragma to avoid usage of sanitizers in input and use them to catch memory errors in debug builds.

**Comment by dflanderka** [comment]
Solved in #1448 and merged.
