### ISSUE TITLE
Memory allocation problem in ElementCacheMap::create_patch()

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#1449]
For mesh with a large number of regions, each having a small number of elements, the size of ElementCacheMap::eval_point_data_ is under-estimated. Consequently, write out of allocated  field value cache happens.

To reproduce: Run the attached model under valgrind:

```valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes ../../../build_tree/bin/flow123d flow_mech-test.yaml```

Possible solutions:
- increase the constant 1.1 (also define it globally e.g. as a member of CacheMapElementNumber class)
- add debug assert into Array copy
- add check for memory overflow into create_patch
- merge regions having the same field algo 
- count different field algo during collection of the patch quadrature points, add simd_size  for every field algo ...
  this should provide guaranteed upper estimate of needed memory.
- merge fracture region in homogenization script

[model.tar.gz](https://github.com/flow123d/flow123d/files/8824850/model.tar.gz)

**Comment by jbrezmorf** [comment]
This must be fixed and backported into 3.9.0.

Cause of the problem (common to #1468 and #1469 most probably):
We collect integration points on the patch and then rearrange them to form sequences for individual regions. These sequences are padded to get multiples of the SIMD size (the size of vector instructions used in the BParser). Therefore we effectively increase total number of integration points which is difficult to predict. This get worse with large number of regions. The algorithm  allocates 10% more then is the maximal number of points in the cache however that may not be sufficient, causing either writes out of memory either when filling the caches (as probably reported in this issue) or even earlier in the create_patch (as reported in #1468 and #1469).

Fix:
- add (SIMD size - 1) to the number of integration points for every new region when creating the patch. Do not over allocate.
- do not track individual regions, but rather unique field instances, that may be done during the formation of the field dependency DAG 
Suggestion:
- add a composite test using many regions and test various assembly algorithms we have

**Comment by Paulie14** [comment]
The memory allocation problem seems to be fixed in 3.9.1 by 9274ec88c665eb77a53dd7eb3567fd66b88e4d1f.
@dflanderka will later check some specifics in FieldFormula in #1472.

Left open:
- [ ] merge to master
- [ ] do not track individual regions, but rather unique field instances, that may be done during the formation of the field dependency DAG
- [ ] add a composite test using many regions and test various assembly algorithms we have

**Comment by jbrezmorf** [comment]
Fixed by #1473
