### ISSUE TITLE
Remove DarcyMH

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#1458]
- [x] create git tag "DarcyMH Removed"
- [ ] remove from tests
- [x] remove from sources
- [x] mark into Changes

**Comment by dflanderka** [comment]
Popis nefungujících testů po náhradě DarcyMH,

- 02/08 původně odvozený z testu 13/02 (odstraněný, DarcyMH), nyní odvozený z testu 13/12 (LMH) - původní testy dávají každý jiné výsledky, proto došlo i u testu 02/08 ke změně výsledků. Ty se ale přesně neshodují s původními testy, protože 02/08 má jiný časový krok.  
- 02/11 chyba pouze pro pressure_p0, ale rozdíl oproti ref_out až 32 %, není moc jasné proč chyba vzniká, podobné jsou testy 30/01 a 30/02, ale ty navíc počítají rovnici pro transport
- 02/23 runtime error - vyřeší FEValues pro dim=0
- 02/24 runtime error - vyřeší FEValues pro dim=0
- 03/01 podobný případ jako 02/08 (vychází z testů 10/02 MH, resp. 10/03 LMH v masteru, jejichž výstupy se liší) - tím pádem má i 03/01 jiné výsledky po změně, navíc přesně neodpovídá původním testům, protože používá jiný časový krok
- 03/11 neprojde jen pro np=1, vychází z testu 20/03, v 03/11 stačí upravit r_tol a a_tol podle 20/03 a test projde
- 05/07 test citlivý na změny

**Comment by jbrezmorf** [comment]
**02/08 and 03/01**
 Just update the reference solution. The difference between MH and LMH in the case of unsteady problems is probably caused by the violation of the discrete maximum principle in the case of the MH method.

**Comment by jbrezmorf** [comment]
**02/23 and 02/24**
We should resolve together with @jstebel.

**Comment by jbrezmorf** [comment]
**03/11**
Just set the tolerances according to 20/03.

**Comment by jbrezmorf** [comment]
**02/11** is completely different from both 30/01 and 30/02 (these have just the same geometry, but have just steady DarcyFlow) 
If there is no other similar test in DarcyFlow tests, copy it to `13_darcy_time`. But change the geometry to 1x1 square. Then perform the calculation for MH and set it as the reference. Then we make a comparison. The discrete maximum principle is again probable cause.

**Comment by dflanderka** [comment]
New tests **13/14** is added - simulates problem in 02/11. 
Tests 02/08, 03/01 and 03/11 are fixed.
It remains to fix the tests: **02/11, 02/23, 02/24, 05/07 and 13/14**.

**Comment by jbrezmorf** [comment]
13/14: minor chenge, update reference solution, but also modify the test output times: 
- output time step 500
- finer grid
- remove time-dependent conductivity

**Comment by dflanderka** [comment]
Remove DarcyMH was merged in #1460 
- old code was moved to directory 'src/flow/old_mh_code'
- tests were fixed or removed (if parallel tests MH and LMH existed) - see comments above
- only tests 12/15 and 12/20 were switched off (non-compatible meshes)
- Git tag and note to Changes.md were added
