### ISSUE TITLE
Fix evaluation of boundary FieldFE.

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#1499]
Evaluation of boundary FieldFE doesn't work correctly in new assembly algorithm. Data of bulk elements is read.

**Comment by jbrezmorf** [comment]
There is a problem in FieldFE with scaling and value checking:

- in set_time, there is first call of sclae and check, which is done on ElementDataCache and has no information about associated regions
- later other check and scale is part of `calculate_element_values` and interpolations

1. Unification. It seems that there are several different cheks and at leas in gauss_interpolation there is an another scaling
2.  Allow correct check only for some regions of the computational mesh. 

Solution introduce `FieldFE::get_scaled_value(i_cache_el, &compute_region_errors)` and use it for access of the element data cache items. The method will do:
- read elemnt from current ElementDataCache of the field
- scale the value
- check the value
- report check result to the compute_region_errors
- return the scaled and checked value
