### ISSUE TITLE
test function of command line parameters

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#153]
- [x] JHy. Template and documentation for adding custom checkers into runtest
- [x] JHy. Implement regexp checker + basic integration test for command line params.

- [ ] Make integration test for correct function of command line parameters ...
Just start with test that Flow123d finish and do not crash for various command line parameters.
Possibly introduce a tool to define regexps that should be found in the stdout.

**Comment by x3mSpeedy** [comment]
I made new branch [JHy_runtest_update](flow123d/flow123d/tree/JHy_runtest_update), changes so far:
  - added docs and notes on modules in comparison 
  - moved `ndiff` module to separated file, all modules are now in folder `src/python/scripts.comparisons.modules`
  - introduced two interfaces
       - first one for calling external program => `ExecComparison`
       - second one handling comparison in place (no external call) => `InPlaceComparison`

All done in commit 48b3287e8e3abe9a87d6c7fbf1261b2a95474495

**Comment by jbrezmorf** [comment]
Tests for parameters:
--yaml_balance
--input_format arg
-l [ --log ] arg (=flow123)
