### ISSUE TITLE
Flow123d github io - download links do not work for 3.9.0.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#1561]
- download link for windows installer does not work
- download link for linux installer does not work
- experienced in explorer and chrome
- can be bypassed by "browse-all" option

**Comment by jbrezmorf** [comment]
That's a mysterious behavior. Here are my findings:
- confirm that links do not work under Chrome on Linux. The blank tab gets opened is closed instantly.
- downloads work under Firefox
- relevant page is /_includes/banner.html
- links are composed by JS and are correct
- links placed in Chorme's address bar start download just fine
- tried to remove target=_blank attribute and add download attribute to the <a> tag, without result
- placing the <a> tag into blank HTML file the links works both with and without download attribute

**Comment by jbrezmorf** [comment]
Problém je patrne [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing).

Nutno povolit na straně hostujícího serveru, tedy share.nti.tul.cz:

do appache2.conf přidat:
```
<Directory "/...Modelari/flow123d"> 
...
# Add CORS headers <IfModule mod_headers.c>     Header set Access-Control-Allow-Origin "https://flow123d.github.io" 
    Header set Access-Control-Allow-Methods "GET, OPTIONS"     Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept" </IfModule>
</Directory>
```

**Comment by jbrezmorf** [comment]
Fixed for recent version.
