### ISSUE TITLE
Partition of mesh ends with PETSC error on multiple processors.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#164]
- on mesh with one element only
- found out when computing some tests on mesh with only one element (in dual porosity)
- it crashes somewhere after mesh reading, when the partitioning is being created, on processors with rank>0

**Comment by jbrezmorf** [comment]
Problem is principal. We can not run decompose a mesh with single element. However the result should not be a crash. We should check that number of elements per processor is meaningful (say at least 10, default value can be changed trough a command-line parameter) and possibly reduce number of used processors (use own MPI_Communicator).

**Comment by jbrezmorf** [comment]
Temporary solution: just check and rise an exception.
