### ISSUE TITLE
New integration tests

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#178]
- [x] design and document (in user manual) new organization of integration tests
	requirements: 
	-  organize according to equation
	- more specific tests, prefered comparison to analytical solution where possible
        - numeric codes
	- test targets generated by CMake like for unit tests
- [x] meshes directory (various meshes used by more tests)
- [x] general directory ( tests of general mechanisms, input, output,  command line parameters)
- [x] flow: boundary conditions, fracture coupling, potential flow, time dependent data, unsteady flow, sources, anisotropy
- [x] complex: complex tests covering many functionalities in one test - for quick code validation
- [x] transport:
- [x] reaction term: see #125, #124 
- [x] coupling:

**Comment by jstebel** [comment]
Tests moved to new directory integration_tests.
To do:
[ ] review mesh files - remove duplicate and similar files, rename them consistently
