### ISSUE TITLE
Script to set license headers to source files

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#186]
For a given file the script should detect if it has a header, remove the header and replace it with the
header specified as the second parameter.

**Comment by jbrezmorf** [comment]
I guess this is already done, but possibly the script is not part of the Flow123d repository. Just put it into bin/python (supposing it is python source).

**Comment by x3mSpeedy** [comment]
Added to Python infrastructure in 9db0ac2219be3cbfca670609743cff8a121dcd30
