### ISSUE TITLE
multiple inheritance for Input::Record

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#190]
What do we want?
Enable to prescribe one common reaction record in Sorption (and DualPorosity) in solid/liquid (and mobile/immobile) zone, instead of two records reaction_solid+reaction_liquid (and reaction_mobile+reaction_immobile).

Problem?
We cannot derive a record from both SorptionMobile and SorptionImmobile for example. 

If we do in make_reactions() in DualPorosity something like:
```
//find records
Input::Iterator<Input::AbstractRecord> 
    reaction_it = input_record_.find<Input::AbstractRecord>("reaction"),
    reaction_it_mob = input_record_.find<Input::AbstractRecord>("reaction_mobile"),
    reaction_it_immob = input_record_.find<Input::AbstractRecord>("reaction_immobile");
    
//if reaction zone is specified then it overrides the reaction record
    if( ! reaction_it_mob) reaction_it_mob = reaction_it;
    if( ! reaction_it_immob) reaction_it_immob = reaction_it;
```
then user cannot specify the output fields for both mobile and immobile part.
All the input fields must be the same which is remembered and satisfied but not checked.

**Comment by jbrezmorf** [comment]
Part of New Input proposal.
