### ISSUE TITLE
Apply Input::factory

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#194]
Factory can be used in these cases:
-------------------------------------------------------------
Abstract record DarcyFlowMH
- can apply if we keep more derived classes
- can be applied (Steady_MH has one more parameter but default defined)
- used in constructor HC_ExplicitSequential

DESCENDANTS FOLLOWS
- Record Steady_MH
- Record Unsteady_MH
- Record Unsteady_LMH

-------------------------------------------------------------

Abstract record LinSys
- very good candidate
- descendants have different parameters in constructors

DESCENDANTS FOLLOWS
- Record Petsc
- Record Bddc

-------------------------------------------------------------

Abstract record Transport (class AdvectionProcessBase)
- good candidate
- descendants have constructors with same parameters
- used in constructor HC_ExplicitSequential

DESCENDANTS FOLLOWS
- Record SoluteTransport_DG
- Record HeatTransfer_DG
- Record TransportOperatorSplitting

-------------------------------------------------------------

Abstract record ReactionTerm
- to apply need concept of "multiple inheritance" , so that a Record could implement
several AbstractRecords
- descendants have constructors with same parameters
- used in DualPorosity::make_reactions

DESCENDANTS FOLLOWS
- Record Isotope
- Record DualPorosity
- Record Sorption
- Record SorptionMobile
- Record SorptionImmobile
- Record PadeApproximant
- Record LinearReactions

-------------------------------------------------------------

Abstract record OutputTime
- good candidate
- descendants have constructors with same parameters
- used in OutputTime::create_output_stream

DESCENDANTS FOLLOWS
- Record gmsh
- Record vtk

**Comment by dflanderka** [comment]
Factory is used in descendants of DarcyFlowMH, AdvectionProcessBase, ReactionTerm, OutputTime and LinearODESolver.

Not in LinSys - see #345
