### ISSUE TITLE
Interface of linear reactions and its numerical methods.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#195]
Split the linear reaction record/class and decay.

Linear reactions are defined by kinetic constant and conserve mass balance.

Decays are defined by half-life and do not conserve mass balance. Internally, the half-life is transformed to kinetic constant. Only molar weight is conserved.

Both classes should assemble the reaction matrix (the matrix of the system of 1. order differential equations) and then give to a numerical solver.

Pade Approximant is numerical method and should behave like a kind of solver as mentioned above.

TODO:
- split the class and think of the interface (LinearReactions, Decays, ...)
- improve records names
- use armadillo on the vectors and matrices
- use armadillo instead of petsc in PadeApproximant
- put numerical methods in different classes (like PadeApproximant)
- resolve the problem with mass balance conservation

**Comment by jbrezmorf** [comment]
merged in 70c9b8acf5
