### ISSUE TITLE
New output for Balance

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#219]
Provide writing balance data in following formats:
- CSV (comma separated values)
- possibly GnuPlot datafile (space delimited values)

For given time, the output method will write:
(i) 1 line for instant values on bulk regions,
(ii) 1 line for boundary regions and
(iii) (if cumulative==true) 1 line for cumulative values
The list of values to be written is described in comment prior to declaration of Balance (in file src/transport/mass_balance.hh, branch JS_mass_balance).

**Comment by jbrezmorf** [comment]
Check how the import into Excel works for both english and czech locales.

**Comment by jbrezmorf** [comment]
Change CSV variant to TXT output 9import in Excel is independent on localization):
tab delimiter, dot decimal point

**Comment by jstebel** [comment]
Apply the new Balance class to DarcyFlow.

**Comment by jbrezmorf** [comment]
Merged in 084284
