### ISSUE TITLE
Input - Storage modification

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#224]
Implement a method that takes  five arguments:
target_type, source_type, source_storage, index, vec_size

Pass recursively (deep first search) through both type trees and source_storage tree. Check that 
type trees match or there is an Array o type T in the source_tree where it is only type T in target_tree. 
During pass copy source_storage to return value and select particular index pro source_tree arrays.

**Comment by jbrezmorf** [comment]
TODO:
* add ASSERT for simplest Input types (Integer etc.) that target and source types match
  also make deep copy in order to preserve tree nature of the storage (otherwise we risk double deletes)
* in Record case and Array check that storage is of Array type before call of get_item
* make modify_storage to return non-const pointer, remove const_casts
* in the case of reduction of the array perform just deep copy of the memebr given by the index parameter and do not continue recursion using modify_storage.

**Comment by jbrezmorf** [comment]
* in StorageTranspose, make source_storage pointer to const StorageBase

* in AbstractRecord::transpose_to:
	* rename rec -> target_rec;  key_name->target_key
	* add minimalistic doc. *this is source abstract record, target_rec.val<Array>(target_key) is 	array of target records.
	* ASSERT -> if (it) { <user provided target array, do nothing>} else {<make conversion>};
	* may do ASSERT that storage for target_key is StorageNull (not necessary)
	* remove deep_copy
* in StorageArray:set_item:
 	* check that array_[index] is StorageNull and delete it, then assign new poiner.

**Comment by dflanderka** [comment]
Done in d9fac94
