### ISSUE TITLE
Bug - TOS wrong time governor usage with init_dt.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#227]
When using TransportOperatorSplitting method the convection call the next_time() method and 
moves the convection one step ahead of ReactionTerm (which uses the same TimeGovernor). 
The ReactionTerm has then wrong information about time_step and time_step_change.
If the init_dt is set then this results in LinearReaction in a bug - the reaction matrix is not computed even once, because is_dt_changed() returns false in the first step.

Suggestion:
- ReactionTerm classes should use their own TimeGovernors.

Future:
- Classes using TimeGovernor should call next_time() in the first place in update_solution() method.
- The TimeGovernor should provide a functionality (e.g. a structure) that give the user a view on the state of the TimeGovernor one step before. The implicit method would then use the current view (after next_time()) and explicit would use the view on the state one step before.
- Think of a functionality that enables communication, sharing and dependence between different TimeGovernors (e.g. TOS->Convection->ReactionTerm)

**Comment by jbrezmorf** [comment]
The original bug was resolved. However this is related to more general issue how to treat implicit and explicit solvers at jump times. S
