### ISSUE TITLE
Units in sorption

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#234]
According to users, preferred units for concentrations are as follows:
- concentration in liquid (solution)
  [kgm^{-3}], kilograms (of substance) per cubic meter of solvent (liquid, water) 
- sorbed concentration in a solid (in rock)
  [-], in kilograms of substance per kilogram of the dry rock
- coefficient of linear sorption K in this case
  [m^3kg^{-1}] 

Internally we prefer to use dimensionless concentrations, and dimensionless isotherm parameters, since these allow better separation of isotherm parameters (namely for nonlinear isotherms). Currently, we describe conversion formulas in the documentation. In future we should allow:
- output of concentrations in different units; this could be implemented through model fields
  which are evaluated only when required
- input of parameters in different units; How to name them? How to implement this? Currently we have two parameters for all isotherms. More parameters may be necessary for more complex isotherms (e.g. BET model). 

TODO: 
- simplify parameters of sorption since sorption coefficients are specific for particular solvent and rock so it is meaningless trying to separate them
- keep unit of mobile concentration [kg / m^3]
- change unit of solid concentration from [mol/kg] to [kg/kg]
- change meaning, name and unit of 'isotherm_mult'
  name: distribution_coefficient [ m^3/kg]
  meaning: C_s = K C_l ; K - distr. coef. ; C_s [kg/kg], C_l [kg/m^3]
  conversion K = M *k / \rho ; M - molar weight of substance, \rho - solvent density; k - isotherm_mult
- explain in documentation and in description that for substances with differnent isotops the distribution coefficient may be recalculated using molar weights ration.
- not clear how distribution_coefficient should be used in other isotherms

**Comment by jbrezmorf** [comment]
Final decision:
- keep concentration in liquid to be in kg of substance over kg of liquid phase (porosity)
- set concentration in solid as kg of substance over kg of solid phase (1-porosity)
- sorption coef. K in [m-3/kg] defined as $c_s/($\rho_l c_l)$

**Comment by jstebel** [comment]
There requirements contain some ambiguity. For example, it is required that
- new K has units m^3/kg
- new K = rho_solid * M_solid * old K ... here units do not fit: [m^3/kg] = [kg/m^3][kg/mol][mol/kg]

In my opinion the correct way is to postulate the balance equation and the isotherm:
- Balance: theta * rho_l * c_l + (1-theta) * rho_s * c_s = const.
- Isotherm: c_s = k_new * rho_l * c_l
Then it implies:
- c_s is dimensionless, k_new has units [m^3/kg]
- k_new = M_s * k_old / rho_l
- c_s(new) = c_s(old) * M_s

Is this OK?
