### ISSUE TITLE
Sorption - input exceptions, remove molar masses from input.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#237]
- improve input reading in SorptionBase by using input exceptions
- we can possibly remove molar masses from input, as they are now set in Substance record

I recommend to do it after JS_mass_balance and PE_reactions are merged. Do you agree?

**Comment by jbrezmorf** [comment]
Finish this in own branch separated from JS_mass_balance

**Comment by jbrezmorf** [comment]
Merged in a9d2335b94

**Comment by jbrezmorf** [comment]
Input reading done as part of a9d2335b94 merge.
Still have to deal with molar masses.

**Comment by jbrezmorf** [comment]
Check state of molar masses....

**Comment by Paulie14** [comment]
Get rid of redundant molar_mass vector in sorption in d84c791defcf127c2b0613000b7ac0c9cd2fb7bb.
Molar masses are members of substances, and do not appear anywhere else.
Now, I believe we can close this one.
