### ISSUE TITLE
Unclear exception in sorption coming from tom748_solve.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#244]
Jakub Říha reported unclear exception in sorption, in case "none".
Data available on bacula:
bacula.nti.tul.cz/intec/lide/pavel.exner/00_share/flow_problems/JakubRiha-sorption_error

The exception ("the root does not lie between bounds 'a' and 'b'") comes from boos::tom748_solve and I could not reconstruct it.
On the other hand, similar exception ("order of bounds 'a' and 'b'") can be thrown just by setting negative porosity.

- We should catch these boost exceptions.
- What should the message be?

**Comment by jbrezmorf** [comment]
Merged in a9d2335b94
