### ISSUE TITLE
windows test server

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#248]
1) create user bulid_cygwin_32 with locally installed Cygwin 32 bit
    run there Jenkins 32 bit windows builds, export packages to Bacula (same is now done on different machine)

2) create user bulid_cygwin_64 with locally installed Cygwin 64 bit
    run there Jenkins 64 bit windows builds, export packages to Bacula (same is now done on different machine)

3) make user package_tests to run tests of made packages
    Can we do automatic tests of packages (i.e. automatic installation and test running)?

4) Possibly other user for experiments and manual testing.

**Comment by x3mSpeedy** [comment]
1) Done, connection thru ssh.
2) Done, connection thru ssh on different port number.
3) Yes, using /S flag in NSIS installer, it is possible for the installer to run in automatic console mode. 
4) Done, created administrators account.

**Comment by jbrezmorf** [comment]
We have it and it works. Great.
