### ISSUE TITLE
Profiler improvements

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#273]
* support for high resolution timer in Profiler (should check it in configuration) - necessary to make benchmarks run as fast as possible yet still get reliable data. Default timer has resolution 20 ms which allows measuremet of 5 time frames with 10% precision in one second. Simply not enough. 
* test actual resolution of the timer, provide it through interface and report it on output in order to: possibly adapt benchmarks and know precision of collected data.
* Profiler that works also without mpi; split into two classes one for serial colection second for MPI reduction. Implement both serial and parallel output. Goal is to allow usage of Profiler without MPI.
* automatic instance of (sequential) profiler
* #271
* output in machine readable format suitable for sending to server

**Comment by x3mSpeedy** [comment]
Pull request on master #329 

> output in machine readable format suitable for sending to server

Python script in [this](https://github.com/x3mSpeedy/Flow123d-py-profiler-transform) repo

**Comment by jbrezmorf** [comment]
Put conversion script into main repo into bin/python.
Make flow123d option to turn text output on/off, text output should just call the conversion script (using PythonLoader class).

**Comment by jbrezmorf** [comment]
Merged in 2147fc4
