### ISSUE TITLE
Review transport boundary conditions

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#274]
Currently in SoluteTransport_DG we provide these boundary conditions:
- dirichlet
- inflow (prescribed total flux on inlet, zero diffusive flux on outlet)
- neumann (prescribed diffusive flux)
- robin (diffusive flux proportional to concentration difference)

Think if they all are useful and sufficient (e.g. one could prescribe total flux).

"Neumann" is probably not correct name.

**Comment by jbrezmorf** [comment]
duplicate of #335

**Comment by jbrezmorf** [comment]
Replaced by #414
