### ISSUE TITLE
Tutorial ideas

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#294]
In the section "Tutorial problem" in user's manual we should mention all possible equations that Flow123d can use, i.e.
- Darcy flow: Steady_MH, Unsteady_MH, Unsteady_LMH
- Transport: TransportOperatorSplitting, SoluteTransport_DG
- Reactions: FirstOrderReaction, RadioactiveDecay, DualPorosity, Sorption, SorptionMobile, SorptionImmobile
- HeatTransfer_DG

Think of making more tutorial problems, one for explaining one type of equations.

Selected CON files in tests directory could be thoroughly commented using e.g. MarkDown so that they could be automatically included into the manual.

**Comment by jbrezmorf** [comment]
- [ ] finish tutorials for every equation
- [ ] document scripts for creation of images (have images in repository) max 1MB per image
- [ ] Add scripts to have generated text part of reference manual
- [ ] Publish tutorials on web

**Comment by jbrezmorf** [comment]
Done.
