### ISSUE TITLE
auxiliary class VectorSeqDouble

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#299]
* auxiliary class for output elementwise concentration vectors in convection transport, sorptions, dual 
porosity
* provides:
	* constructor that creates 
		* shared pointer to vector of given size
		* PETSC VecSeq that use same data
	* getter for PETSC vector (used by scatters)
	* create_field method - returns corresponding FieldElementwise

prerequisity for #226

**Comment by dflanderka** [comment]
Done in a1e4879afcd8578a0b80603d0fd1e0f0046c9881
