### ISSUE TITLE
Balance file readability

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#315]
Summarizing ideas of balance file improvement:

- sign of sources: column source_in is negative and and source_out is positive - this agree with fluxes but if you have positive source it appears in source_out column. I believe switching the names of columns would make it more meaningful. Think about it.
(partly resolved by swapping column labels, unification of flux and source signs 
postponed to release 2.0.0)

- [x] make columns wider for names of regions (perhaps also substances) - there is an idea of cutting the names of and adding a column with regions numbers to resolve duplicit names
( resolved in gnuplot, human readable format, using region label column large enough)

- what is the row 'ALL'? Currently it includes both fluxes and sources. We should think of better name or separate into 2 summing rows (e.g. BULK and BOUNDARY)
( ALL is consistent with implicit region set names)

- implicit boundary region name should start with a dot '.IMPLICIT_BOUNDARY' and we should think of shorter name
( postponed )

- [ ] add empty line between times in the textual version
( resolved in gnuplot output)

- for work in Excelu is better to have one line(even very long) per time
(postponed)

TODO:

- [x] erase first empty column (in front of time column)
(resolved)

- [x] make the columns wider for exponential numbers
(resolved in gnuplot output)

- [ ] region IMPLICIT_BOUNDARY appears when not all boundary regions are specified. We should at least comment on that in documentation.
(resolved)

- [x] test both textual and csv output
(resolved)

**Comment by jbrezmorf** [comment]
Is txt format meant for Excel import? If so, we should not break import by enhanced formatting.
Possibly have external format tool written in python and optionally call it from Flow123d.

**Comment by jbrezmorf** [comment]
* keep consistency with input
* how it is done in other software?
* cumulative balance for the last step

**Comment by jbrezmorf** [comment]
merged in commit 283ae3ee94
