### ISSUE TITLE
Web page - switching between versions

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#328]
I found a bug in switching the versions on the web:
problem:
switch to 1.8.0 and go to source doc. 1.8.0:
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.0/doxygen/
go back, switch to 1.8.1 and go to source doc. 1.8.1:
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.01.8.1/doxygen/

End with error:

	The requested URL /~jan.brezina/flow123d_packages/1.8.01.8.1/doxygen/ was not found on this server.

So when switched back, it creates wrong address. The same case is the reference manual.

One more thing - the source doc of 1.8.1 is not just
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.1/doxygen
but it is
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.1/doxygen/flow123d/

Second small thing - wrong address for RC-1.8.0 reference manual
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.0_master/flow123d_1.8.0_master_doc.pdf
instead of:
http://bacula.nti.tul.cz/~jan.brezina/flow123d_packages/1.8.0_master/flow123d_doc.pdf

Another idea - we should create a simple page saying, that some documentation is not available, instead of 404 error...

**Comment by x3mSpeedy** [comment]
Should be [fixed] (https://github.com/flow123d/flow123d.github.io/commit/d0baccf16e7857735cb3d65c003916d5141f0dd6)

Issue was that global variable ```bacula_root_url``` contained url to bacula.
When version changed this variable was also changed resulting in appending version again and again. Solution was done by creating **local** variable ```bacula_url```.

**Comment by Paulie14** [comment]
Yes, the switching problem is gone. Thanks.
