### ISSUE TITLE
Embedded Python infrastructure

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#354]
Related to #336 and #98.

In order to implement parts of flow funcionality in Python, we need:
1. Source directory where to place our python modules (proposed: src/python and its subdirectories)
2. Source directory to place scripts that could be used by users (proposed: bin)
3. Source directory to place advanced/auxiliary scripts (bin/py)
4. Copy modules into 'build_tree/libs'
5. Modify PythonLoader constructor to set access to both system modules (either in system prefix or in our copy of system modules according to
    the COPY_PYTHON variable in the config.cmake) and to our modules. Current implementation is messed with various experiments to overcome 
    a bug in particular CYGWIN version. Is possible that Py_SetProgramName is not necessary. Question how to augment python module search path 
    through the C API.
6. Make some checks in modules of correct python version. Since when modules are used through scripts on the user system they can run under system python,
while when they are used through C API within flow123d they run under our embedded python. Could there be a confict of generated pyc files? 
Are the pyc files even generated by the embedded python? 

7. Test the infrastructure on Profiler formaters.

**Comment by x3mSpeedy** [comment]
- [x]  ad 1) in ```src/python``` is hierarchical structure of python modules
- [ ]   ad 2) currently no script are in ```bin```
- [x]  ad 3) in ```bin/python``` are python scripts which requires python modules located in ```src/python```, path is automatically fixed so **scripts can see modules**
- [x]  ad 4) cmake will copy (if flag COPY_PYTHON) contents of ```src/python``` into ```build_tree/lib/flow123d```. This path is appended so using embedded python in c++ will see modules.
- [x]  ad 5) in cmake is defined constant using ```flow_define``` named ```PYTHON_EXTRA_MODULES_PATH```. Value differ depending on COPY_PYTHON flag. It points to either ```src/python``` or ```build_tree/lib/flow123d```
- [x]  ad 6) all script files includes pathfix python file which appends to module search file ```src/python``` folder.
All script and modules includes python file which checks running version. If version is 3, execution is terminated with error.

After some testing: 
 - pyc files are generated even when embedded python is used. Pyc files behavior is following:

>.pyc files generated whenever the corresponding code elements are imported, and updated if the corresponding code files have been updated.
> The .pyc's timestamp **must be older** than the corresponding .py's timestamp to trigger a recompilation

- There should not be conflict since after copying all timestamps will be changed so pyc will be refreshed.

**Comment by jbrezmorf** [comment]
Are you sure, that python modules are accessible after installation from packages. 
Add test of python functionality (e.g.  profiler output or HTML IST output) into tests on windows that run from packages out of cygwin environment.
Then we can close this issue.

**Comment by x3mSpeedy** [comment]
After some testing It seems that **Embedded python does not work** like it should. Python seems to be working but not correctly. Output [here](http://ci2.nti.tul.cz/job/Windows-64-package-python_test/33/console) shows that python is somehow working (throwing errors, saying theres packages missing). But python paths are wrong:
```
PYTHON_PATH: 
/tests/03_transport_small_12d/../../lib/python27.zip:
/tests/03_transport_small_12d/../../lib/python2.7/:
/tests/03_transport_small_12d/../../lib/python2.7/plat-cygwin:
/tests/03_transport_small_12d/../../lib/python2.7/lib-tk:
/tests/03_transport_small_12d/../../lib/python2.7/lib-old:
/tests/03_transport_small_12d/../../lib/python2.7/lib-dynload:
/home/cygwin64/F123-windows-release/build-master/lib/flow123d
```

They are absolute paths or relative paths from cygwin environment

Python ImportError ```No module named _struct``` indicates that basic modules such as ```_struct``` cannot be found.

Should we maybe add more paths (relative) pointing to correct location in ```python _loader.cc```?

**Comment by jbrezmorf** [comment]
Thats exactly the reason why I want to make this kind of test. I was suspicious that we can not just add path relative to the location of flow123d during the build. We have to add path relative to the actual location of flow123d during execution. The location of the binary can be probably obtained by:
 Py_GetProgramFullPath

However, we probably need to introduce two macros one for absolute location used without PYTHON_COPY and one for relative location used for PYTHON_COPY variant.

**Comment by jbrezmorf** [comment]
depends on #184

**Comment by jbrezmorf** [comment]
Need to finish this issue. Possible reason could be, that we have to check and copy DLLs that the python depends on.
