### ISSUE TITLE
Replace MHFeValues with FeValues

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#358]
- [x] try to remove element side numbering hack in TransportDG::calculate_velocity()
mh_dh should currently use same numbering as in the mesh, which is same as in reference element (check this in Mesh:reinit(), side_nodes initialization)

- [x] create DarcyFlowMH::assembly_local_matrix() using FeValues nad suitable quadrature to compute local matrix, 
compare it against MHFeValues

- [x] replace usage of  MhFeValues::RT0_...(ele, point, side)  by FeValues

- [x] use new approach every where, remove MhFeValues

prerequisity for #232

**Comment by Paulie14** [comment]
done in b905ec7cf72bd1764cc29b438c0b580fb4dcee3a
pull request waiting for merging
