### ISSUE TITLE
Combine Neumann and Newton BC

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#367]
Allow combination of Neumann and Newton BC. (consider both Transport and Flow equations).
Reason: using Newton condition as model for drainage into watercourse (rivers) and consider infiltration at the same time.
Proposing: Introduce new BC type (combined) and remove current BC types.

**Comment by jstebel** [comment]
Dirichlet, Neumann and Newton(=Robin) are used in most situations I have seen (papers, software codes). I omit unilateral conditions (seepage face, atmosphere, spring), which are more difficult to implement and should be a separate issue.

Proposed classification of BC:
- Value (Dirichlet type): given value of the solution (pressure head, piezometric head, concentration , temperature)
- Flux: possible sum of Neumann or Newton flux

All parameters in BC should have natural units (without the manifold dimension "d") - this has to be changed in Transport and Heat.

Further remarks: See Google doc https://docs.google.com/document/d/1uMUYqo0sfiyYbHZpDRc8iwWqwtYEJ8lM2Eq1m3EJtSw/edit#heading=h.twyimfco1uwx

**Comment by jbrezmorf** [comment]
Replaced by #414 , #338 , and #413  - issues specific for equations.
