### ISSUE TITLE
Publish dates of the builds

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#375]
flow123d.github.com downloads should provide last modification dates for individual builds.
This is crucial namely for development builds.

Can not use a link provided by Jenkins: can not have this for particular branch, not sure, that the file was successfully published.
Seems that modif date of an external file can not be retrieved within JavaScript on client side. Possibly we can create file/files during build (?? a JSON) and
than load them from JavaScript.

**Comment by x3mSpeedy** [comment]
There are limited option in how to deal with this issue. GitHub pages are for static pages only.
> **static** here means, that all content which can be displayed must be present on server, in this case in repository.

Javascript can provide dynamic-like behavior but I think it cannot send request to server since everything is static-like (*will test it out*)

Loading json file from other domain is [problematic](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy) because security issues

Static limitation means, that after every build would have to be commit to repository, which would alter some json file where modification date would be written.

**Comment by jbrezmorf** [comment]
Can we load a static HTML from other server as part of the page on github?

**Comment by x3mSpeedy** [comment]
Using ```iframe``` element it is possible to render html page from other domain into designated area [example](http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_iframe). 

But just loading page using javascript is not possible withou dynamic server, example
```js
XMLHttpRequest cannot load "http://bacula.nti.tul.cz/~jan.hybs/flow123d_input_reference/index.html".
No 'Access-Control-Allow-Origin' header is present on the requested resource.
Origin 'http://x3mspeedy.github.io' is therefore not allowed access.
```

Bassically static solution can access things from different domain. That it ```iframe```, or images ```img```.
Popular approach is to load image from other domains (for example build status badges from jenkins ci server)
But it would be also possible to generate piece of page which would be injected after into static page.

**Comment by x3mSpeedy** [comment]
Publish dates are now automatically created. At the end of publishing process **json** file is created containing publish date information. Other information can be appended later. Json file can look like this:

```js
{ "build": "14-07-2015 12:54:34" }
```

Bacula server now contains ```Access-Control-Allow-Origin``` thanks to @jirihnidek,  in header so other domains can access files on server dynamically.
Javascript on [github io](http://flow123d.github.io/)'s page tries to locate file with given name. On success it extracts date and display date in download section. If file doesn't exists message ```build date unknown``` is be displayed instead.

While completing this issue. Web page was enhanced #342 now supporting useful placeholders in html code which will be automatically changed upon new selected value from dropdown component. Code was simplyfied, duplicated parts were removed. Now without javascript more parts of page will be accessible (such as static menu). It is now possible to **disable** some links for specific versions.

*There is still need to manually create json files for older versions which aren't builed anymore.*

 @jbrezmorf I think this issue can be closed now.

**Comment by jbrezmorf** [comment]
Great. One bug (up to my view), when switching to differnet versions the current page do not switch until reloaded. E.g.
1) select Download; main title report version 1.8.2 as well as the version of Download page
2) select Dev master; main title is Dev master but Download page is still 1.8.2. Confusing!

**Comment by x3mSpeedy** [comment]
Now when on download page, when changing version in dropdown, main title version is fixed to URL's version.

**Comment by x3mSpeedy** [comment]
I have done necessary changes, @jbrezmorf can you confirm correct functionality [now](http://flow123d.github.io/)?

**Comment by jbrezmorf** [comment]
Rather publish dates then period since build it's more precise and more to the point you usually want to know (e.g. to compare it to some other events).

**Comment by jbrezmorf** [comment]
Jan Hybs replay:
Situation **before** was: shown ```relative-date```, when mouse overed shown ```precise-date```
Situation **now** is: shown ```precise-date (relative-date)```, when mouse overed shown ```relative-date```
![image](https://cloud.githubusercontent.com/assets/894428/9721629/d097db7c-559e-11e5-8083-253dc9326fca.png)

Do you want to remove relative date as well? It's w´quite useful in new build, since you can see right away when was it build.

**Comment by jbrezmorf** [comment]
Great.
