### ISSUE TITLE
Linux packages for 1.8.2 and master do not run

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#378]
Running flow123d executable gives the following error:

relocation error: /tmp/flow/Flow123d-1.8.2-Linux/bin/../lib/libpthread.so.0: symbol __getrlimit, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

**Comment by jbrezmorf** [comment]
Should be fixed now. And definitely we shall solve such problems using Docker.
