### ISSUE TITLE
BUG - test15 explicit - program crash with balance off

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#384]
When we set balance = {balance_on = false}, the program crashes.

**Comment by Paulie14** [comment]
note: shared pointer cannot be compared with nullptr (transport.cc: 483)

**Comment by jbrezmorf** [comment]
Should make one test for every equation: Darcy flow, transport, transport_dg to test same problem with and without balance.

**Comment by Paulie14** [comment]
done in f6c3e87b0246aad3a7056f3d497e43e1c405729d in branch PE_balance
tests were created for future for darcy steady, unsteady MH and LMH, transport explicit and dg

note: shared pointer CAN of course be compared with nullptr
The problem was finally in darcy flow output where there was no condition on balance pointer.

**Comment by jbrezmorf** [comment]
merged in  465e49dd67
