### ISSUE TITLE
Json profiler data has zero values when running in paralel

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#393]
There seems to be bug when collecting data from *several processes* (**MPI** collecting). Must investigate further.

**Single process example output** ([link to file](http://hybs.nti.tul.cz/flow-collector-arts/2015-07-24_11-11-25/tests/15_unsteady_and_transport/test_results/flow_trans_implicit.con.1/profiler_info_15.07.24_10-13-54.log.json))
```json
      "tag": "Whole Program",
      "file-path": "/src/system/sys_profiler.cc",
      "file-line": 194,
      "function": "Profiler",
      "call-count": 1,
      "call-count-min": 1,
      "call-count-max": 1,
      "call-count-sum": 1,
      "cumul-time": 0.032422167,
      "cumul-time-min": 0.032422167,
      "cumul-time-max": 0.032422167,
      "cumul-time-sum": 0.032422167,
      "percent": 100,
```
**Paralel example output** ([link to file] (http://hybs.nti.tul.cz/flow-collector-arts/2015-07-24_11-11-25/tests/15_unsteady_and_transport/test_results/flow_trans_implicit.con.2/profiler_info_15.07.24_10-14-17.log.json))
```json
      "tag": "Whole Program",
      "file-path": "/src/system/sys_profiler.cc",
      "file-line": 194,
      "function": "Profiler",
      "call-count": 1,
      "call-count-min": 0,
      "call-count-max": 0,
      "call-count-sum": 0,
      "cumul-time": 0.028042824,
      "cumul-time-min": 0.000000000,
      "cumul-time-max": 0.000000000,
      "cumul-time-sum": 0.000000000,
      "percent": 0,
```

**Comment by x3mSpeedy** [comment]
Same test executed again possess **meaningful values** ([link to file](http://hybs.nti.tul.cz/flow-collector-arts/2015-07-24_11-39-08/tests/15_unsteady_and_transport/test_results/flow_trans_implicit.con.2/profiler_info_15.07.24_11-38-31.log.json)) could be fluke.

**Comment by jbrezmorf** [comment]
can not reproduce.
