### ISSUE TITLE
Python-markdown parser bug does not process "<" in html-doc

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#419]
In documentation, string like "(($q<0$))" or "(($q\\\\<0$))" is not processed properly when invoking "make html-doc". Target "ref-doc" works OK.

**Comment by x3mSpeedy** [comment]
Ad 1) ```(($q<0$))``` should be fixed now. New version of ```main.js``` will be downloaded upon html-doc call.
Ad 2) ```(($q\<0$))``` Is it valid expression? HTML documentation uses KaTeX library. Maybe some expressions are not implemented yet. @jstebel can you test it [here](https://khan.github.io/KaTeX/) (no need to surround expressions with ```(($``` on that site)

**Comment by jstebel** [comment]
Ad  2) Indeed, \< is not valid LaTeX tag. Otherwise I would appreciate text formatting with \boldsymbol and \mathbb.

**Comment by jstebel** [comment]
Another bug: In pdf manual the underscore is escaped both in text and math mode, so lower indices like (($q_w$)) do not work.

**Comment by x3mSpeedy** [comment]
Javascript rendering engine added support for **bold** fonts. So expression 
```tex
$nobold\space \bold{bold}$
```
will look like this:
![image](https://cloud.githubusercontent.com/assets/894428/12946926/22f7f144-cff8-11e5-92eb-a8d7504dae75.png)

Issue with underscore should also be fixed now.
