### ISSUE TITLE
Documentation, numerical topics of reaction classes

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#42]

**Comment by jstebel** [comment]
Should we document 1st order reactions and decays? (update and include file decay.tex)

**Comment by Paulie14** [comment]
Following the JS_numerical_doc, I added 1st order reactions and decays and its numerical topics, in
PE_doc. Finished by 34cfd6967b0c937871d56df9c404b9c9c1674cfa.
Can merge into 1.8.0_master after reviewing..
