### ISSUE TITLE
Add version into HTML and Latex doc

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#420]
Prerequisity: #415 

Report in HTML documentation version of the flow123d,
In latex export version through definition of Latex macros (then can be placed e.g. to header or footer)

**Comment by jbrezmorf** [comment]
Both done.
HTML improvements:
- [ ] support of @VERSION@ placeholder in the main html template
- [ ] html-doc target should copy logo image(s) from doc/graphics
- [ ] put logo + version into gray header
- [ ] replace TUL icon of the page by Flow icon

**Comment by jbrezmorf** [comment]
@janhybs Please, fix the formating of HTML doc, see published version 2.2.0:
http://flow.nti.tul.cz/packages/2.2.0_release/htmldoc/

Need to fix scaling and style of the logo and "ver 2.2.0" which is currently white.  
Fix template used by generating scripts,

**Comment by janhybs** [comment]
Should be fixed now, but everything needs to be rebuilded. Also oepned new issue #919 which, for now is not that important but may affect htmldoc in the future.

**Comment by jbrezmorf** [comment]
Better. Yet, few points to improve to have this page done:
- split whole page into two columns, left white, right with current gray heading
- have Flow123d logo at the top of the left column
- remove gap above the list of types 
- have version at the gray heading on the right, 
- move "Generated ..." to the right column, keep vertical position just move it under version

**Comment by janhybs** [comment]
So fat it looks, like this:
![image](https://user-images.githubusercontent.com/894428/35779855-c0fb6dbc-09cb-11e8-8698-69761fcef88f.png)

Unfortunately I can't really picture no `1)` (and I suppose related `2)`)

**Comment by jbrezmorf** [comment]
How it looks for me:
![screenshot_20180205_090802](https://user-images.githubusercontent.com/326204/35794023-450e85a2-0a54-11e8-9cca-0e435c9fe16e.png)

**Comment by jbrezmorf** [comment]
The idea of 1) is to split heading in the same way as the content. Having left column with list of types all white with Flow logo at the top and current heading (grey strip and hline) used just for the right column.
So the "Generated ..." will be in the right column aligned to the left.

However, other approaches to less messy layout are welcome.

**Comment by janhybs** [comment]
@jbrezmorf, it should be done. It was quite a challenge, but I've made the changes. Currently It looks like this [[live demo](http://hybs.nti.tul.cz/ist/)]:
![image](https://user-images.githubusercontent.com/894428/35810523-f1b49e16-0a83-11e8-89a4-765152f61fe1.png)
Changes were made to the Flow123d-htmldoc repo flow123d/Flow123d-htmldoc@6bc6f3658f7d66ade51d3ecc99b1e4c9567f2166
as well as to the html template file 5b1d669734a7e8cdfb394d4308a6e59d58d5dff4

Also changed favicon: 
![image](https://user-images.githubusercontent.com/894428/35810820-d74a9fde-0a84-11e8-8633-5e5e51eb9724.png)

**Comment by jbrezmorf** [comment]
Much better. Some misunderstanding on the way, so postpone it to a Skype session or so.

**Comment by jbrezmorf** [comment]
Done for version 2.2.0.

**Comment by janhybs** [comment]
The [newest version](https://flow.nti.tul.cz/packages/3.0.1_dev/htmldoc/) offers many visual and practical improvements. I believe the issue can be closed now.

**Comment by jbrezmorf** [comment]
Sure.
