### ISSUE TITLE
Finish non-compatible intersections.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#427]
- [ ] Comment out or remove unnecessary code. Use DBGMSG for essential debugging mesages. (VF)
- [ ] Comment classes, data and methods in header files. (VF)
- [ ] Merge ReferenceElement and RefSimplex. (PE)
- [ ] Go through whole source, propose enhancements, safety, readability. (PE, VF)
- [ ] Propose modifications to allow also computing 1d-2d and 2d-2d intersections in 3d.

**Comment by Paulie14** [comment]
Is included in #448.
