### ISSUE TITLE
Simplify Balance constructor

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#432]
Use native partitioning of the mesh in the constructor no need to pass ds_el, and el_4_loc. 
Small improve of Partitioning necessary.
Do not store redundant vector be_regions_, just pass trough the mesh in allocate() method or some auxiliary_method.

**Comment by jstebel** [comment]
Ad partitioning: If el_ds and el_4_loc are the same for all equations, should we store them directly in mesh?

Ad be_regions_: I don't think it is so simple. The mapping from number of local boundary edge to its boundary region is needed in Balance::calculate_flux(). Passing through all edges in this method would be too expensive as the number of boundary edges is usually much smaller.

**Comment by jbrezmorf** [comment]
Ad partitioning: I agree, the parallel mesh in future should provide this kind of data in some way.
Ad be_regions_: OK. I didn't find the usage in calculate_flux.
