### ISSUE TITLE
Executing tests with absolute paths causes File not found error

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#447]
During testing, if flow123d binary is called and flag ```-i``` contains other value than ```input``` some tests will fail due to error, where two absolute paths are glued together:
```bash
Can not open input file '/home/jan-hybs/Documents/Flow123d/flow123d/tests/01_steady_flow_123d//home/jan-hybs/Documents/Flow123d/flow123d/tests/01_steady_flow_123d/input/test1_new_fbc.fbc
```
This only happens when **con** file contains placeholder **```${INPUT}```** (so easy solution would be to remove these placeholders), **con** file example:
```yaml
  { region = "3d_cube",
    anisotropy = 0.1
  },
  { region="IMPLICIT BOUNDARY",
    flow_old_bcd_file="${INPUT}/test1_new_fbc.fbc"
  }
```
It appears that path of file starts with prefix of test dir. Command which causes error (current working dir is irrelevant):
```bash
/home/jan-hybs/Documents/Flow123d/flow123d/build_tree/bin/mpiexec -np 1
/home/jan-hybs/Documents/Flow123d/flow123d/build_tree/bin/flow123d 
-s /home/jan-hybs/Documents/Flow123d/flow123d/tests/01_steady_flow_123d/flow_vtk_fbc.con 
-i /home/jan-hybs/Documents/Flow123d/flow123d/tests/01_steady_flow_123d/input 
-o /home/jan-hybs/Documents/Flow123d/flow123d/tests/01_steady_flow_123d/output

```

**Comment by jbrezmorf** [comment]
There is clear bug in the constructor of FilePath:
For the input file type we should:
1) substitute_variables
2) for relative paths prepend  root_dir, for absolute paths do nothing

We should have an unit test for FilePath to test all cases of input/output files relative/absolute with or without substitution.
