### ISSUE TITLE
Finalize non-compatible intersections

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#448]
Viktor Fris:
- [x] Complete comments of all classes and methods. Document: input, output, purpose (namely for classes), use english
- [x] clean-up of `inspect_elements.hh/cc`
- [x] move code in IntersectionLocal into IntersectionPoint (see comments there)
- [x] Declare ProlongationLine and ProlongationPoint as mere struct. Distinguish two kinds of prolongation.
- [x] Convert ``to_string` methods into overloaded << operator.
- [x] Optimize allocation of products: only one allocation in the highest CI object, use just indexes into that main vector in lower CI objects
  to operate on the subset of products. 

Pavel Exener:
- [x] Merge ReferenceElement class form mesh/intersections/ref_element.hh a mesh/ref_element.hh
- [x] Unit tests: 
  - various intersections  line-tetrahedron, all possible outcomes, at least some special cases
  - various intersections triangle-tetrahedron, all possible outcomes, at least some special cases
  - test every permutation of nodes of input elements
  - pay attention to coverage of the intersection code by unit tests
- [x] Various minor enhancements through the code.
- [x] Audit of the implementation, for no code dependent on the internals of the reference element, in particular numbering and orientation of sides, edges, nodes.
- [x] Audit for usage of various epsilon tolerances. Target:
  - correctly find all intersections of non-zero measure of the lower dimension, compute local coordinates to a reasonable precision given by double calculations
  - possibility to find also intersections of zero measure
  - Do not look for "almost" intersections. If really necessary is better to enlarge lower dimension object and look for true intersection.
- [ ] Prepare classes to:
  - overtake role of ngh in computation of 2d-1d intersections
  - search for 2d-2d, 2d-1d intersections in 3d
- [x] Find bug in tracing and prolongation routines for nonfunctional meshes in the unit test

**Comment by Paulie14** [comment]
Replacing toString methods finished by 4d9fcab.

**Comment by Paulie14** [comment]
Comments on current state:
Issue #473 was done as prerequisite.
Issue #474 suggested for intersection point improvements.
Finalize #467 unit testing of intersections.

**Comment by Paulie14** [comment]
Notes before merging:
- intersection classes are in 'computeintersection' namespace;  but in old ngh the classes are not in namespace and some have same names, so it does not allow us to write 'using computeintersection'
- selection of algorithm (BIHsearch,BBsearch,BIHonly) is hardcoded in inspectelements - how better would we like to make this decision ?

**Comment by Paulie14** [comment]
ad notes: the last two are done

**Comment by jbrezmorf** [comment]
Some notes what we should finish after the paper:
- [ ] Finish and test robust tracing algorithm for 2d-3d case in branch JB_intersections. This also includes some changes in RefElement
- [ ] Add functionality in RefElement for get local index of an edge of a side, etc.
- [ ] How to iterate sides of triangle of RefElement in cyclic order and cyclic orientation?
- [ ] Reuse CI objects in mesh intersection algorithm in order to reduce number of allocations
- [ ] Review 1d-2d degenerate intersection algorithm
- [ ] Eliminate Simplex<> clases as the intersection algorithms work only with plucker coordinates and RefElement.
- [ ] Eliminate duplicate code for final intersections (1d-2d, 1d-3d) have separate method to finish an intersection object or store the intersection in  th CI itself. A fixed (maximum) size of the Intersection may be allocated.

**Comment by Paulie14** [comment]
I would move your note to the actual issue #690, so we have it at one place...
