### ISSUE TITLE
Incorrect dependencies in the main makefile

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#450]
Rules in the main makefile have not specified full set of dependencies (for example everything should depend on make_build_tree).
This cause errors when running whole build in parallel, e.g.
make -j 4 all

Workaround is to build target 'cmake' in sequential and then run in parallel:
make cmake
make -j 4 all

The problem is that most of rules are PHONY rules and this is the simplest way how to make them run only once.
TODO:
Fix dependency, at lest make_build_tree could be just regular rule 'build_tree'. Study documentation of the make 
to prevent reevaluation of PHONY rules or replace them by regular rules.

**Comment by x3mSpeedy** [comment]
Dependencies should be fixed via 8454ed68c3536408ae2814d28d06db67b7a42abd 
I've done clean ```git clone``` and ```make -j 4 all``` (with paralel options) and project was build without error.

I added more comments on targets and add one more target which groups ```install-hooks```, ```build_tree```,  and ```update-submodules```together.

**Comment by jbrezmorf** [comment]
Should be fixed by smaller change. Merged in b2f28af9
