### ISSUE TITLE
Redundant warning when reading elementwise field

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#452]
See files at bacula/.../jan.stebel/00_share/flow123d_issues/#452.
When reading initial condition for pressure, this warning appears:

Warning (/home/stebel/dev/git/flow123d/src/system/tokenizer.cc, next_line(), 74):
Remaining tokens, file '././input/hydraulic.msh', line '99382', after token #1.

It seems that there is no reason to complain, but it should be checked. The method Tokenizer::next_line() is called from GmshMeshReader::get_element_data().

**Comment by jbrezmorf** [comment]
Look into the input file on particular line, there should be some remaining token. Wrong line ending?

**Comment by jbrezmorf** [comment]
The problematic line is last line of the header of a data block. Seems that possibly the file iterator in the header_table points to wrong line.

**Comment by jbrezmorf** [comment]
Fixed Tokenizer::set_position, which did not reset the line tokenizer after setting new position.

**Comment by jbrezmorf** [comment]
Fixed in #dae1035
