### ISSUE TITLE
Prepare tests for creating transformation rules

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#456]
- [x] Add transformation script into repository.
- [x] Create (empty) main file with transformation rules.
- [x] into ```bin/``` add simple python script that use the main transformation file.
- [x] Make a script that apply transformation to all test con files. 
- [x] Apply this script with empty transformation rules. Fix some CON files with complex references.
- [x] change the test scripts and change ref_output subdirs to not contain suffix.
- [x] Make all tests run on YAML files.

**Comment by jstebel** [comment]
Questions:
- Should be done in master or in what branch?
- The script has dependencies so that a large part of the GeoMop repository has to be added. This can be done either manually or using some script that downloads the files from github or by submodule. Any preference?

**Comment by jbrezmorf** [comment]
- in a branch derived from master.
- Finally, the script and its dependencies should be part of Flow123d repository. However, as the converter  is not fully stabilized yet, it may be simpler to 
use submodule temporary and take advantage of immediate access to fixes.
