### ISSUE TITLE
use std::regexp

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#465]
Remove or minimise dependence on BOOST replace by std library.
Support both, prefer std::regexp if available.

**Comment by jbrezmorf** [comment]
Since we use regexp. We depend on boost at least until gcc 4.9 (which fix buggy std regexp implementation, released in 2014) becomes standard, say in 2017? However, RHEL and CentOS will support that versions probably around 2018.

**Comment by dflanderka** [comment]
Done in version 2.2.0, commits 2b113ab and 11cd79c (merged in pull #903).
