### ISSUE TITLE
Optimize release builds

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#466]
Mostly moved to issue #740 
- Get size of installation before packaging and report that in the package json file.

**Comment by jbrezmorf** [comment]
related to #740

**Comment by janhybs** [comment]
A size of an flow123d package is available online and can be at the bottom of the page (17.6 MB) [here](https://microbadger.com/images/flow123d/3.0.1)

**Comment by jbrezmorf** [comment]
This issue is very old, before introduction of docker. However the point was to have an information about the size of the build which was closely related to the space needed for the installation. This is not true any more with docker as the major part are dependencies.
