### ISSUE TITLE
Unit tests in intersections

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#467]
Unit tests:
- find out, why some of the test meshes fail in polygon tracking
-    various intersections line-tetrahedron, all possible outcomes, at least some special cases
-    various intersections triangle-tetrahedron, all possible outcomes, at least some special cases
-    test every permutation of nodes of input elements
-    pay attention to coverage of the intersection code by unit tests

**Comment by Paulie14** [comment]
bug solved in 0fc14885224bf9ef0b096186bafb947046f972b6
the problem was a wrong normal of a tetrahedron side in polygon tracing

**Comment by Paulie14** [comment]
testing intersections line-tetrahedron done by commit 70967d2bdf4f93b8905ba4034ee2188bfa31c6c2
- various situations, including all possible pathologic cases
- test for every permutation of tetrahedron
- compare with analytically computed intersection coordinates

**Comment by Paulie14** [comment]
tests for 1d-2d done by commit 6a2a3594eea0130ae5b938ff79aa85ffb5d18299

**Comment by jbrezmorf** [comment]
Make new issue for remaining and mark done this one.

**Comment by Paulie14** [comment]
2d-2d permutations solved by commit 17e3778.
Closing and moving the rest to issue #690.
