### ISSUE TITLE
Mesh reader for NetGen

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#470]
- [  ] Which mesh output formats are supported by NetGen?
- [ ] Which one is supported by other tools (mesh generators, ParView, FeFlow, etc. )?
- [ ] Which is well documented?
- [ ] Which have C++ reader?
- [ ] How to deal with elementwise input fields or output fields?
- [ ] Implement reader for Flow123d.

**Comment by jstebel** [comment]
See also #558.

**Comment by jbrezmorf** [comment]
NetGen abandoned in BGEM, so no motivation to support it.
