### ISSUE TITLE
Template interface for topology data in reference element.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#473]
Create function template for interfacing the topology information of reference element.
Get rid of the public arrays side_lines, line_nodes etc..

**Comment by Paulie14** [comment]
Suggested in commit 52a39fc

Note:
The actual call looks like `RefElement<3>::interact<0,1>(i)[j]`
but in templated code like

    template<unsigned int dim> void func{
        RefElement<dim>::template interact<0,1>(i)[j];
    }

could be a little bit annoying with the `template` word..

What do you think, is it ok?

**Comment by jbrezmorf** [comment]
I see no way to make it simpler. Hopefully, we will use it only in the library part of Flow123d.

**Comment by Paulie14** [comment]
Done in eded54361a5c0af8204eba5940f26ab9456f809e.
The solution is not absolutely general, but it provides a uniform interface to topology data.
Further improvements involve generalizing the topology data arrays which are now successfully hidden private and it should not change the interface in future.

**Comment by jbrezmorf** [comment]
Need careful merge into master.

**Comment by Paulie14** [comment]
Is solved also in #359.
