### ISSUE TITLE
Intersections - unify epsilon tolerances

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#483]
Audit for usage of various epsilon tolerances. Target:
- correctly find all intersections of non-zero measure of the lower dimension, compute local coordinates to a reasonable precision given by double calculations
- possibility to find also intersections of zero measure
- Do not look for "almost" intersections. If really necessary is better to enlarge lower dimension object and look for true intersection.

**Comment by Paulie14** [comment]
Question: Do we need two types of tolerances, let's say rounding error and geometry tolerance?
Usage:
- Plucker products are compared with zero - use rounding error tolerance.
- Test line parameter around 0 and 1, to test end point - geometry tolerance (what is and is not IP??)
This is connected with "Do not look for "almost" intersections." So, if a point is in distance less than (reasonably chosen) geometry epsilon, it wil be IP?

Note: there is another tolerance in IntersectionPoint::operator<, which is used in convex hull tracing and which I do not really understand..

**Comment by jbrezmorf** [comment]
Concerning the issue:
Table of dimensions of the intersections we are interested in for various input dimensions:
input dim            intersections dim
3,2				2
3,1				1
2,2				1
2,1				1,0

So in the last case we are looking also for zero measure intersections in the dimension of the lower object.

I think that we can drop any intersections of other dimensions from the final result, but possibly these may be important for the prolongation algorithm to work. As an example consider a triangle with one side touching a face of an tetrahedron, if we do not inspect their intersection we (possibly) miss intersection of the neighbouring triangle.

"Almost" intersections are just rubbish, but introducing tolerances I wonder if we can completely avoid them.

**Comment by jbrezmorf** [comment]
I think that tolerances around line ends are just for rounding issue. However, its possible that this tolerance
should be larger since the coordinates of IP results from longer calculation. 
Note, that the error is not only error of the calculations but also error of the input coordinates. So in fact the toleraces should be set relative to a given tolerance of the input coordinates. And the later one may be set on  the input.

**Comment by Paulie14** [comment]
Can be closed, moved to #690.
