### ISSUE TITLE
Make input transform rules for existing changes

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#485]
Compare IST of 1.8.2 and IST of master before changes in the input structure.

Every change of the test  CON files made since version 1.8.2
has to be reverted and replaced by appropriate transformation rules.

List of commits that made changes in CON files:
09375 - ef86e1 - implementation of total_flux BC in transport_DG, consult with Jan Stebel if this only add new functionality. It seems so from the changes.

**Comment by jstebel** [comment]
Total flux b.c. is indeed a new functionality. The original 'neumann' now corresponds to 'diffusive_flux'.
