### ISSUE TITLE
Invalid input reference json file

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#507]
When generating input reference ```json``` using flow123d binary:
```bash
$> ./flow123d --JSON_machine input_reference.json 
```

When formatting default value in keys of ```Record``` type ```json``` looks like this
```json
"default": {
    "type": "obligatory",
    "value": OBLIGATORY
},
```

but should look like this (notice **"**)
```json
"default": {
    "type": "obligatory",
    "value": "OBLIGATORY"
},
```
Suspect is probably ```Default``` class in [type_record](https://github.com/flow123d/flow123d/blob/master/src/input/type_record.hh#L49)

**Comment by x3mSpeedy** [comment]
Another problem with default values @jbrezmorf . String values in `value` do not replace newlines with `\\n`. Example: 
```json
"default" : {
    "type" : "value at read time",
    "value" : "List containing the initial time of the equation. 
 You can prescribe an empty list to override this behavior." },
    "type" : "ae4d15413e119e57"
},
```
Value of `value` is multiline, which is no valid in json. Correct format is:
```json
"default" : {
    "type" : "value at read time",
    "value" : "List containing the initial time of the equation.\nYou can prescribe an empty list to override this behavior." },
    "type" : "ae4d15413e119e57"
},
```
There is need for something like in [type_output.cc](https://github.com/flow123d/flow123d/blob/9780c0eb6e2dbbbc78060c2db56409b390995150/src/input/type_output.cc#L433)

**Comment by jbrezmorf** [comment]
- default values fixed
- newlines fixed
