### ISSUE TITLE
Fix region_fields_ in copy constructor of Field

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#534]
Currently the copy constructor only resizes the vector region_fields_ and does not copy the pointers from the origin. This prevents e.g. using value() or is_constant() on the new object. The problem will appear e.g. in the following code:

vector<Field> vec;
for (auto field : vec) if (field.is_constant(region)) do_something;

since field.region_fields_ is a vector of null pointers. The problem can be avoided using reference:

for (auto & field : vec) ...

but a more error-prone solution is desirable.

**Comment by jbrezmorf** [comment]
- [ ] check where the copy constructor is actually used (comment it out)
- [ ] If it is really usefull, ... either fix it to be really copy, or convert it to an method.

**Comment by jbrezmorf** [comment]
Just add  = delete; to be sure that default constructor is not involved.

**Comment by jbrezmorf** [comment]
Done in pull #546
