### ISSUE TITLE
Under surface depth

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#538]
Introduce a parameter D into FieldFormula, taking the distance of the point to the surface. 
Two other (optional) keys must be added into FeildFormula record:

surface_direction (default [0,0,-1]) the vector used to project evaluation point onto the surface
surface_region - the name of region set considered as the surface. If there are more intersection points the closest one is used.
max_depth - If no intersection is found, we use this value. By default we use 

Implementation should use an array storing the depth of the center of every element. And reusing this information in further evaluations.

Implementace: BIH tree pro XY projekce povrchovych elementu, 
Pro dany xy,z bod najit povrchovy element -> spocitat projekci bodu na povrch. Pomale pokud bychom to provadeli pro kazdy kvadraturni bod zvlast. Bylo by vhodne mit pro to cache nebo to napocitat do FieldFE. S tim souvisi moznost pouzit ve FieldFormula nejake jine Field, asi mozne pokud budeme mit FiedlValueCache

**Comment by jbrezmorf** [comment]
Implementation in own class SurfaceDepth.
1. Have this object separately in every FieldFormula. Precompute the BIH tree for surface elements, but evaluate projection for every quadrature point independently (no precomputing)
2. ... possible optimizations

**Comment by jbrezmorf** [comment]
Nemyslim, ze je potreba konstruovat celou submesh, staci do BIH Tree pridat jen hranicni elementy z vybranych regionu.
Zavislost BIHTree na Mesh je zbytecna, podivej se na

https://github.com/flow123d/bih/blob/master/src/bih_tree.cc

Zde jsem tu tridu exportoval do samostatneho projektu s Pythonim rozhranim, bylo by fajn to ve Flow123d mit stejne.

**Comment by jbrezmorf** [comment]
Co se tyce projekce:
Je zadany vektor N, ten se vydeli velikosti, aby byl jednotkovej a vytvori se bazove vektory pro kolmou plochu:

Ex = (1,0,0), Ey=(0,1,0)
Ta = Ex - (Ex . N) N
Ta = Ta / |Ta|
Tb = Ey - (Ey . N) N - (Ex . Ta) Ta
Tb = Tb/|Tb|

Udela se matice M s vektory Ta a Tb v radcich.

Libovolny 3d bod P se pak projektuje do souradnic (a,b) v rovine kolme k N, prenasobenim tou matici:

(a,b) = M . P

Takto je potreba zprojektovat vrcholy tech hranicnich elementu a pak teprv pro ne delat bounding boxy a BIH Tree.
Pak kdy budu vyhodnocovat FieldFormula v bode P, tak ho nejdriv zprojektuju do roviny a bude se testovat jestli projekce lezi v bounding boxu nejakych hranicnich trojuhelniku.

Pro kandidatni trojuhelniky T se pak bude pocitat prusecik T a primky skrz bod P ve smeru N.

**Comment by jbrezmorf** [comment]
Prunik Trojuhelnika s vrcholy V0, V1, V2:

Va = V1 - V0
Vb = V2 - V0
Matice A se sloupci Va, Vb, N, vektor B=P-V0.
Resi se soustava 3x3:
Ax = B
 vektor x = (a,b,t)

(a,b) musí být >0 a a+b< 1, pak existuje průsečík 
X = V0 + a Va + b Vb

A spocte se vzdálenost |X - P|.

**Comment by jbrezmorf** [comment]
Use a dedecated class for representing projection of points to given surface. This should keep a vector of extracted surface elements of the surface. We assume only elements from Mesh.bc_elements, this can be extended once we have a single indexing for all element types in the Mesh.  The bounding boxes in the BIH tree will have same order.

**Comment by jbrezmorf** [comment]
Optimization:
Speed test results:
FieldConstant    0.12
FieldFormulaSimple    0.63
FieldFormulaFullExpr  1.1
FieldFormulaDepth      18.1
FieldFormulaDepth (bez projekce bodu): 13.6

Conclusion, FieldFormulaDepth:
   - expr evaluation: 0.6
   - bih::find_point: 13
   - bih point projection: 4.5

Optimisation tips:
- avoid allocations in find_point (merge from master)
- avoid other allocations
- use Armor for storinge in BIH and in SurfaceDepth
- better precalculations

**Comment by jbrezmorf** [comment]
Results for commit  5f5839d:
Optimization:
Speed test results:
FieldConstant    0.12
FieldFormulaSimple    0.61
FieldFormulaFullExpr  1.1
FieldFormulaDepth      9.0
FieldFormulaDepth (bez projekce bodu): 2.5

Conclusion, FieldFormulaDepth:
   - expr evaluation: 0.6
   - bih::find_point: 2
   - bih point projection: 6.5

**Comment by jbrezmorf** [comment]
possible improvements in point projection:
- zjistit duvod zpomaleni v projekci: volani funkce, velke mnozstivi neuspesnych projekci?
- predpocitat inverzi projekcni matice (2x3, first 2 rows of 3x3 inversion matrix to a_mat)

**Comment by dflanderka** [comment]
Merged in dc7e0db
