### ISSUE TITLE
Binary VTK output

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#544]
- [x] change current implementation to use method write_vtk_data_ascii to output all data vectors (even for mesh geometry and topology), i.e. output of XML tag DataArray should be done only through this method
- this needs output of mesh points and connectivity into OutputDataFields. 
- [x] change name and implementation of write_vtk_data_ascii to support append data format.
- [x] add ZLib 
- [x] add support for compressed VTK data

**Comment by jbrezmorf** [comment]
partially done. wait for merge after the test changes

**Comment by jbrezmorf** [comment]
@x3mSpeedy : need to add 'lib32z1-dev' pacakge into devel image and 'lib32z1' into package image (i.e. image that is used as base for flow123d package).

**Comment by x3mSpeedy** [comment]
Added `lib32z1` and `lib32z1-dev` to appropriate DockerFiles in https://github.com/flow123d/docker-config/commit/29b3787a11642bc9b4e3cad8d4631e44d09b73e8

**Comment by jbrezmorf** [comment]
Closed by a68b282d1
