### ISSUE TITLE
FieldFE IO and VTK reader

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#545]
Implement reader for VTK data for a mesh compatible with the computational mesh.

TODO before merge:
- revert "gmsh_file" rename
- add an integral test, test that VTK files are read just in the correct time provided in corresponding field descriptor; possibly extend test 02/03.

TODO:
- [ ] rename "gmsh_file" to "mesh_data_file" in FieldElementwise and FieldInterpolated ...
- [x] Implement an API in Mesh to add nodes and elements in general mesh reader. In mesh make methods for creating single Node, Element and passing Physical Names table
- [x] Move gmsh read into IO.
- [x] Make common Base class for data and mesh readers. 
- [x] Make current GMSH and VTK readers derived from the common base, possibly reducing duplicities.
- [x] Unify ElementDataCache with OutputData, can be part of previous item.
- [x] Simplify common reader interface.
- [x] In Mesh make getter for `node_elements` which calls `create_node_element_lists` if necessary.
- [ ] implement PVD reader, and support for time dependent VTK data

**Notes on using OutputData**
- I propose to replace both OutputData and ElementCacheData by IOData<T>, where T is just
  double, int or uint, size of stored vectors will be runtime variables.
- OutputData get FieldCommon in constructor just to retrieve name units (just string) and Value, 
  we can pass the Value shape as a parameters and set name and units through setters after construction.
- OutputData use FieldValue as the template parameter, this is not necessary, constructor use it to get shape of values and operate method use it to access stored values, this only has to be changed.
- OutputData (both for reading and writing) contains values in input/output units, so the conversion takes place on Fields side of OutputData access. Thus we need not to pass Units object to IO just string of units.

**Comment by jbrezmorf** [comment]
prerequisity for #680

**Comment by jbrezmorf** [comment]
Take the last (temporary) approach.
- [ ] Implement a reader of VTK files. Try to detect map from the nodes and elements of the VTK mesh to the current mesh. Use these later to read field data.
- [ ] Add our own XML tags to indicate FE type.
- [ ] Check that a DOF handler match field type in VTK file.
- [ ] If yes read the data into the vector.
- [ ] Implement interpolations between FE types.

**Comment by jbrezmorf** [comment]
**Notes on using OutputData**

- I propose to replace both OutputData and ElementCacheData by IOData<T>, where T is just
  double, int or uint, size of stored vectors will be runtime variables.
- OutputData get FieldCommon in constructor just to retrieve name units and Value, 
  we can pass the Value shape as a parameters and set name and units through setters after construction.
- OutputData use FieldValue as the template parameter, this is not necessary, constructor use it to get shape of values and operate method use it to access stored values, this only has to be changed.

**Comment by dflanderka** [comment]
Ok, but we have one more problem. ElementDataCache is used by readers which are in mesh library now. Moving ElementDataCache to IO directory will cause that readers won't see to ElementDataCache.

Solution: We will have to split readers according to an earlier proposal and move part for reading element data to IO. Is it OK?
