### ISSUE TITLE
CFL for reactions

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#552]
- demonstrate numerical instability of current implementation
- compute CFL for reactions and limit the time step or (better) use shorter time steps per element to avoid instability
- the implicit schemes for the reactions should be OK
- discuss this in documentation

**Comment by jstebel** [comment]
Dual porosity: Write down the condition for stability of explicit Euler method for the system of ODEs. This should give explicit upper bound for the time step. If the condition is not satisfied then use analytic solution.

**Comment by jstebel** [comment]
See detailed overview at https://docs.google.com/document/d/1nlOWnmbB8mVaR7KsfLB0O1BW8YyJ1aQgATArw0pU1-0/edit?usp=sharing
