### ISSUE TITLE
split jenkins config file

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#573]
- [x] make separate directory for jenkins configuration (possibly in ROOT/config)
- [x] move there associated cmake rules
- [x] split the YAML file into separate files for: 
	- debug, release jobs
	- coverage jobs
	- package test jobs

**Comment by x3mSpeedy** [comment]
**Ad 1)** structure looks like [this](https://github.com/jbrezmorf/flow123d/tree/JHy_docker/config/jenkins-job):
<details>
  <summary>Structure below</summary>
  ```/config/jenkins-job/
├── expand_placeholders.cmake
├── jenkins.ini.template
├── jobs
│   ├── debug.yaml.template
│   ├── ...
│   └── main.yaml.template
├── makefile
├── test_list
└── unit_list
```
</details>

**Ad 2)** added [makefile](https://github.com/jbrezmorf/flow123d/blob/JHy_docker/config/jenkins-job/makefile) with following targets:
<details>
  <summary>makefile help:</summary>
  ```
Usage:
    - test:   expands placeholders and tests configuration without
              upload and prints result xml

    - upload: expands placeholders and uploads configuration to server
              by default jenkins.ini is used.
              You can override this behaviour by specifying variable
              CONFIG in make step, example:
              make CONFIG=foo.ini upload

    - expand: expands placeholders in all files located in jobs folder
              ending with .yaml.template. This action will preserve originals
              and created new files where suffix .template will be removed
              main.yaml.template -> main.yaml

    - delete: *** deletes all jobs from server ***
              this action cannot be undone

    - help:   print this message
```
</details>

**Ad 3)** So far debug yaml is done

**Ad 4)** This is already supported by jenkins-job-builder (option `delete-all`). Or you mean something different?

<details>
  <summary>jenkins-jobs usage</summary>
```
usage: jenkins-jobs [-h] [--conf CONF] [-l LOG_LEVEL] [--ignore-cache]
                    [--flush-cache] [--version] [--allow-empty-variables]
                    {update,test,delete,delete-all} ...
```
</details>

**Comment by jbrezmorf** [comment]
ad 4. I know, but that removes definition of the jobs not their build files and directories. However the groovy script is not necessary any more:
- slow Jenkins was due to ipv6 or something rotten in TUL network

This was an old issue, that you have almost done.

**Comment by jbrezmorf** [comment]
done during transition to the new build system under docker
merge in fa265ae
