### ISSUE TITLE
Propagate exception messages

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#590]
When one exception is catched and other exception suited to particular context is throwed instead we want to keep message provided by the previous exception in order to better understand reason.

To asi bude dlouhodobe reseni, zde mame pripad, kde vyjimku trikrat
odchytime a pokazde by bylo vhodne vyhodit novou vyjimku spolu s
informaci o puvodni vyjimce. Takze by kazda vyjimka mohla mit
EI_previous, tam by se pri vyhazovani mohla pridat what message:

```
try {
} catch (ExcA &e) {
	THROW(ExcB() << EI_previous(e.what());
}
```
EI_previous by se vypsalo pouze v ramci Diagnostic info a tim padem jen
v logu.

**Comment by dflanderka** [comment]
Use EI_previous in ExcWrongDefault and ExcWrongDefault exceptions.

**Comment by jbrezmorf** [comment]
Takze to udelame trochu sloziteji, ale prehledny vystup:

```
-----------------
Error message
-----------------
** Stack trace **
...
** Diagnosting info **
...
===============
Nested exception:
---------------------
Error message
-----------------
** Stack trace **
...
** Diagnosting info **
...
```

Tento vystup bude realizovat metoda what() nasledovne:
1.  EI_Previous prejmenujeme na EI_Nested a definujeme podobně jako boost::errinfo_nested_exception
    tj. nebude to obsahovat retezec ale ukazatel na vnorenou vyjimku. Tímto bude v diagnosting info pouze ukazatel.
2. Použití bude:
catch ( ExcXYZ &e ) {
  THROW( ExcNew() << EI_Nested( &e );
}
3. what() bude obsahovat cyklus, kde na začátku bude nastaven pointer na aktuální vyjímku, dokud je pointer nenulový, vypíše podmínku (err message, stack, diagnostic info) a pokusí se přečíst EI_Nested (boost::get_error_info<EI_Nested>(exc), to navratí NULL pokud u nested exception neexistuje a tím se what() ukončí.

**Comment by jbrezmorf** [comment]
boost::get_error_info<EI_Nested>(exc) is wrong since EI_Nested is not the boost error_info type
Try:

- EI_Nested::ptr(exc)
- boost::get_error_info<EI_Nested::ErrorInfo>(exc)

**Comment by jbrezmorf** [comment]
In order to propagate the exception safely we should make our own copy and pass shared pointer. To this end we may add the template function:

	template <class Exc>	
	EI_Nested make_exception_ei(Exc &e) {
		return std::make_shared<Exc>(e);
	}

**Comment by jbrezmorf** [comment]
resolved in merge 3a24f4e275
