### ISSUE TITLE
Check CFL condition

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#592]
Check that Melechov benchmark problem with convection transport leads to same time step in 1.8.3 and 2.0.0 versions. It seems that the new version leads to much smaller timestep, which cause too long run time.

**Comment by jstebel** [comment]
Where can I find the benchmark data?

**Comment by jbrezmorf** [comment]
Pease, ask Honza Hybs.

**Comment by jstebel** [comment]
The problem was in the data files, not in Flow123d code.

The input files use old BCD format for flow boundary conditions, therefore in versio 2 Flow123d ignored them and computed wrong velocity field which then led to wrong CFL constraint.
