### ISSUE TITLE
Fix Python_COPY

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#599]
Problem to solve:
- too long dirs during installation using NSIS (in partcular due to pip)
- avoid copy unnecessary modules
  TODO:
- USE_PYTHON indicates only if we make flow_define(HAVE_PYTHON)
- introduce variables (in config file) to set what modules to copy, and some other details of the copy process

**Comment by x3mSpeedy** [comment]
Pull in #602 should fix this issue

**Comment by jbrezmorf** [comment]
Irrelevant without using NSIS
