### ISSUE TITLE
Python scripts for tests

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#600]
**Integration and Unit tests of the scripts**:
- [x] everything in `unit_tests/test_scripts`
- [x] create mockup for bin/flow123d in order to test the `run_test.py`
- [x] test also correct reporting of errors

**Comment by jbrezmorf** [comment]
This seems to be done. Is it pull request: #645?

**Comment by x3mSpeedy** [comment]
Yes it is done (branch `JHy_python_scripts`) but not merged.

**Comment by jbrezmorf** [comment]
Merged in 6e8e39fbf
