### ISSUE TITLE
Intersections and components, problems in 2d-2d.

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#621]
Intersection 2D-2D inside 3D bulk mesh.
(expl.: After computing 2D-3D, go through 3D elements and their intersections..)

Problem: we need to distinguish elements of the same component
when on 3D element, we want to compute intersections of every 2D element pair having intersection with 3D element and of course we don't want to compute intersection for neighboring elements (and also 'vertex neighbors').. i.e. we want to exclude 2D elements of the same component

solution idea 1:
We already number components and set component index in intersection algorithms, but in 2d-3d this does not work, since we do not prolongate over intersection of size < 3.
Therefore we can add this type of prolongation (if possible ??) and ensure, that components are numbered correctly. Then we only ask, if the candidates are from different components...

update: in BIHonly algorithm we do not prolongate, therefore we have no component numbers and we cannot compute 2d-2d later using this approach..

solution idea 2:
mesh preprocessing - number components a priori

solution idea 3:
cannot we ask user, that the input mesh is required to distinguish between components? different region ids for different components... but this probably does not ensure that two components will not have the same id accidentally

**Comment by jbrezmorf** [comment]
Use solution 2, breadth first search on mesh elements.
After finishing prerequisites of solution 1 we can just use the main breadth first search  and naturally move to solution 1.

**Comment by Paulie14** [comment]
Can be closed, moved to #690.
