### ISSUE TITLE
Bounding Boxes and BIHtree computation in intersections

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#623]
- [x] 
  Currently, BIHtree is created for each algorithm 1d-3d, 2d-3d, and possibly for others.
  We need to compute it definitely once at maximum.
  Should it be part of Mesh or InspectElements or ?
- [x] 
  Bounding boxes are computed in BIH, so we do not have to compute them again, like we do at the moment
- [x] 
  The above is related also to question of algorithm selection: BIHonly, BIHsearch, BBsearch
  if we intend to have this selection at all... (I think so)
  When and according to what do we decide ?

**Comment by jbrezmorf** [comment]
ad 1. When implementing observe points I run to the same problem with BIHTree. So now it is part of the mesh.

ad 2. BIHTree contains precomputed boxes, but we need an accessor to get box of particular element.

ad 3. Add new key into Mesh record with default value BIHsearch.

**Comment by Paulie14** [comment]
OK, I have already done 1,2 (I just put BIH into inspect elements, so I will take it from mesh..)

**Comment by Paulie14** [comment]
Finished by 70e2c30.
