### ISSUE TITLE
Finish remove of Field<..>::Vector

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#625]
- [x] pass through field unit tests, remove commented EnumVector related tests
      try to replace Vector by VectorFixed where it test something new, what is not part of other tests
      
- [ ] remove set_components() in  FieldCommon,  Field<>

- [ ] remove FieldValue specialization

**Comment by dflanderka** [comment]
After fix problem with Python fields, definitions of vector fields in field_algo_base.cc and darcy_flow_mh_output.cc can be removed.
