### ISSUE TITLE
null Balance 

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#631]
Have internal flag in the Balance to indicate that it is on or off. Remove lot of boilerplate code in equations.
- [x] flag already implemented
  other possible simplifications:
- [ ] merge start___assembly and finish___assembly methods
- [ ] make compute_\* methods internal calling them automatically from output method
- [x] move check for is_current into output method
- [x] move check for cumulative into cumulative_\* methods (already done)
- remove (now) unnecessary tests for empty balance

**Comment by jstebel** [comment]
start and finish assembly cannot be merged because balance matrices for mass, source and flux may be assembled independently at different times.
