### ISSUE TITLE
XFEM adaptive quadrature rule in 2d

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#640]
Mirror adaptive quadrature from PE thesis for 2d case.
- define singularity object with enrichment function
- define object for xfem quadrature - quad point coordinates both in real and reference element
- create xfem quadrature factory
- mirror refinement algorithm from quadrilateral to triangle elements
- implement distance criterion for refinement

3D ambient space
- 1d well is cylinder; if it is not perpendicular to the 2d plane, their cross section is ellipse..
  (so far, I simplified that and I only rotate the circle around the cross section center..)
- ellipse triangle intersection is harder to compute, enrichment function is than also more complicated since we need to compute points along the ellipse and the enrichment function is then dependent on the plane

**Comment by jbrezmorf** [comment]
3D ambient space:
- no need for triangle - ellipse intersection, just need to decide if a point is in the ellipse
- can introduce a transform on the plane that maps ellipse to a unit circle (this map is unique for every well)

**Comment by Paulie14** [comment]
solved:
- compute projection of the circle onto ellipse (we have exact cross section, we can now also compute qpoints for boundary intergral)
- project element into the plane of the circle
- create subelement refinement for quadrature
(we compute distance of triangle and circle in the refinement criteria)
- project subelement refinement back to ellipse (element) plane
- distribute quadrature points on the refined element (there is a check on subelements crosssecting the ellipse that qpoint lies inside or not)

**Comment by jbrezmorf** [comment]
Can discuss during your visit home. 2.9. or 5.9. as you wish.

**Comment by jbrezmorf** [comment]
done
