### ISSUE TITLE
FEValues updates gradients in Darcy Flow

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#641]
Is there a reason, why should fe_values in Darcy Flow update also gradients??
I believe that is unnecessary.

Secondly, why there is 3. degree Gauss quadrature??
2. degree should be satisfying in my opinion.

All test are ok with the cheaper setting.
If you agree, I'll make the change in master...

**Comment by jstebel** [comment]
I don't see any reason for updating gradients.

The quadrature is used only to integrate u.(A^(-1)v) on elements (A stands for anisotropy*conductivity*cross_section). So if A is constant, then 2 point Gauss quadrature is OK. But in general we cannot guarantee exact integration.

**Comment by Paulie14** [comment]
Thanks, I did not realize that A does not have to be constant inside element..

**Comment by jbrezmorf** [comment]
There is a function Field<>::field_result that could be used to check for special cases. In particular we can check for result_constant and result_eye to apply some optimizations. However the assembly is completely reorganised in the Richards branch which I hope to merge till the next week. So, I propose to postpone this optimization after that.

**Comment by jbrezmorf** [comment]
- [ ] Turn off update_gradients
- [ ] Check for constant conductivity and modify quadrature.
- [ ] Proof effect on a benchmark.

**Comment by Paulie14** [comment]
Turning of updating gradients brings:
- 1,84 x speedup in `DarcyFlowMHy::assembly_mh_matrix`
- 1,81 x speedup in `DarcyLMH::assembly_steady_mh_matrix`
(measured with profiler on master a41e096bbcce0169975c42b5df83930cba6f896a, release build, average of 10 measurements)

**Comment by Paulie14** [comment]
Quadrature:
- it seems that we do not integrate the fields at all!
- all the fields (conductivity, anisotropy, water_source_denstity, ...) are evaluated only at element centers

**Comment by Paulie14** [comment]
I decreased the quadrature order to 2 which is accurate for the combinations of RT0 base functions (v_i, v_j)
with further speedup:
- 1,72 x speedup in `DarcyFlowMHy::assembly_mh_matrix`
- 1,32 x speedup in `DarcyLMH::assembly_steady_mh_matrix`

**Comment by jbrezmorf** [comment]
REduce quadrature order to 2 and update binary output 03-37

**Comment by Paulie14** [comment]
Finished by 366f6e7e64957755799455c95c5c640661e031ff.
PR #1353.
