### ISSUE TITLE
remove INPUT_CHECK macro

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#647]
- [x] replace all use cases of INPUT_CHECK macro by explicit 'if' statement with throwing an input exception
      (about 13 matches)
- [x] remove all use of xprintf(Msg,...) (replace by the output streams)
      (about 9 matches)
- [x] remove all use of xprintf(UsrErr, ...) .. excepion of input exception
      (about 26 matches)
- [x] remove all use of xprintf(Err, ...) .. excepion of input exception
      (about 13 matches)
- [x] remove all use of xprintf(PrgErr, ...) .. excepion of input exception
      (about 9 matches)

- [x] remove xio.*
- [x] remove read_ini.*
- [x]  remove Semchem

**Comment by dflanderka** [comment]
Merge in 63a12c7f2
