### ISSUE TITLE
[docker] Invalid mpiexec binary

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#683]
If we are using `openmpi `under docker, `mpiexec `does not work:
![image](https://cloud.githubusercontent.com/assets/894428/18129173/d126dd1c-6f89-11e6-8d97-bb30679da1b2.png)

**Comment by jbrezmorf** [comment]
That is more like mpiexec doesn't exist. Try to call it explicitely:

	<path>/mpiexec -n 1 <flow_path>/flow123d -s ...

**Comment by x3mSpeedy** [comment]
In cmake we rely on variable from PETSc `PETSC_MPIEXEC` which is used in our mpiexec wrapper. But value is first edited using `realpath` which should make value absolute.

If value from PETSc is indeed path it works fine, but if `PETSC_MPIEXEC` is just a command, such as `mpiexec`, calling `realpath` will just append current working directory to that value making it absolute (it assumes that given value is relative path) thus wrapper does not point to valid location. Commit ce70532c4ed0c1872865374773ce3b0ad2f12eca shoud fix that.

**Comment by jbrezmorf** [comment]
OK.
