### ISSUE TITLE
[docker] using openmpi under docker

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#685]
When using openmpi MPI_INIT fails:
```
> It looks like MPI_INIT failed for some reason; your parallel process
> is likely to abort.  There are many reasons that a parallel process
> can fail during MPI_INIT; some of which are due to configuration or
> environment problems.  This failure appears to be an internal failure;
> here's some additional information (which may only be relevant to an
> Open MPI developer):
```

Need to investigate whether compilation and linking are coming both from `openmpi` and not that some parts coming from `mpich` and some from `openmpi` as stated [here](http://stackoverflow.com/questions/7011519/mpiexec-fails-as-mpi-init-aborts/13197488#13197488)

Temporary solution is to not install `openmpi` at all and only install `mpich` library.

**Comment by jbrezmorf** [comment]
Use mpich instead of openmpi is OK.
