### ISSUE TITLE
Intersections further development

### ISSUE THREAD

**Issue by Paulie14** [flow123d/flow123d#690]
**2D-3D unit tests**
- [x] Get rid of comparison with NGH. Replace the tests with new ones that have analytic solution.

**1D-2D intersection in 2D space**
Implement an effective algorithm for 1d-2d intersections in 2D space.
(Probably not using Plucker; we can apply some prolongation algorithm like in 1D-3D)

**1D-2D intersection inside 3D bulk mesh**
- [x] Algorithm is implemented. However we do not look for any 1D-2D intersections outside 3D bulk mesh.

**2D-3D prolongation improvement**
- [x] Currently we only prolongate, when there are more then 2 intersection points.
We should investigate also prolongation over line or point. This would solve the problem in component numbering in 2D-2D intersection.

**2D-2D intersection inside 3D bulk mesh**
- [ ] Use breadth first search algorithm to number components.
At first we can number the components a priori; After solving 2D-3D prolongation (see above), we could possibly do it inside the prolongation breadth first search.  (Issue #621)
We do not look for any 2D-2D intersections outside 3D bulk mesh.
We suppose disjunct 2D elements in the same plane (not lying on each other).

**Tolerances in intersections**
We unified tolerance usage in intersection algorithm (geometry (input) tolerance, vs. rounding tolerance). Still, there are cases, when the IPs are found in wrong way (e.g. 2 IPs close the edge, instead of a single IP on an edge). This causes error in optimal tracing algorithm (solved by hack at the moment - if error, then call the convex hull tracing). See old issue #483.

**Overtake role of NGH**
Overtake role of ngh in computation of 2d-1d intersections.

**Comment by jbrezmorf** [comment]
Notes from writing paper:
- use RefElement<N> in Simplex<N>

**Comment by Paulie14** [comment]
Some notes what we should finish after the paper:
- [ ] Finish and test robust tracing algorithm for 2d-3d case in branch JB_intersections. This also includes some changes in RefElement
- [ ] Add functionality in RefElement for get local index of an edge of a side, etc.
- [ ] How to iterate sides of triangle of RefElement in cyclic order and cyclic orientation?
- [ ] Reuse CI objects in mesh intersection algorithm in order to reduce number of allocations
- [ ] Review 1d-2d degenerate intersection algorithm
- [ ] Eliminate Simplex<> clases as the intersection algorithms work only with plucker coordinates and RefElement.
- [ ] Eliminate duplicate code for final intersections (1d-2d, 1d-3d) have separate method to finish an intersection object or store the intersection in  th CI itself. A fixed (maximum) size of the Intersection may be allocated.

**Comment by Paulie14** [comment]
2D-3D prolongation improvement in 8bdaffcb66ea04beb15a93f915fa8c14eae217ed and previous commits. New 23 prolongation unit tests added. Still need to look at the correct component numbering and element closing (not tested enough).

**Comment by Paulie14** [comment]
23 unit tests created in 8928cfdee28c8dc5f398e066ba1d6849013ffa6d in branch PE_prolong at the moment. Need to be broaden with more cases. Read notes in corresponding unit test cpp file for info on testing. I tried to start doing it in JB_intersection, but it fails a lot, so I moved into my branch..

**Comment by jbrezmorf** [comment]
Urgent points moved to #802 to be done before merge.
Long term points moved to #801.
