### ISSUE TITLE
Darcy flow per dimension assembly

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#691]
Goals:
- consistent elimination of dirichlet dofs
- whole assembly separated by dimension (specialized code used for every element according to dimension), one virtual call per element
- allow arbitrary order of assembled elements 

TODO:
- move remaining code in `DarcyMH::assembly _mh_matrix` into AssemblyMH class template in darcy_flow_assembly.hh
- keep only the main element loop in assembly_mh_matrix
- introduce a new class LocalSystem to store: dense local matrix, local rhs, row and col dofs, dirichlet condition indicators, dirichlet bc values (solution values)
- assembly into this class whole local system, indicate Dirichlet values correctly
- copy method LinSys::set_values into the local system object

**Comment by Paulie14** [comment]
I created LocalSystem. I mirrored the set_values function and also created set_value method for single entry. I enabled setting the dirichlet BC before entering the other values.
I copied also the unit test from lin_sys..

Do I understand correctly that we want to do the assembly of local system in these steps:
1) setup dirichlet BC
(Then I will have to go through sides to compute anything with Dirichlet at first; and later deal with other entries, correct?)
2) entry the matrix and rhs values one-by-one, using set_value method, which now handles dirichlet values
3) pass the local system to lin_sys

I am not sure about the diagonal part of set_values function. The new_diagonal value is computed from loc_matrix, which is now the local system?? Or is the 'submatrix' of the local system which we want to enter?
In function set_value, which sets only one entry, I moved this part to another function, which then uses the whole local system. (see possibly PE_assembly)

**Comment by Paulie14** [comment]
Issue with DirichletBC in LocalSystem: #804

**Comment by jbrezmorf** [comment]
It seems that this issue is already resolved. Am I right?

**Comment by Paulie14** [comment]
Yes.
