### ISSUE TITLE
Wrong flow calculation for small conductivity and bc_flux

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#695]
See integration_tests/05_tutorial/02_column_transport.yaml (fork jbrezmorf/flow123d, branch JS_test).

When the conductivity is 1e-8, bc_flux 6.34e-9, the flow calculation is wrong (probably since the product of both is smaller than the tolerance 1e-15 of the solver).

When one of these quantities is increased 100 times, the problem disappears.

I suspect that it is due to the scaling of the linear algebra system, which has changed recently.

**Comment by jstebel** [comment]
Git bisect found:
good commit 7a683e39871bdfd1aff4b61d2bab55db9a9753cc
bad commit f9948508ade11c8c8502036a89364239db11f713

**Comment by jbrezmorf** [comment]
Current implementation use (hacked) nonlinear solver also for linear problems. So if the tolerance of the nonlinear solver is high and error in water content is low we get convergence without singel linear solve.
Resolution:
- have dedicated nonlinear solver, use just linear variant in the linear case
- use better criteria then just water content error 
- temporary solution: at least single iteration always required (default value for min_it option)
