### ISSUE TITLE
[Python] long testing interval while using runtest

### ISSUE THREAD

**Issue by x3mSpeedy** [flow123d/flow123d#698]
While using `runtest`, each process is periodically checked. We are testing:
 1. process duration is lower then `limit_time`
 2. process memory allocation is lower then `limit_memory`

In order to affect process as least as possible, we are using `5 sec` interval which does not disturb system that much but causes following bug:

Process duration can exceed `limit_time `and still be considered as successful because check point last check did not break any limits but the next check would reveal limits violation:

This way we may encounter memory bugs as well. The most fatal scenario could be exhausting memory completely in `5 sec ` (*could not terminate process with memory leak in time which could be fatal*).

Possible solutions:
 - shorten test interval (if too short, could introduce additional overhead because system calls)
 - do nothing (*tolerate this behaviour*)
 - check limits (only duration) after process ended and mark test as failure upon rule violation

**Comment by jbrezmorf** [comment]
Estimating that a single check takes about 1000 ticks the check interval may be even about 1ms without large performance penalty. On the other hand no time interval can avoid breaking the limits and it is not in fact necessary. Absolutely no problem with slight overcomming of the time limit and usually no big deal with memory limit as the leak usually progress slowly. 

Anyway I understood that you use shorter check interval at the beginning and then gradually larger one.

**Comment by jbrezmorf** [comment]
May I close this?
