### ISSUE TITLE
[Python] wait for sufficient amount of free memory

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#699]
While running `runtest` we may encounter swapping since multiple instances of `runtest`are running of the same platform.

Idea is to not start process until _`sufficient amount`_ of free memory is available. Term _`sufficient amount`_ can be easily obtained from test memory limits.

If we eliminate swapping I believe tests can run faster and they can also be more stable (if we are swapping, process duration will be greater).

**Comment by jbrezmorf** [comment]
What about turning off the swapping or deminish swappiness  before starting flow123d. Can be part of flow123d.sh (script to run flow in docker).

**Comment by janhybs** [comment]
To play with swap root access is necessary I believe but can also affect user. A solution I can think of is:

runtest will communicate with other runtest instances (only on demand, off by default). The behavior will be similar to that of a queue, where running runtest will add new jobs to the queue while queue is continuously processed if free resource is available (CPU)

**Comment by jbrezmorf** [comment]
Interesting idea, but a bit nontrivial to implement (communication, detection of assumed memory footprint of the test). 
This is an issue only on Jenkins build server so can consider:
- turn off swapping on this machine
- enlarge memory of this virtual machine
- move builds to (new or existing) virtual on charon frontend or to the charon itself
