### ISSUE TITLE
profiler: measure time penalty of collecting memory info

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#706]
Seems that collecting memory information is big performance penalty making the profiler inusable
for frames with many calls. 
- measure what part takes so much time
- turn that (possibly the PETSc off by default)
- Possibly allow detailed tunign of the frame paramters, eg.
  
  START_TIMER("memory frame").petsc_memory_on()

**Comment by x3mSpeedy** [comment]
Done in docker repo https://github.com/jbrezmorf/flow123d/commit/ce501b979677f0b4ee953b0dc0c7d3792e64235d branch [JHy_profiler_memory](https://github.com/jbrezmorf/flow123d/commits/JHy_profiler_memory)

By default `START_TIMER` does not measure petsc memory allocations.
For that macro `START_TIMER_PETSC` was added.

Profile memory overhead studied in more depth in #719

**Comment by jbrezmorf** [comment]
Further development, possibly in new issue:
- [ ] keep memory measurement on by default
- [ ] Memory info in formated profiler output.

**Comment by jbrezmorf** [comment]
related to #719

**Comment by jbrezmorf** [comment]
See #719
