### ISSUE TITLE
Use copy instead of symlinks under Windows

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#717]
- try to use copy instead of symlink in macro `make_link_in_source`, line 680
  use `copy` instead of `create_symlink`
- try if it works under docker under windows
- if yes, add an option `COPY_INSTEAD_OF_SYMLINK` Iinto config.cmake file

**Comment by jbrezmorf** [comment]
Check if copy_directory works also as replacement of file symlinks. Worry it doesn't. Possibly call both copy and copy_directory. We plane slight reorganization of the python code which will make copy_directory unnecessary, but it takes time.

**Comment by jbrezmorf** [comment]
- `ln -s ` - creates empty file instead of the link, no error
- `cmake create_symlink` fails with error

**Comment by jbrezmorf** [comment]
Try to setextradata to the VirtualMachine se the link above.

**Comment by dflanderka** [comment]
Symlinks under Windows allows to create command:

...
ln - s <source> <target> -f
...

This command must be executed under docker and creating symlinks are executable under docker too.

**Comment by jbrezmorf** [comment]
Can make this work even running VM as non-admin?

**Comment by dflanderka** [comment]
No, it fails with above-mentioned protocol error.

**Comment by jbrezmorf** [comment]
Seems that we can not succeed to use links under docker under windows reliably. 
TODO:
- introduce separate macro that make wrappers fro executables, do not use links but always only wrappers, can be used for: mpiexec, flow123d, tests/runtest

**Comment by jbrezmorf** [comment]
Done in commit 9bb4f8.
