### ISSUE TITLE
Work after PE intersection merge

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#722]
Summary of work to do yet after merge of monstrous PE_intersection branch.
- [ ] remove topology_idx from RefElement, see TODO in correct_tetrahedron_ip_topology
- [x] fe_rt.hh and other fem code, try to make explicit instantiation, move implementation to cc files, avoid unnecessary includes in headers.
- [ ] Cleanup in bih_tree, unused 'counter', in method find_bounding_box. 
- [ ] Performance test of BIH tree, possible optimization of its creation (median etc.). Remove commented code.
- [x] What is 
  
  double tetrahedron_jacobian() const;

in element.hh. Why we need this? Use FEValues instead.
- [x] Used in GMSHReader::read_elements to check sign of jacobian. We should do our renumbering of elements to minimize number of permutations of sides for neighbouring elements, then we should fix this sign as well. Degeneracy checked elsewhere.
- [x] Call of intersection search algorithm should be part of mesh, so then 

Mesh::IntersectionSearch Mesh::get_intersection_search()

will not be necessary.
- [x] Unify barycentric coords convention. Distinguish local coords and barycentric coords. Cleanup code due to observation point. Resolve duplicity of element map with fe_mapping.
- [x] Try to yet improve Interaction syntax and names, e.g. RefElement<dim>::Incidence<dim_out, dim_in>(idx_in) may be array like object, possibly derived from std::array. 
- [x] Need also inverse of incidence,e.g. getting local number of node on side or edge.
- [ ] Finish 2d-3d topology polygon tracking algorithm.
- [ ] Remove old tracking methods.
- [x] Finish unit tests, replace comparison to ngh with manually computed intersection (should be nice).
- [x] Use 1d-2d instead of ngh in current non-compatible code.
- [x] Remove ngh.
- [ ] Review allocations during intersection search.
- [ ] Try to make intersections independent of particular numberings in RefElement (in particular where we need some special numbering or ordering).
- [ ] Try to have elementary intersection algorithms 'parsimonious' that is every float condition should be independent of conditions evaluated before. Probably not completely possible. Then adaptive precision predicates may help.

**Comment by Paulie14** [comment]
double tetrahedron_jacobian() const;
is just temporary solution, mainly for interesection unit tests (for warning or assert, if the mesh is ok), because we do not ensure, that element nodes are numbered properly; 
It should be done properly including renumbering, as you write, during gmsh reading...

**Comment by jbrezmorf** [comment]
Review this old issue. Try to finish what can be finished quickly.

**Comment by Paulie14** [comment]
Partially finished, continues in issue #801 for next release.
