### ISSUE TITLE
transport: inconsistent zero time step output 

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#726]
Transport operator splitting treats output at zero time step out of output_data method, in particular ConvectionTransport::zero_time_step performs output of at zero time so the 
TransportOperatorSplitting::output_data() can not be called ?? as it performs the same output again (that may still produce just single output).
Nevertheless result is inconsistent behavior of balance output.

- try to use common output_data method also in zero_time

**Comment by jstebel** [comment]
When balance::add_input_times is set to false, balance of transport writes out the zero time even if it should not.
