### ISSUE TITLE
CI and Packaging

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#729]
For version 2.1.0 we must fix:
- [x] build documentation also for debug builds to detect errors coming from source
- [x] publish documentation PDF also out of the package and image
- [x] publish HTML doc
- [x] add into package:
	- have manual PDF into doc/
  	- HTML doc into /doc
 	- bin/input_convert.py (move into bin/python)
	- wrappers: bin/input_convert.sh, bin/runtest

- [x] remove from package: 
	- bin/config
	- bin/ini2json.sh
	- bin/python/ini2json*
	- doc/con_syntax 
	- include
	- lib/cmake
	- share
	
- [x] update bin/README
- [x] update doc/README
- [x] update README.md
- [x] make structured output of latex formatter ( try '%\n' for line ends)
- [x] remove redundant formatter files e.g. src/python/ist/formaters/json2latex.py , ... 
- [x] remove or add description in comment for config/artifacts.yaml

HTML doc issues:
- [x] Must have at least ROOT button, better provide sort of types by IST depth
- [x] Record and Tuple keys should link to their types not to them selfs.
- [x] Default values are missing. Move description under key, put defulat value to the right from the key name.
- [x] Records that implements some Abstract have key TYPE.

**Comment by jbrezmorf** [comment]
- [ ] still missing: 
    - html doc, 
    - bin/input_convert.py (move into bin/python)
    - wrappers: bin/input_convert.sh, bin/runtest
- [ ] still not removed what should be removed (not in repository but still in installation)

Usage problems (tested linux installation):
- most of files only inside docker package, not practical (tests, doc) we should try to have only executables and scripts inside container
- better location just /opt/flow123d
- mount /home/jb to /home/jb and cd to actual dir if under home, cd to home otherwise
- after installation rather plot info about fterm.sh and flow123d.sh

**Comment by x3mSpeedy** [comment]
[materialize-v0.97.8.zip](https://github.com/flow123d/flow123d/files/645566/materialize-v0.97.8.zip)

**Comment by jbrezmorf** [comment]
- What is Flow123d-docker-windows.zip, Flow123d-image.tar.gz?
- *-image vs, *-docker-image?
- duplicate publication of htmldoc and doc/htmldoc

**Comment by x3mSpeedy** [comment]
- [ ] fix python modules path
- [ ] fix path in `flow123d.sh`
- [ ] add uninstall script
- [ ] remove empty dir `/opt/flow123d/flow123d`

**Comment by jbrezmorf** [comment]
Good progress. Just finish tow remaining points. ASAP.

**Comment by x3mSpeedy** [comment]
Commit 95d9b275af0dafd7f742bb3d8d6c62b34cc39a1f should clear all `test_results*` folders.
Regarding empty `/opt/flow123d/flow123d`. Its removal is more wired then I presumed at first so it requires more time and effort.

**Comment by jbrezmorf** [comment]
Thats enough for release 2.1.0.  I'm going to publish it today.

**Comment by jbrezmorf** [comment]
done.
