### ISSUE TITLE
stats in /proc/net/dev are different for eth0, veth0, docker0 and wlan0

### ISSUE THREAD

**Issue by aagarwal-optumsoft** [flow123d/flow123d#733]
I have a setup where a raspberry Pi is connected using wifi to the internet, runs the docker container, inside which there are bunch of processes communication with a public server over TCP. I monitor /proc/net/dev for 100 secs at eth0 (inside container) and  veth0 & docker0 (outside the conatiner). I see that bytes transmitted from veth0 and docker0 interface are same but very less in comparison to eth0 In spite of all having same number of packets. Following is the e.g stats of that:

eth0: 73,427 bytes and 165 packets
veth0: 11,842 bytes and 166 packets
docker0: 11,842 bytes and 166 packets
wlan0 (on host): 84,964 bytes and 228 packets.

so the actual data sent should be at wlan0 interface and that is very much consistent with eth0 (inside the container). 

Am I mistaken in some way?

Thanks
Abhinav

**Comment by jbrezmorf** [comment]
Wrong project.
