### ISSUE TITLE
Profiler JSON output

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#764]
Boost library used to output profiler data in JSON format seems to not support output of ints and floats in native JSON format and outputs them as strings instead which makes further processing more complicated.

- verify that the library can not deal with it
- use our own output to go around the problem

**Comment by janhybs** [comment]
Boost ptree does not support this functionality nor it will in near future 
https://svn.boost.org/trac10/ticket/9721

When processing profiler data, is it inevitable to pre-process the data. Therefore I propose to leave the files as they are. Other solution would be to bring another json output library and have yet another dependency/license to manage.

**Comment by jbrezmorf** [comment]
Result: do no close the issue, but postpone as it has low priority.

**Comment by janhybs** [comment]
I suggest to use [nlohmann](https://github.com/nlohmann/json) header-only library licensed under MTI. It is handy fast and does support basic such as numbers, strings booleans and can even support custom types.

**Comment by jbrezmorf** [comment]
Agree. Add the header and use it.

**Comment by janhybs** [comment]
PR #1152

**Comment by jbrezmorf** [comment]
Usage of another library aside from JSON spirit is not ideal, yet the problem is resolved.
