### ISSUE TITLE
Profiler - memory allocation

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#78]
Need to monitor memory usage in  Flow123d.
- [ ] redefine new/delete operators (see LibMesh) for such profilling
- [ ] Use PetscMallocGetMaximumUsage(), PetscMemoryGetCurrentUsage(),
PetscMemoryGetMaximumUsage() or other PETSC functions to include also PETSC allocations.
- [ ] check by valgrind --tool=ḿassif that we cover significant allocations

It is dangerous to implement new operators by calling malloc and delete operators by calling free.
We need:
- better redefinition of these operators so that we can count memory and report it in Profiler
- redefinition compatible with various compilers
- must redefine all allocation/deallocation operators/functions since they can be used in templated libraries (e.g. armadillo boost)
... nevertheless current overload seems to work well (possibly due to C++11)

**Comment by x3mSpeedy** [comment]
- [x] operators redifined
 - [x] add unit tests
 - [x] monitor also Petsc memory consumption
 - [ ] add simple  unit test to petsc
 - [ ] verify by valgrind, results:
results of allocating and deallocating differ, but it appears that different is **constant** (maybe Python loading or other things which are not measured)
will run more tests
