### ISSUE TITLE
CI and publish 2.2.0

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#781]
Summary issue for various problems in CI, packaging and publication.

- [x] Builds are publised on flow.nti.tul.cz in unique directories containing commit hash. This is good so we know where particular build comes from but we are not able to provide links to master builds on the web.
Do we need them? (link to latest, delete old builds?)

- [x] Python 3. Both for conversion script and in usage with Flow123d for embedded Python. Issue #644 

- [x] Mount current directory into Docker if it is not under already mounted directories. (solution under windows is not so simple)

- [x] Mount root location of Flow123d installation (access to tests). (solution under windows is not so simple)

- [x] Rename directory in package to "Flow123d-2.x.y", i.e. without "windows-install" etc.

- [x] uninstall.sh do not uninstall Git and VirtualBox  and keep .docker and .VirtualBox directories.

- [x] Seems that sometime VBoxManage is not in path. Temporary resolution in `bin/mounts.sh` is to check also its usual absolute location. Tested with Windows 10 but not sure, that location does not change with Windows version. Any better idea how to obtain VBoxManage location?

- [ ] Use true installer for Windows. (Possibly hire a freelancer?)

**Comment by x3mSpeedy** [comment]
About VboxManage. I scan registry and it appears we can use registry key `HKLM\SOFTWARE\Oracle\VirtualBox`.
Following example will return installation directory of VirtualBox:

```ps1
PS C:\Users\Jan> (Get-ItemProperty -Path HKLM:SOFTWARE\Oracle\VirtualBox).InstallDir
C:\Program Files\Oracle\VirtualBox\
```

which we complete and pass it to script `mounts.sh`.

**Comment by x3mSpeedy** [comment]
Improvements:
- [ ] do not exit shell right away if error occurs (user does not see output)
- [ ] fix custom `.bat` shortcuts on windows
right now custom `.bat` file having command `flow123d -s %1 -o %1.out` does not work
- [ ] mount also extra folders when using `flow123d.bat`
- [ ] increase font size (or perhaps tutorial on how to change the font size)

**Comment by jbrezmorf** [comment]
Done.
