### ISSUE TITLE
no docker builds

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#782]
Implement scripts that allows automatic builds of flow without docker (i.e. metacentrum).
These will be part of docker-config repository.

Have all configuration or parts that may be modified into a single script. Have stable subroutines in separate script.

- [x] unify installation scripts for libraries, separate BUILD_TREE from target location, i.e. INSTALL_DIR (e.g. /usr/lib)
- [ ] build of libraries using specific system libraries (BLAS, LAPACK, MPI ...)
- [ ] build flow123d
- [ ] move as much as possible to stable script, i.e. code cleanup
- [ ] document building process

**Comment by janhybs** [comment]
I've create a [new branch]((/flow123d/docker-config/tree/janhybs/libs-update)) in docker config repo. Where installation process is unified.

The main makefile is for Jenkins and other auto tool to use. Precise tuning of the installation process can be done using makefile in subfolders. Everything should be written in makefile's comments.

**Comment by jbrezmorf** [comment]
What is name of the branch? The link doesn't work.

**Comment by janhybs** [comment]
Fixed the link,
https://github.com/flow123d/docker-config/tree/janhybs/libs-update

**Comment by janhybs** [comment]
There is a [Makefile](https://github.com/flow123d/docker-config/blob/master/cmakefiles/Makefile) which offers this functionality (and is used on metacentrum). You can specify `BUILD_TYPE` and `INSTALL_PREFIX`:

```sh
make BUILD_TYPE=Release INSTALL_PREFIX=$(pwd)/libs petsc
```

**Comment by jbrezmorf** [comment]
The mentioned branch in the docker config repository merged into master.
No intent to fully resolve this issue. We rather try Singularity to have fixed runtime environment also on Metacentrum clusters.
