### ISSUE TITLE
Need check for missing placeholder.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#788]
If placeholder INPUT is not set but used in the input file, no relevant error message is throwed.

See: void FilePath::substitute_value

**Comment by dflanderka** [comment]
If parameter -i (-input_dir) is not set, default value 'input' is used. I propose to add warning in Application::parse_cmd_line, that default value is used (not only for input parameter, but for output parameter too).

**Comment by jbrezmorf** [comment]
Resolved as: no bug, just feature.
