### ISSUE TITLE
Various improvements in input structure

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#791]
- key 'output_stream' is obligatory even if it have defaults for all values
  ... add empty record as a default value for this key.
- same for linear and nonlinear solver (provided Petsc is default solver type)
    ... add empty record as a default value for linear and nonlinear solver, set 'Petsc' as default for the abstract.
- (linear) solver in DG need not to be obligatory
  ... add empty record as a default value for this key.

**Comment by dflanderka** [comment]
Done in pull #898 and prepare for merge.
