### ISSUE TITLE
Improve description of heat fields

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#792]
What is 'fluid_ref_temperature', there is no sigma for robin like sources. Make nomenclature consistent with transport and darcy flow where possible.

**Comment by jstebel** [comment]
The corresponding 'sigma' is named 'solid heat exchange rate'. In the milestone 2.2.0 we may not rename the fields.

**Comment by jbrezmorf** [comment]
Improve description of heat fields and postpone changes in field names to an issue for 3.0.0 branch. We postpone changes in input after new implementation of the conversion script.
