### ISSUE TITLE
Review DG + Reaction term sorption

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#794]
Results are strongly discontinuous.
Result of benchmark 'flow_dg_sorption.yaml':
![convection_dg_with_sorption](https://cloud.githubusercontent.com/assets/326204/22302721/5b3954c0-e330-11e6-8dec-3bb7bcfe7db4.png)

**Comment by jstebel** [comment]
This is not a bug.

Reactions under operator splitting are calculated elementwise, which increases the discontinuity. In this problem, there is a large advection as well, which together with large time step produces this result.

Remedy: enforce smaller computational time step (max_dt: 0.01).
