### ISSUE TITLE
Space characters in path during installation

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#797]
During installation on Windows we encountered problem, where installation folder contained spaces. Installation process was not completed correctly. This can also happen on Linux as Windows installation process uses some Linux install scripts.

There are two problems:
- [x] quote escaping in scripts (can be easily fixed)
- [ ] quote escaping in external programs (cannot be fixed). This is so far only related `VBoxManage`. Users cannot mount folders containing spaces. 
In `VBoxManage` we register new shared folder, this shared folder requires name which we obtain from given Windows path:

  - user input **`f:\data`**
  - linux mount path **`/f/data`**
  - shared folder name **`f/data`**

Problem is that shared folder apparently cannot contain spaces (at least testing proofed that). We have several options:

 - normalize path (replace spaces)
 - create custom shared folder name (it is hidden to it can be random)
 - postpone this issue, since we plan to mount whole disks anyway.

**Comment by jbrezmorf** [comment]
Concerning the shared folder issue:
ad 1. Path normalization seems viable.
ad 2. Do not understand. If we mount f:\data as shared: user_mount_42 it would be quite confusing. 
ad 3. Can we do that right now? Just change the message before prompt and just take the first letter.

So 3. seems simplest, but 1. may also work.

**Comment by janhybs** [comment]
Picked the solution no. 3 to mount the whole disks done in flow123d/docker-config@e835442b250ff8ffad675a24f5a0c2b8982c3f0b
