### ISSUE TITLE
docker development scripts

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#798]
Currently we have the configure script, for preparation of images, and environment. Further JB have docker.sh script for configuration and starting of dev. env. Further we need fterm.sh (development version, partly implemented in docker.sh) to allow calls from eclipse. Related to #754. 

docker configure: 
add user to group docker
set docker mapping dirs
setup/download images
set user and group in docker
add user extensions (namely changes in .bashrc, completitions, additional packages)
make user extended image

fterm.sh (replacement for docekr.sh)
just start shel in an interactive mode
run particular command
make clean-all
make config
make fast-flow123d
make ...
run_test.sh

**Comment by janhybs** [comment]
@jbrezmorf, @jstebel, It would be quite useful if you could send me your `docker.sh` setup scripts so I can *merge* them into a single one while preserving all the functionality.

**Comment by jbrezmorf** [comment]
Mine is in bin/docker.sh.

Further propositions:
- move it or make a wrapper bin/flowsh,  
- that normally tries to configure and open the shell in the docker
- options or subcommands (like 'flowsh make' or 'flowsh conf') can be used for specific operations under or over the container
- necessary improvements:
    - mount whole $HOME
    - transfer git user and mail from the host git setting

**Comment by jstebel** [comment]
Further improvement:
On some machines docker must be run with "--privileged" in order to disable ASLR which is necessary for GDB debugger.

https://stackoverflow.com/questions/34856092/gdb-does-not-hit-any-breakpoints-when-i-run-it-from-inside-docker-container

**Comment by jbrezmorf** [comment]
Resolved by fterm '-p' option and documentation.
