### ISSUE TITLE
Summary class for field initialization.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#799]
Implement a class that collec information about default ,missing or wrong values of fields. Collect these reports during FieldSet::set_time and report them in single table.

**Comment by jbrezmorf** [comment]
Set default value for print_regions to 'true'.

**Comment by jbrezmorf** [comment]
- prefered just methods of FieldCommon one for getting shared pointer to the table one for output of the table.

**Comment by dflanderka** [comment]
Done.

Format of region table:

  ----------- Table of all regions: -----------
   - Boundary elementary regions -
  name                  id dim
  .1d_bottom             3   0
  .1d_left               2   0
  .1d_top                1   0
  .2d_bottom             9   1
  .2d_left              10   1
  .2d_right              8   1
  .2d_top                7   1
  
   - Bulk elementary regions -
  name                  id dim
  1d_left_branch         6   1
  1d_lower               5   1
  1d_upper               4   1
  2d                    11   2
  
   - Sets of regions -
  name              contains regions
  .BOUNDARY         [".1d_top", ".1d_left", ".1d_bottom", ".2d_top", ".2d_right", ".2d_bottom", ".2d_left"]
  1d_domain         ["1d_upper", "1d_lower", "1d_left_branch"]
  ALL               [".1d_top", ".1d_left", ".1d_bottom", "1d_upper", "1d_lower", "1d_left_branch", ".2d_top", ".2d_right", ".2d_bottom", ".2d_left", "2d"]
  BULK              ["1d_upper", "1d_lower", "1d_left_branch", "2d"]
  ---------------------------------------------

Format of Field warning table:

  00:00:00.845      WARNING.
                    ---------------------------------------- Used default values of Fields: ----------------------------------------
                     Field name                                         Default value       Apply on regions
                     anisotropy (anisotropy)                            1.0                 1d_upper 1d_lower 1d_left_branch 2d
                     cross_section (cross_section)                      1.0                 1d_upper 1d_lower 1d_left_branch 2d
                     sigma (sigma)                                      1.0                 2d
                     water_source_density (water_source_density)        0.0                 1d_upper 1d_lower 1d_left_branch 2d
                     init_pressure (init_pressure)                      0.0                 1d_upper 1d_lower 1d_left_branch 2d
                     storativity (storativity)                          0.0                 1d_upper 1d_lower 1d_left_branch 2d
                    ----------------------------------------------------------------------------------------------------------------

Proposals for improvements:

 - add equation name to Field warning table
 - encapsulate region table to logger message (now is only printout to console output)

**Comment by jbrezmorf** [comment]
Field warning table: We pass the equation name into the output method and print equation name in header. 
Report only key name of the field. What about multifields?

Agree with output of the region table into log.

**Comment by dflanderka** [comment]
Now, every component of multifield is printed to separate rows (with different input name).

Possible solutions:
 - use input_name of the field
 - store only one row for uninitialized multifield (inadequate if some mutifield should have defined different default values for individual components)

**Comment by jbrezmorf** [comment]
OK. Use input_name, that is separate row for every component of the multifield.
