### ISSUE TITLE
Update libs

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#805]
Boost warns a lot about deprecated declarations of some auto_ptr var in smart_ptr. The Warnning is selectively disabled in version 1.60 and later. 
We keep version 1.58 with Ubuntu 16.04 and use our own disable of appropriate warning.
(-Wno-deprecated-declarations).
Result, no special update in boost.

own compilation:
- armadillo
- petsc
- BDDCML

... replace one by one, using the newest version available.

**Comment by janhybs** [comment]
I've update libraries to newest version but there are some compatibility issues, namely:

- [ ] Armadillo `3.4.3` to `8.3.4`
  - [ ] changes [here](http://arma.sourceforge.net/docs.html), section `History of API Additions, Changes and Deprecations`
*not really sure what all we are using, but compilation failed on the end, they were plenty of changes*
  - [x] no patch required during cmake, add option `-DBUILD_SHARED_LIBS=Off` and `-DDETECT_HDF5=Off`


- [ ] Petsc `3.6.1` to `3.8.3`
  - [ ] changes [here](http://www.mcs.anl.gov/petsc/documentation/changes/37.html) and [here](http://www.mcs.anl.gov/petsc/documentation/changes/38.html)
  - [x] added `--with-mpi-dir` since PETSc would find MPI but did not set proper include flags
  - [x] `src/la/linsys_PETSC.cc`, method `PetscOptionsInsertString`
  - [x] `CMake/Modules/FindPETSc.cmake` wrong `PETSC_INCLUDES`, did not included mpi include


- [ ] BDDCML `2.4.0` to `2.5.0`
  - [ ] changes [here](http://users.math.cas.cz/sistek/software/bddcml/changelog-2.5.txt)
  - [x] `/src/la/bddcml_wrapper.ipp` add prefix `_c` to the methods
  - [x] `/src/la/bddcml_wrapper.ipp`, methods `bddcml_upload_subdomain_data_c` and `bddcml_setup_preconditioner_c`, **need to check my solution**

Docker images with new libraries are up on Docker Hub, so to test things out:
`
docker pull flow123d/flow-libs-dev-dbg
`

**Comment by jbrezmorf** [comment]
Please build also shared version of libraries (or possibly only shared version), we have to move to shared libraries (faster linking, smaller binary footprint, especially important when using MPI on single CPU) see issue #183.

**Comment by jbrezmorf** [comment]
Is it possible to pull the image under different name in order to compare?

**Comment by janhybs** [comment]
OK, will use shared libs. As for renaming, it is not possible during pull, but you can rename your original image and then pull the new one:

```
docker tag flow/flow-libs-dev-dbg:latest flow/flow-libs-dev-dbg:old-libs
docker rmi flow/flow-libs-dev-dbg:latest
docker pull flow123d/flow-libs-dev-dbg
```

**Comment by jbrezmorf** [comment]
Can you put here listing of the failed build with new libraries?

**Comment by janhybs** [comment]
Flow123d is successfully compiled but last error is while linking, related to `arma` (gueassing armadillo), will try to find exactly the error. But it may change in the future when switched to the shared libs.

**Comment by janhybs** [comment]
I'm attaching entire make log. Where armadillo linking at the end fails.

Error at the end is:
```
src/libfem_lib.a(mapping_p1.cc.o): In function `MappingP1<3u, 3u>::fill_fe_side_values(flow::FullIteratorId<Element> const&, unsigned int, Quadrature<3u> const&, MappingInternalData&, FEValuesData<3u, 3u>&)':
/home/jan-hybs/projects/flow123d/flow123d/src/fem/mapping_p1.cc:212: undefined reference to `double determinant<arma::Mat<double>::fixed<3ull, 3ull> >(arma::Mat<double>::fixed<3ull, 3ull> const&)'
collect2: error: ld returned 1 exit status
```
[make-static.log](https://github.com/flow123d/flow123d/files/1702789/make-static.log)

**Comment by janhybs** [comment]
Also, I've made some changes and the libs are now shared:
  - Armadillo - no problems
  - YamlCPP - no problems
  - PETSc - no problems with PETSc itself, but some external projects does not support shared libs
  - bddcml - quite a hussle, edited `makefile.inc` for bddcml and blopex to force to create final so, but it appears to be working
  - boost - only change in main `CMakeLists.txt`

**Comment by janhybs** [comment]
Compatibility fixes are in a branch [JHy_libs_update](/flow123d/flow123d/tree/JHy_libs_update)

**Comment by janhybs** [comment]
A new error during compilation:
```
/work/jan-hybs/projects/flow123d/flow123d/src/fem/finite_element.cc: In instantiation of ‘arma::Col<double>::fixed<dim> FiniteElement<dim>::shape_grad(unsigned int, const arma::Col<double>::fixed<dim>&, unsigned int) const [with unsigned int dim = 0u]’:
/work/jan-hybs/projects/flow123d/flow123d/src/fem/finite_element.cc:171:16:   required from here
/work/jan-hybs/projects/flow123d/flow123d/src/fem/finite_element.cc:127:23: error: call of overloaded ‘Col(unsigned int)’ is ambiguous
     arma::vec grad(dim);

```

**Comment by janhybs** [comment]
@jbrezmorf 
A compilation and a linking now succeeds, running simple test however fails:
![image](https://user-images.githubusercontent.com/894428/39471906-1c04e810-4d46-11e8-8797-47dafdcba551.png)

Full output: [petsc-error.log.txt](https://github.com/flow123d/flow123d/files/1963648/petsc-error.log.txt)

**Comment by jbrezmorf** [comment]
Comments to 'dockerrun':
- shortcut script: bin/fterm
- consider rename also to fterm (or frun), 'dockerrun' seems that we call docker
- need to have the workdir with same absolute path in host system as well as in docker since git stores absolute paths and then workdir can not be versioned out of docker; however mounting whole
home makes problems with conflicting .bashrc; 
- not clear which setup should be modified, I only succeed modifying the template.
- custom setup.sh somewhere deep in dir structure is not practical, better have some customization in the main flow dir, or just through some evn variables.
- PS1 colors, light vs. dark background (customization)
- sort of pmake; 'make' command of fterm

**Comment by janhybs** [comment]
Ad 3) I see two possible solutions:
We can mount `$HOME` to `$HOME`
:heavy_minus_sign: flow123d must always be under `$HOME` dir
:heavy_minus_sign: some errors may occur when processing host's` .bashrc` (`.profile`)
:heavy_plus_sign: the mount will make all other project accessible
:heavy_plus_sign: faster building (can also use `ccache`)
:heavy_plus_sign: git will work properly
:heavy_plus_sign: ssh keys will work properly

We can mount `pwd` to `pwd`:
:heavy_minus_sign: may not work properly under Windows
:heavy_minus_sign: `.gitconfig` and `.ssh` will need to be inside container
:heavy_plus_sign: we can specify which directory will be mounted
:heavy_plus_sign: no problems with .bashrc` (`.profile`)

**Comment by jbrezmorf** [comment]
Third option:
 mount a 'workspace' dir, e.g. I have nearly all git repositories in a
$HOME/workspace dir:
+ separate .bashrc (and need copy of .ssh, .gitconfig)
+ git happy
? Windows
+ includes PWD to PWD case
- other custom option
