### ISSUE TITLE
valgrind don't work

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#806]
Using valgrind to run flow123d either within docker or out of it fails with:
Warning: ignored attempt to set SIGRT32 handler in sigaction();
the SIGRT32 signal is used internally by Valgrind
cr_libinit.c:189 cri_init: sigaction() failed: Invalid argument

seems related to Ubuntu and mpich [error](https://bugs.launchpad.net/ubuntu/+source/mpich2/+bug/1045326)

replicate with:
	
	bin/valgrind.sh --

see also discussion [here](
http://stackoverflow.com/questions/10602966/free-crashes-but-only-if-more-than-a-certain-size-of-memory-is-allocated)

Seems that we need either to compile own MPICH (possible simply through PETSC) or use different MPI package, possibly OpenMPI. Or can we install MPICH without BLCR which cause the problem?

**Comment by x3mSpeedy** [comment]
@jbrezmorf  I'v done some testing in [this](https://github.com/x3mSpeedy/mpich-ubuntu-valgrind-issue) repo. Simple c++ code is compiled and then run with/without mpirun with/without valgrind.

| Library    |  no mpi / no valg  |    mpi / no valg   |    no mpi / valg   |     mpi / valg     |     valg / mpi     |
|------------|:------------------:|:------------------:|:------------------:|:------------------:|:------------------:|
| mpich      | :heavy_check_mark: | :heavy_check_mark: |         :x:        |         :x:        | :heavy_check_mark: |
| mpich-blcr | :heavy_check_mark: | :heavy_check_mark: |         :x:        |         :x:        | :heavy_check_mark: |
| openmpi    | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

where:

- `no mpi / no valg` means no mpi or valgrind used
- `mpi / no valg` means mpirun was used but no valgrind
- `no mpi / valg` means no mpi was used but valgrind was called
- `mpi / valg` means no mpi was used and also valgrind was used in order `mpirun -np 2 valgrind <binary>`
- `valg / mpi ` means no mpi was used and also valgrind was used in order `valgrind mpirun -np 2 <binary>`

Also based on the  [official repository page](http://packages.ubuntu.com/xenial/mpich) for `xenial` (ubuntu 16.04). Library BLCR is marked as **suggested** for package `mpich-dev`, therefore is not installed by default. Installing it will not change results in any way.

So what is left to manually compile `mpich` a use that.

**Comment by jbrezmorf** [comment]
Just use openmpi. We need to recompile BDDC and PETSC.

**Comment by jbrezmorf** [comment]
Resolved by our own build of MPICH.
