### ISSUE TITLE
Heat transport DG consume to much memory

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#808]
For a 3D problem consistin of about 17000 elements the Heat model takes about 500 MB top allocation.
See profiler data (petsc) in output dir on:
bacula.nti.tul.cz/intec/projekty/flow123d/input_data/Error_Reports/Balvin_out_of_memory

Darcy with more dofs per element takes 180 MB top. 
Seems that about 50MB of both numbers is due to common part: mesh etc.
So Darcy is about 8kB per element and Heat about 26kB per element.

Seems that lot of memory is taken by symbolic assembly of the ILU preconditioner and further there
are lot of memory used during output.

Investigate better using valgrind massif, detect bottlenecks and try to optimize.

**Comment by jstebel** [comment]
I made some measurements with sequential computations. In this particular problem, the vast memory is consumed by ILU factorization. The peak consumption depends on the no. of factor levels (-pc_factor_levels) as follows:

|levels|2|3|4|5 (default)|
|-------|--|--|--|------------|
|memory [MB]|309|313|347|564|
|BCGS iterations|24|66|27|15|

The fill ratio (-pc_factor_fill) does not play role, values between 2 and 6 (default) do not make any change.

So it seems, that 2 factor levels are best for memory. However for different problems (transport, dominating advection) the results do not lead to the same conclusion.

**Comment by jbrezmorf** [comment]
What about levels 0 (default by PETSC), 1?
What are results for different problems ...

**Comment by jstebel** [comment]
Levels 0 and 1 added to the above comment.

Different problems: for small meshes the difference in memory consumption is negligible but still 2 levels are better than 5. On large mesh the computation under valgrind massif takes too long.
