### ISSUE TITLE
FeValues flags are not stored

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#820]
Seems that at least for FeSideValues the update flags are not stored and thus reinit just updates all.

**Comment by jbrezmorf** [comment]
@jstebel Can you confirm this as a bug?

**Comment by jstebel** [comment]
No. UpdateFlags are stored in FEValuesData, which are initialized from the constructor of FESideValues via this->allocate() and there via data.allocate().

**Comment by jbrezmorf** [comment]
Resolved.
