### ISSUE TITLE
Add death test option to config.yaml

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#831]
- [x] Add option to `config.yaml`. Name of a option is `death_test` with values is one of the following:
 - `false` (default value, no death test will be performed)
 - `true`  requires **any** test to fail in order to pass (return values 0)

**Comment by x3mSpeedy** [comment]
@dflanderka option `death_test` is now supported in `config.yaml` (Only values `true` and `false` are supported for now). [Wiki](https://github.com/flow123d/flow123d/blob/master/tests/README.md) page was also slightly updated. You can either pull master or just cherry pick fca6de8f51ccd0d688786e61ffdb60b32dee5c38

**Comment by jbrezmorf** [comment]
done
