### ISSUE TITLE
time step as function of time

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#835]
- add key 'dt_limits' as Array(Tuple( 'time', 'min_dt', 'max_dt' ))
  meaning a time dependent changes in min_dt and max_dt limits. This list is processed at individual times overwriting previous setting of min_dt/max_dt. Limits equal to 0 are ignored.

- add key 'write_used_timesteps'. If given it provides file name to which the sequence of used timesteps will be written in format that allows passing it to 'dt_limits' using include YAML.

**Comment by dflanderka** [comment]
merge in 4068acf
