### ISSUE TITLE
Documentation 2.2.0

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#836]
Poznamky od Milana:

- [x] str.29 alfa [kg na -1] ma byt [m na -1] ?
- [x] špatně české znaky Cislerova: CA­slerovAa

- [ ] Do manualu doplnit jak se pozna ustalene a neustalene. (zavisle na storativite, ...)

- [x] proč je na str.102 v datech FlowDarcyMH i storativita? (pro steady) ... JB: je asi OK

- [x] str 22 nahoře odkazuje na CON místo na YAML

- [x] str 68 Bedrichov má také špatně češtinu

- [x] 5.2.2 špatně vysázená čísla (znak krát a exponent)

-  [x] v příkladu 1 je `variant: ascii`, ale v input reference není (str 115/116)

- [ ] v dokumentaci proudění chybí popis jak se Darcy přepíná mezi steady a unsteady

- [x] v dokumentaciu FieldElementwise a FieldInterpolated je napsané:
R3 to R Field constant in space.
což mi nedává smysl, myslel jsem naopa že je pro prostorové rozložení (nekonstantní)

- [x] seepage:  vsekci 2.3.2 str 27 se uvádí jako parametr "bc_switch_pressure"
ale na str.111 se uvádí že se má použít bc_pressure/bc_piezo_head
u river je pak na stejném místě oboje, se switch i bez switch
prakticky
kdyz zadam bc_pressure, hlasi default bc_swithc_pressure
kdy zadam bc_switch_pressure, hlasi default bc_pressure
to opravdu chce oboje? co to pak znamená?
... JB: chyba je v referenci k 'bc_type'

JB:
- [x] better description of individual BC fields in reference, fix and add cross links
- [x] for BC seepage, bc_pressure and bc_piezo_head should be disabled

**Comment by jstebel** [comment]
Ideas:
- Consistent key names of equation fields (e.g. exchange_rate vs. sigma).
- How to link equations from fields in Model Editor? (use back references in Latex or include parts of the documentation to field descriptions)

**Comment by jstebel** [comment]
Resolved except for the last comment.

**Comment by jstebel** [comment]
- [ ] Do manualu doplnit jak se pozna ustalene a neustalene. (zavisle na storativite, ...)
- [ ] v dokumentaci proudění chybí popis jak se Darcy přepíná mezi steady a unsteady
- [ ] How to link equations from fields in Model Editor? (use back references in Latex or include parts of the documentation to field descriptions)
- [ ] Consistent key names of equation fields (e.g. exchange_rate vs. sigma).

**Comment by jbrezmorf** [comment]
Yet finish remaining items.
