### ISSUE TITLE
Review RefElement for barycentric coordinates

### ISSUE THREAD

**Issue by dflanderka** [flow123d/flow123d#841]
- review RefElement and intersections for barycentric coordinates, consistently use barycentric coords instead of local coords
- extension of #824

**Comment by jbrezmorf** [comment]
- use 'interpolate' instead of 'barycentric_from_face', first try call 'interpolate' from 'barycentric_from_face'.
- merge 'node_coords' and 'bary_coords'
- Where 'barycentric_on_face' is used?
- Other redundant methods?

**Comment by jbrezmorf** [comment]
done in  beb97ee
