### ISSUE TITLE
Fix water sources in DarcyFlowMH

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#86]
Currently sources are computed on element even for LMH method where they has to be accounted to edges. Postprocess is correct but assembly should differ for LMH.

Make integration test for sources. What about sources due to dimension coupling?

... process this after consolidation of DarcyFlow using possibly just LMH method.

**Comment by jstebel** [comment]
Test 15 uses LMH + sources and water balance does not hold.

**Comment by jstebel** [comment]
Update documentation of numerical method.

**Comment by jbrezmorf** [comment]
Yet need to check and resolve issue with sources due to dimension coupling.
