### ISSUE TITLE
Segfault when observation point is outside the mesh

### ISSUE THREAD

**Issue by jstebel** [flow123d/flow123d#865]
Reported by AB, input files on bacula: \intec\lide\ales.balvin\00_share\toHonza\mshSIT_nefunkční

When the observation point is outside the domain, the method ObservePoint::find_observe_point() finds no candidate elements and consequently tries to access a vector "process_list" of zero size.

**Comment by jbrezmorf** [comment]
Input data: http://flow.nt.tul.cz/input_data/Error_Reports/170726_Balvin_observe_segfault
