### ISSUE TITLE
Parallel VTK output

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#872]
- study VTK parallel output format, are cell and node IDs unique over processors? How are node data merged together?
- anlyse meshes converted from OpenFOAM to parallel VTK either by OpenFOEM tool or in Paraview

**Comment by jbrezmorf** [comment]
TODO: 
- make simple test parallel time-dependent output both using 'pvtu' and using 'pvd' ('part' attribute)

**Comment by dflanderka** [comment]
- 'pvd' with part attribute can be used for cases of parallel output (time-dependent and independent)
- 'pvtu' can be used only for parallel output with one time step (not necessary for us)

**Comment by jbrezmorf** [comment]
- add new method for creation of local output mesh, see loop over local elements in transport.cc create_matrix ...
- evaluation of fields in Field::output() should use output mesh references to original elements for filling the output cache

**Comment by jbrezmorf** [comment]
Seems that we need only:
- new method in OutputMesh to create only local part of the computing mesh
- write partition info into PVD file (we do not use pvtu).

**Comment by dflanderka** [comment]
Merged in 8386e05d6e1f7c16f3653d934b4abb591fb6e8d8.
