### ISSUE TITLE
Test interpolation output

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#876]
- test that we can make output of 'pressure_p0' and 'velocity' in nodes and corners
- test output of 'temperature' from DG heat  in element centers and nodes
- test output of 'conc' from FV transport  in nodes and corners
... make a one or two tests in 03_generic_output

**Comment by jbrezmorf** [comment]
Reuse test `40_heat/02_flow_transport_heat` which variable conductivity in rock domain:
```
      - region: rock
        conductivity: !FieldFormula
		value: y + 1.0
        cross_section: 1
```

**Comment by jbrezmorf** [comment]
- [ ] Register interpolation types of fields to OutputStream during EquationOutput initialization.
- [ ] In creation of output mesh use this information from all registered output intrepolation types to create correct output mesh.
- [ ] Simplyfy TimeOutput::get_output_mesh
- [ ] Modify GMSH to use output mesh not computing mesh. Deal with original IDs.

**Comment by dflanderka** [comment]
see pull #877
