### ISSUE TITLE
Time units

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#894]
- Create a specific tuple for a time value. (time, unit)
- Use this tuple for a time values everywhere instead of current 'double' scalar.

**Comment by dflanderka** [comment]
Generating methods in code, where tuple will be used:
- FieldCommon::field_descriptor_record() - key 'time'
- OutputTimeSet::get_input_type() - keys 'begin', 'step', 'end'
- TimeGovernor::get_input_type() - keys 'start_time', 'end_time', 'init_dt', 'min_dt', 'max_dt'
- TableFunction::get_input_type_val() - key 't' ?

**Comment by jbrezmorf** [comment]
- Have common time unit set in TimeGovernor, this unit will be used for all time inputs and outputs within the equation.
- Involved outputs: Balance, Observe, TimeOutput
- We should set time units of the fields during call of set_input_list in order to make shared fields work well in the case of equations with different time units. Need an integration test for this.

**Comment by jbrezmorf** [comment]
- TimeGovernor::read_time( Iterator<IT::Tuple>, default_time=NaN)
  test how this methods can be used both for obligatory, optional, and at_read_time time keys 
- Propose a similar method 'output_time' to convert a time in seconds to default time unit, have getter for default time unit in order to output the unit with the value.
