### ISSUE TITLE
clean trunk_1.8 - LinSys

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#90]
Following notes should be considered when adopting deal.ii la part, #23 :
- [x] Simplify builds of deal.ii - turn off build of code not related to linear algebra
- [ ] Identify work that is necessary to use deal.ii linear system classes instead of LinSys classes
- [ ] Move SchurComplement and BDDC under deal.ii interface.
- [ ] Replace usage of LinSys with deal.ii.

Consider how to deal with following ideas:
- add
  enum LinSys::ConvergenceReason LinSys::get_convergence_info(string &)
  returning reason code and text description 
- report iterations and reason to log file after every solve, can determine  information (like full convergency monitor) through input interface
- remove similar messages in individual equations
- Let LinSys to create its own solution vector automatically.
  remove currently necessary calls set_solution(NULL) in equations
- simplify LinSys::get_whole_solution and DarcyFlow::get_solution_vector: 
  1) we should use at least std::vector to pass raw data serial vector (until we have proper class for both serial and parallel vectors)
  2) scatter is now moved into LinSys and also make reordering, this has to be clarified. LinSys should not provide this since there could be more different scatters( e.g. to serial for output or to possible different mesh partitioning of different equation)
  ... we should just sum local portions of BDDC solution to get same thing as provided by PETSC.
  Update: probably this is already resolved
- one common getter and setter for various matrix properties, this usually is not performance critical
  property given either as string or as enum value; internally the states can be hold in separate variables
  since some of them (status) are used in critical parts of implementation
- is method set_whole_solution necessary ?
- remove matrix interface (namely PETSc dependent methods), make separate wrapper class for matrix 
  representations
- use our Vector wrappers to return RHS and or solution
- clean interface of LinSys base class

**Comment by jbrezmorf** [comment]
related to #431

**Comment by jstebel** [comment]
The aim is to remove LinSys and instead use dealii's wrappers for PETSc vectors, matrices and solvers.

Solvers will need to be initialized from input, so we will have to:
- either modify the corresponding classes in dealii fork. Problems will arise due to dependence on Input.
- or inherit or wrap into Flow123d's classes.

**Comment by jstebel** [comment]
Further notes at
https://docs.google.com/document/d/1CHqmklWpntSJMW2DZDaVTP_I8qgY_OovHNme732rEN0/edit#
