### ISSUE TITLE
flow.nti.tul.cz serving wrong mime svg type

### ISSUE THREAD

**Issue by janhybs** [flow123d/flow123d#919]
When loading `svg` images from the `bacula`, server does not send correct `mime type` header to the browsers, which causes `svg` images to not be displayed, more [here](https://stackoverflow.com/questions/10901836/svg-images-displayed-as-broken-images-on-server).

For now, we are loading svg images from github.io

**Comment by jbrezmorf** [comment]
Is this issue actual yet?

**Comment by janhybs** [comment]
With `bacula` -> `astra` transfer, issue resurfaced once again so I moved all `svg`s to github.io repository and it is working.
https://flow.nti.tul.cz/packages/3.0.1_dev/htmldoc/

**Comment by jbrezmorf** [comment]
OK, so I'm closing this. You can reopen it if necessary.
