### ISSUE TITLE
Native IO for conc.

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#963]
@Paulie14 
- [x]  Create test A for writing a native conc data of TransportDG, three variants: P0, P1, P2.
        Square domain, subsquares with significantly different conductivity, pressure jump.
        BC conc on left conductive part of boundary. Simulation time till steady state.
        Write native conc in steady state.
        After steady state time, turn off conc on inflow BC.
        Write subsequent simulated conc as reference data for the test B.

- [x] Create test B for reading init conc from native data.
        Same geometry and flow as in test A.
        Read init conc from native format.
        Check that the conc simulation is the same as in test B.

@dflanderka 
- [ ]  Test that test A CORNER data output is same as the NATIVE output of test A once it is read in test B and output as CRONER data.
- [ ] @jstebel How to turn off interpolation of initial concentration fi given as NATIVE.
- [ ] Fix lists of Scalars, Vectors, Tensors for the Flow123dData tag of the native output.

**Comment by jbrezmorf** [comment]
Test A probably 03/43 (currently commented) test B probably 03/42 (currently commented).

@Paulie14 
TODO: test it

**Comment by Paulie14** [comment]
The tests were prepared for @dflanderka , so that he could further work on native IO.
I tried the native output of conc in test 43 (testA), but it fails on the assert:
```
Program Error: Violated assert! 
      ##                   > In file: /home/paulie/Workspace/flow123d/src/fields/field_fe.cc(817): Throw in function native_data_to_cache
      ##                   > Expression: 'output_data_cache.n_values() * output_data_cache.n_comp() == dh_->distr()->lsize()'
      ##                   > Values:
      ##                     output_data_cache.n_values() * output_data_cache.n_comp() : '1000'
      ##                     dh_->distr()->lsize() : '3000'
      ##                   
      ##                   ** Stacktrace **
      ##                     0  FieldFE<3, FieldValue_<1, 1, double> >::native_data_to_cache(ElementDataCache<double>&)
      ##                     1  Field<3, FieldValue_<1, 1, double> >::fill_data_cache(OutputTime::DiscreteSpace, std::shared_ptr<OutputTime>, std::shared_ptr<ElementDataCache<double> >)
      ##                     2  Field<3, FieldValue_<1, 1, double> >::compute_field_data(OutputTime::DiscreteSpace, std::shared_ptr<OutputTime>)
      ##                     3  MultiField<3, FieldValue_<1, 1, double> >::field_output(std::shared_ptr<OutputTime>)
      ##                     4  EquationOutput::output(TimeStep)
      ##                     5  TransportDG<ConcentrationTransportModel>::output_data()
      ##                     6  TransportDG<ConcentrationTransportModel>::zero_time_step()
      ##                     7  TransportOperatorSplitting::zero_time_step()
      ##                     8  HC_ExplicitSequential::advection_process_step(HC_ExplicitSequential::AdvectionData&)
      ##                     9  HC_ExplicitSequential::run_simulation()
      ##                    10  Application::run()
      ##                    11  main
```

When I switch to FV transport, it works (meaning it outputs something).
In case of DG, it seems, that the `ElementCache` is not appropriate for the P1 discontinous approx. of concentration...

Any hints??

**Comment by Paulie14** [comment]
Seems that Native data currently works only for "constant elementwise" data. 

DG transport default order is 1, therefore `n_dofs_per_element` is equal 3.
However in Native output is:
`dof_handler_hash="3000" n_dofs_per_element="1"`
coming from `output_vtk.cc:487`
```
file  << "dof_handler_hash=\"" << output_data->dof_handler_hash() << "\" ";
file  << "n_dofs_per_element=\"" << output_data->n_comp() << "\"";
```
**What is the meaning of `dof_handler_hash`?**
**How can we get correct `n_dofs_per_element` at this place (somehow access `DofHandler` through `ElementDataCache`)?**

Then, when reading the vtu data file in `msh_vtkreader.cc:256`
the number of entities is not `n_elements` but the actual number of saved DoFs in the file
which must be equal to number of DoFs of the `ElementDataCache` into which we want to read..


I get lost in all these reader and output classes.
However the point of Native Data in this test is:
- write the Native data into vtk (P1 DG data for concentration - the solution vector in DG transport)
- read these data into init_conc for DG

**Comment by jbrezmorf** [comment]
In order to initialize a field (e.g. "init_conc_A" - component of a multifield) from native input, we have to inform the field
which dofhandler to use so that the created FieldFE can set that dofhandler. It seems that there is no way to provide such information in current code (but I can be wrong). 

Proposed solution: 
Introduce FeildFE::NativeFactory that would keep the dofhandler. Example of usage:

```
conc_dof_handler = ...
data.init_conc['A'].add_factory(FieldFE::NativeFactory(conc_dof_handler, optional_dof_vector));
```
NativeFactory will create FieldFE using provided dof_handler and optional dof vector.

**Comment by jbrezmorf** [comment]
Full resolution depends also on #1344.

**Comment by Paulie14** [comment]
- working tests 42 and 43
- added switch for DG initial projection
- still not sure about the effect of the projection - no test with significant effect (i prepared test with sinusoidal b.c. but it is propably too smooth... - continue in #1354

PR in branches `DF_fix_native_io` and `PE_DG_initcond`

**Comment by Paulie14** [comment]
PR merged: `DF_fix_native_io` and `PE_DG_initcond`, see #1352.
