### ISSUE TITLE
Optimize sorptions through better FieldFormula

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#971]
In FieldFormula use parser to detect that there is only dependency on time. In that case is_constant method should return true, which enable table optimizations in Sorptions.

TODO:
- introduce a flag is_constant_in_space in FieldCommon, reimplement is_constant method
- set this flag to False as default
- set the flag to trure for FieldConstant and FieldTimeFunction
- set the flag to true if FieldFormula does not depend on x,y,z,d

**Comment by Paulie14** [comment]
Tested on
```bacula.nti.tul.cz/intec/projekty/flow123d/input_data/Error_Reports/slow_sorption/```
I tried changing the value of rock_density in sorption:

- works fast [16s] - uses interpolation tables:
```
rock_density: 2.0
```
- works fast [16s] - uses interpolation tables:
```
rock_density: !FieldFormula
    value: 2.0
```
- works very slow [784s] - cannot use interpolation tables, calls isotherm reinit every time step
```
rock_density: !FieldFormula
    value: 2.0*x
```
