### ISSUE TITLE
FieldFE simplifications

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#988]
Some simplifications and thinks to finish from merging FieldElementwise to FieldFE.

- [x] Check carefully, that we can create DoFHandler for boundary mesh. Since current implementation without distinguishing bulk and boundary mesh should not work. Check:
	- mesh->element_range() iterates only over bulk elements
	- mesh->raw_4_el_ have size of just bulk elements, 
	- mesh->n_elements() returns just bulk elements
- [x] Temporary solution until we have working BC dof handler: FieldFE have its own dof idices vector for P0 boundary field.
- [x] Define Mesh interface used by DofHandler and duplicate_nodes
- [x] Create Duplicate nodes for the boundary mesh.
- [x] Implement other parts of the boundary mesh.
- [x] Modification of DoFHandler to support BoundaryMesh, 

 
- shared DofHandler repository otherwise every FieldFE have own dofhandler
- [x] check_compatible_mesh should only perform the check, setting id maps should be done in FeildFE.set_mesh
- [x] remove `fields/field_elementwise.*`, `fields/field_interpolated_p0.*` and appropriate unit tests
- [x] remove XYZ_reader.check_compatible_mesh
- [x] remove commented code of VectorSeqDouble in appropriate header file and unit test, rename both files to 'vector_mpi*'

**Comment by dflanderka** [comment]
After fix BCMesh class, remove temporary solution (commit 8c48eca) in FieldFE and FEValueHandler.

**Comment by Paulie14** [comment]
Do also #1163.

**Comment by jbrezmorf** [comment]
Many things done. Review and move remaining parts to the new issue for 4.0.0.
