### ISSUE TITLE
Version 2.2.1

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#992]
- [x] Backport left/right side issue in DG transport bug
- [x] Backport of docker systemu, fterm script.
- [x] raw output

... is done in branch PE_2.2.0

- [x] How to make install packages?
- [x] Build on flow123d
- [x] Publish on flow123d page

**Comment by Paulie14** [comment]
PE and JHy 2.2.0 branches merged in branch 2.2.1.
