### ISSUE TITLE
precision of nodes in GMSH output

### ISSUE THREAD

**Issue by jbrezmorf** [flow123d/flow123d#993]
- check that precision parameter influence also precision of node coordinates
- report to Jiri Landa the parameter and version in 2.2.x branch or in 3.x branch that support the precision parameter

**Comment by Paulie14** [comment]
status:
- 2.1.2 does not support precision setting
- since 2.2.0, precision can be set via
```
output_stream:
  precision: 14
```
- no integration test for GMSH output (I will create one and test it)
- according to code, 'precision' is set globally to ofstream, so all values should be written with the same precision

**Comment by Paulie14** [comment]
Solution:
- create a test for gmsh format
- create version 2.2.1 for Jiri Landa

**Comment by jbrezmorf** [comment]
done
